package api

import (
	"fmt"
	"os"
	"strings"
)

// WriteSimulatorConfig generates a simulator.yaml file from the seed state.
// Uses fmt.Fprintf instead of yaml marshaling to avoid adding a yaml dependency to the seed package.
func WriteSimulatorConfig(state *SeedState, path string) error {
	var b strings.Builder

	fmt.Fprintf(&b, "# Auto-generated by seed command. Do not edit manually.\n")
	fmt.Fprintf(&b, "base_url: %s\n", state.BaseURL)
	fmt.Fprintf(&b, "refresh_interval: 30s\n")
	fmt.Fprintf(&b, "\n")

	// Event config
	fmt.Fprintf(&b, "event:\n")
	fmt.Fprintf(&b, "  interval: 5s\n")
	fmt.Fprintf(&b, "  max_events_per_tick: 3\n")
	fmt.Fprintf(&b, "  rotation:\n")
	fmt.Fprintf(&b, "    order: [heimatraum, ag, schulhof, heimatraum]\n")
	fmt.Fprintf(&b, "    min_ag_hops: 1\n")
	fmt.Fprintf(&b, "    max_ag_hops: 2\n")
	fmt.Fprintf(&b, "  actions:\n")
	fmt.Fprintf(&b, "    - type: checkin\n")
	fmt.Fprintf(&b, "      weight: 1.0\n")
	fmt.Fprintf(&b, "    - type: checkout\n")
	fmt.Fprintf(&b, "      weight: 0.8\n")
	fmt.Fprintf(&b, "    - type: schulhof_hop\n")
	fmt.Fprintf(&b, "      weight: 0.4\n")
	fmt.Fprintf(&b, "    - type: attendance_toggle\n")
	fmt.Fprintf(&b, "      weight: 0.4\n")
	fmt.Fprintf(&b, "    - type: supervisor_swap\n")
	fmt.Fprintf(&b, "      weight: 0.3\n")
	fmt.Fprintf(&b, "\n")

	// Devices - map device[i] -> betreuer[i] -> activity[i]
	fmt.Fprintf(&b, "devices:\n")

	numDevices := len(DemoDevices)
	numBetreuer := len(state.Accounts.Betreuer)
	numActivities := len(DemoActivities)

	count := numDevices
	if numBetreuer < count {
		count = numBetreuer
	}
	if numActivities < count {
		count = numActivities
	}

	for i := 0; i < count; i++ {
		device := DemoDevices[i]
		betreuer := state.Accounts.Betreuer[i]
		activity := DemoActivities[i]

		deviceState, ok := state.Devices[device.DeviceID]
		if !ok {
			continue
		}

		activityID, ok := state.Activities[activity.Name]
		if !ok {
			continue
		}

		roomID, ok := state.Rooms[activity.DefaultRoom]
		if !ok {
			continue
		}

		fmt.Fprintf(&b, "  - device_id: %s\n", device.DeviceID)
		fmt.Fprintf(&b, "    api_key: %s\n", deviceState.APIKey)
		fmt.Fprintf(&b, "    teacher_ids: [%d]\n", betreuer.TeacherID)
		fmt.Fprintf(&b, "    default_session:\n")
		fmt.Fprintf(&b, "      activity_id: %d\n", activityID)
		fmt.Fprintf(&b, "      room_id: %d\n", roomID)
		fmt.Fprintf(&b, "      supervisor_ids: [%d]\n", betreuer.StaffID)
	}

	if err := os.WriteFile(path, []byte(b.String()), 0o600); err != nil {
		return fmt.Errorf("write simulator config: %w", err)
	}
	return nil
}
