package api

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestWriteSimulatorConfig_GeneratesValidYAML(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "simulator.yaml")

	state := &SeedState{
		BaseURL:   "http://localhost:8080",
		DevicePIN: "1234",
		Accounts: SeedStateAccounts{
			Betreuer: []AccountCredentials{
				{Name: "Julia Klein", StaffID: 10, TeacherID: 100, Email: "demo11@mail.de"},
				{Name: "Markus Wolf", StaffID: 20, TeacherID: 200, Email: "demo12@mail.de"},
			},
		},
		Devices: map[string]SeedDevice{
			"demo-device-001": {APIKey: "key-001", Name: "Scanner 1"},
			"demo-device-002": {APIKey: "key-002", Name: "Scanner 2"},
		},
		Rooms: map[string]int64{
			"OGS-Raum 1":  1,
			"Sporthalle":  2,
			"Kreativraum": 3,
			"Mensa":       4,
			"OGS-Raum 2":  5,
			"Schulhof":    6,
		},
		Activities: map[string]int64{
			"Hausaufgaben": 50,
			"Fußball":      51,
			"Basteln":      52,
			"Kochen":       53,
			"Lesen":        54,
			"Musik":        55,
			"Tanzen":       56,
			"Schach":       57,
			"Garten":       58,
			"Freispiel":    59,
		},
	}

	err := WriteSimulatorConfig(state, path)
	require.NoError(t, err)

	content, err := os.ReadFile(path)
	require.NoError(t, err)
	yaml := string(content)

	// Check header
	assert.Contains(t, yaml, "Auto-generated by seed command")
	assert.Contains(t, yaml, "base_url: http://localhost:8080")
	assert.Contains(t, yaml, "refresh_interval: 30s")

	// Check event config
	assert.Contains(t, yaml, "event:")
	assert.Contains(t, yaml, "interval: 5s")
	assert.Contains(t, yaml, "max_events_per_tick: 3")
	assert.Contains(t, yaml, "type: checkin")
	assert.Contains(t, yaml, "type: checkout")

	// Check devices section
	assert.Contains(t, yaml, "devices:")
	assert.Contains(t, yaml, "device_id: demo-device-001")
	assert.Contains(t, yaml, "api_key: key-001")
}

func TestWriteSimulatorConfig_LimitedByMinCount(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "sim.yaml")

	// Only 1 betreuer but 10 devices and 10 activities
	state := &SeedState{
		BaseURL: "http://localhost:8080",
		Accounts: SeedStateAccounts{
			Betreuer: []AccountCredentials{
				{Name: "Julia Klein", StaffID: 10, TeacherID: 100},
			},
		},
		Devices: map[string]SeedDevice{
			"demo-device-001": {APIKey: "key-001", Name: "Scanner 1"},
			"demo-device-002": {APIKey: "key-002", Name: "Scanner 2"},
		},
		Rooms: map[string]int64{
			"OGS-Raum 1": 1,
			"Sporthalle": 2,
		},
		Activities: map[string]int64{
			"Hausaufgaben": 50,
			"Fußball":      51,
		},
	}

	err := WriteSimulatorConfig(state, path)
	require.NoError(t, err)

	content, err := os.ReadFile(path)
	require.NoError(t, err)
	yaml := string(content)

	// Should only have 1 device entry (limited by betreuer count)
	count := strings.Count(yaml, "device_id:")
	assert.Equal(t, 1, count, "should be limited by minimum of devices/betreuer/activities")
}

func TestWriteSimulatorConfig_SkipsDeviceWithoutAPIKey(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "sim.yaml")

	state := &SeedState{
		BaseURL: "http://localhost:8080",
		Accounts: SeedStateAccounts{
			Betreuer: []AccountCredentials{
				{Name: "Julia Klein", StaffID: 10, TeacherID: 100},
			},
		},
		Devices:    map[string]SeedDevice{}, // No device for demo-device-001
		Rooms:      map[string]int64{"OGS-Raum 1": 1},
		Activities: map[string]int64{"Hausaufgaben": 50},
	}

	err := WriteSimulatorConfig(state, path)
	require.NoError(t, err)

	content, err := os.ReadFile(path)
	require.NoError(t, err)
	yaml := string(content)

	// No device entries should be written
	assert.NotContains(t, yaml, "device_id:")
}

func TestWriteSimulatorConfig_ErrorOnInvalidPath(t *testing.T) {
	state := &SeedState{BaseURL: "http://localhost:8080"}
	err := WriteSimulatorConfig(state, "/nonexistent/dir/sim.yaml")
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "write simulator config")
}

func TestWriteSimulatorConfig_EmptyState(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "sim.yaml")

	state := &SeedState{
		BaseURL:    "http://localhost:8080",
		Devices:    map[string]SeedDevice{},
		Rooms:      map[string]int64{},
		Activities: map[string]int64{},
	}

	err := WriteSimulatorConfig(state, path)
	require.NoError(t, err)

	content, err := os.ReadFile(path)
	require.NoError(t, err)
	yaml := string(content)

	assert.Contains(t, yaml, "base_url:")
	assert.Contains(t, yaml, "devices:")
	assert.NotContains(t, yaml, "device_id:") // no devices to write
}
