version: "2"

run:
  timeout: 10m

linters:
  default: standard
  enable:
    - sloglint
  settings:
    sloglint:
      no-mixed-args: true
      key-naming-case: snake
      args-on-sep-lines: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
