name: Question / Support
description: Ask a question or request support
title: "[QUESTION]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out! Please provide the details below so we can best help you.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Please be as specific as possible with your question...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What are you trying to accomplish? This helps us provide a more relevant answer.
      placeholder: Describe what you're working on and why you need help...
    validations:
      required: true

  - type: textarea
    id: attempted
    attributes:
      label: What have you tried?
      description: Have you looked at documentation or tried any solutions?
      placeholder: Describe what you've already attempted...

  - type: dropdown
    id: area
    attributes:
      label: Area of Question
      description: What area does your question relate to?
      options:
        - Installation/Setup
        - Frontend Features
        - Backend Features
        - Database
        - Authentication
        - Deployment
        - Documentation
        - Other (specify in context)
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other context, screenshots, or references that might help us answer your question
      placeholder: Include any other details that might be helpful...
