name: Refactoring Request
description: Suggest improvements to existing code without changing functionality
title: "[REFACTOR]: "
labels: ["refactoring"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting code improvements! Please provide details to help us understand the refactoring needed.

  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: Describe the current code/feature that needs refactoring. What problems does it have?
      placeholder: Explain the current implementation and its issues (complexity, maintainability, performance, etc.)
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: Refactoring Goals
      description: What would you like to achieve with this refactoring?
      placeholder: |
        Example goals:
        - Improve performance
        - Reduce complexity
        - Improve maintainability
        - Enhance readability
        - Fix technical debt
    validations:
      required: true

  - type: textarea
    id: approach
    attributes:
      label: Suggested Approach
      description: How do you suggest we refactor this code?
      placeholder: Describe your suggested refactoring approach, pattern changes, or architectural improvements
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope and Impact
      description: What files/components will be affected? How extensive is this refactoring?
      placeholder: List affected files, components, or services and potential impact on the system
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What benefits will this refactoring bring?
      placeholder: Explain quantifiable improvements (e.g., performance gains, reduced complexity metrics)
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Before submitting, please confirm that...
      options:
        - label: This refactoring maintains the same functionality (no behavior changes)
          required: true
        - label: I've considered the effort-to-benefit ratio of this refactoring
          required: true
