import type { Icon as PhosphorIcon } from "@phosphor-icons/react";
import {
  ArrowUpRightIcon as ArrowUpRight,
  ArrowsClockwiseIcon as Repeat,
  ArrowsLeftRightIcon as ArrowsLeftRight,
  BankIcon as Landmark,
  BellRingingIcon as BellRing,
  BuildingsIcon as Building2,
  CalendarCheckIcon as CalendarCheck,
  CalendarDotsIcon as CalendarDays,
  CalendarPlusIcon as CalendarPlus,
  ChartBarIcon as BarChart3,
  ChatCircleTextIcon as MessageSquareText,
  ChatsCircleIcon as ChatsCircle,
  ClipboardTextIcon as ClipboardList,
  ClockAfternoonIcon as ClockAfternoon,
  ClockIcon as Clock3,
  DatabaseIcon as Database,
  DeviceMobileIcon as Smartphone,
  DeviceTabletIcon as TabletSmartphone,
  DevicesIcon as Devices,
  DoorOpenIcon as DoorOpen,
  DownloadSimpleIcon as Download,
  EnvelopeOpenIcon as EnvelopeOpen,
  EyeIcon as Eye,
  EyeSlashIcon as EyeSlash,
  FileTextIcon as FileText,
  FolderOpenIcon as FolderOpen,
  ForkKnifeIcon as UtensilsCrossed,
  GearIcon as Settings,
  GraduationCapIcon as GraduationCap,
  KeyIcon as KeyRound,
  ListChecksIcon as ListChecks,
  MagnifyingGlassIcon as Search,
  MapPinIcon as MapPin,
  MegaphoneIcon as Megaphone,
  MonitorIcon as Monitor,
  PasswordIcon as Password,
  PlugIcon as PlugZap,
  ScanIcon as Scan,
  ShieldCheckIcon as ShieldCheck,
  ShieldWarningIcon as ShieldAlert,
  SignInIcon as LogIn,
  SignOutIcon as LogOut,
  SlidersHorizontalIcon as SlidersHorizontal,
  SparkleIcon as Sparkles,
  StudentIcon as Student,
  SunHorizonIcon as SunHorizon,
  TableIcon as Table,
  TimerIcon as Timer,
  TrashIcon as Trash2,
  UserCircleIcon as UserCircle,
  UserFocusIcon as UserRoundSearch,
  UserPlusIcon as UserRoundPlus,
  UsersIcon as Users,
  WatchIcon as Watch,
} from "@phosphor-icons/react/ssr";

/**
 * Icons der Hilfeartikel. Die Artikel in `help-content.ts` nennen nur den
 * Namen: `help-content.ts` laedt jeder Seitenkopf ueber `ContextHelpLink`,
 * und ein Phosphor-Icon bringt alle Strichstaerken mit. Die Icons selbst
 * laedt so nur die Hilfeseite.
 */
export const HELP_ICONS = {
  ArrowUpRight,
  Repeat,
  ArrowsLeftRight,
  Landmark,
  BellRing,
  Building2,
  CalendarCheck,
  CalendarDays,
  CalendarPlus,
  BarChart3,
  MessageSquareText,
  ChatsCircle,
  ClipboardList,
  ClockAfternoon,
  Clock3,
  Database,
  Smartphone,
  TabletSmartphone,
  Devices,
  DoorOpen,
  Download,
  EnvelopeOpen,
  Eye,
  EyeSlash,
  FileText,
  FolderOpen,
  UtensilsCrossed,
  Settings,
  GraduationCap,
  KeyRound,
  ListChecks,
  Search,
  MapPin,
  Megaphone,
  Monitor,
  Password,
  PlugZap,
  Scan,
  ShieldCheck,
  ShieldAlert,
  LogIn,
  LogOut,
  SlidersHorizontal,
  Sparkles,
  Student,
  SunHorizon,
  Table,
  Timer,
  Trash2,
  UserCircle,
  UserRoundSearch,
  UserRoundPlus,
  Users,
  Watch,
} as const satisfies Record<string, PhosphorIcon>;

export type HelpIconName = keyof typeof HELP_ICONS;
