package contract

import (
	"fmt"

	"github.com/moto-nrw/project-phoenix/e2e/scenarios"
)

// TypeScriptModule returns the generated frontend contract module for the
// Playwright harness. The Go manifest structs stay the single source of truth;
// the frontend consumes this generated Zod schema + inferred types instead of
// hand-maintaining a second copy of the manifest shape.
func TypeScriptModule() string {
	return fmt.Sprintf(`// Code generated by go run main.go e2e print-contract-ts. DO NOT EDIT.
import { z } from "zod";

export const E2E_MANIFEST_VERSION = %q as const;
export const E2E_SCENARIO_NAME = %q as const;
export const E2E_SCENARIO_MODE_SINGLE_TENANT = %q as const;
export const E2E_SCENARIO_MODE_MULTI_TENANT = %q as const;
export const E2E_SETUP_ROLE_ADMIN = %q as const;
export const E2E_SETUP_ROLE_STAFF = %q as const;
export const E2E_DEFAULT_BACKEND_URL = %q as const;
export const E2E_DEFAULT_TENANT_DOMAIN = %q as const;
export const E2E_DEFAULT_FRONTEND_PORT = %d as const;

export const e2eRuntimeConfigSchema = z.object({
  backend_url: z.string().min(1),
  tenant_domain: z.string().min(1),
  frontend_port: z.number().finite(),
  operator_hostname: z.string().min(1),
});
export type E2ERuntimeConfig = z.infer<typeof e2eRuntimeConfigSchema>;

export const e2eTenantSchema = z.object({
  organization_id: z.number().finite(),
  school_id: z.number().finite(),
  slug: z.string().min(1),
  name: z.string().min(1),
});
export type E2ETwitterTenant = z.infer<typeof e2eTenantSchema>;

const actorBaseSchema = z.object({
  email: z.string().min(1),
  password: z.string().min(1),
  display_name: z.string().min(1),
  staff_id: z.number().finite(),
});

export const seedAdminActorSchema = actorBaseSchema.extend({
  role: z.literal("admin"),
});
export type SeedAdminActor = z.infer<typeof seedAdminActorSchema>;

export const seedStaffActorSchema = actorBaseSchema.extend({
  role: z.literal("user"),
});
export type SeedStaffActor = z.infer<typeof seedStaffActorSchema>;

export const e2eStudentRefSchema = z.object({
  id: z.number().finite(),
  first_name: z.string().min(1),
  last_name: z.string().min(1),
  group_key: z.string().min(1),
  class: z.string().min(1),
});
export type E2EStudentRef = z.infer<typeof e2eStudentRefSchema>;

export const e2eStudentPairSchema = z.object({
  primary: e2eStudentRefSchema,
  secondary: e2eStudentRefSchema,
});
export type E2EStudentPair = z.infer<typeof e2eStudentPairSchema>;

export const e2eGroupRefSchema = z.object({
  id: z.number().finite(),
  key: z.string().min(1),
  display_name: z.string().min(1),
});
export type E2EGroupRef = z.infer<typeof e2eGroupRefSchema>;

export const e2eGroupPairSchema = z.object({
  primary: e2eGroupRefSchema,
  secondary: e2eGroupRefSchema,
});
export type E2EGroupPair = z.infer<typeof e2eGroupPairSchema>;

export const e2eRoomRefSchema = z.object({
  id: z.number().finite(),
  name: z.string().min(1),
});
export type E2ERoomRef = z.infer<typeof e2eRoomRefSchema>;

export const e2eActivityRefSchema = z.object({
  id: z.number().finite(),
  name: z.string().min(1),
});
export type E2EActivityRef = z.infer<typeof e2eActivityRefSchema>;

export const e2eCheckinFixtureSchema = z.object({
  student: e2eStudentRefSchema,
  room: e2eRoomRefSchema,
  activity: e2eActivityRefSchema,
  device_key: z.string().min(1),
  rfid_tag: z.string().min(1),
  supervisor: seedAdminActorSchema,
});
export type E2ECheckinFixture = z.infer<typeof e2eCheckinFixtureSchema>;

export const operatorCredentialsSchema = z.object({
  email: z.string().min(1),
  password: z.string().min(1),
});
export type OperatorCredentials = z.infer<typeof operatorCredentialsSchema>;

export const switchingSchema = z.object({
  link_email: z.string().min(1),
  verified: z.boolean(),
  actor: seedAdminActorSchema,
});
export type Switching = z.infer<typeof switchingSchema>;

export const e2eAuthSetupSchema = z.object({
  roles: z.array(z.string().min(1)).min(1),
  requires_secondary_tenant: z.boolean(),
  requires_verified_switching: z.boolean(),
});
export type E2EAuthSetup = z.infer<typeof e2eAuthSetupSchema>;

export const e2eSetupSchema = z.object({
  auth: e2eAuthSetupSchema,
});
export type E2ESetup = z.infer<typeof e2eSetupSchema>;

export const deviceSchema = z.object({
  key: z.string().min(1),
  api_key: z.string().min(1),
  pin: z.string().min(1),
});
export type Device = z.infer<typeof deviceSchema>;

export const e2eManifestSchema = z.object({
  version: z.literal(E2E_MANIFEST_VERSION),
  runtime: e2eRuntimeConfigSchema,
  scenario: z.object({
    name: z.string().min(1),
    mode: z.string().min(1),
  }),
  setup: e2eSetupSchema,
  tenants: z.object({
    primary: e2eTenantSchema,
    secondary: e2eTenantSchema.optional(),
  }),
  actors: z.object({
    admin: seedAdminActorSchema,
    staff: seedStaffActorSchema,
    operator: operatorCredentialsSchema.optional(),
  }),
  switching: switchingSchema.optional(),
  devices: z.object({
    default_checkin: deviceSchema,
  }),
  fixtures: z.object({
    students: z.object({
      search_pair: e2eStudentPairSchema,
    }),
    groups: z.object({
      visible_pair: e2eGroupPairSchema,
    }),
    checkin: e2eCheckinFixtureSchema,
  }),
});
export type E2EManifest = z.infer<typeof e2eManifestSchema>;
`,
		ManifestVersion,
		scenarios.NameE2EMultiTenant,
		scenarios.ModeSingleTenant,
		scenarios.ModeMultiTenant,
		scenarios.SetupRoleAdmin,
		scenarios.SetupRoleStaff,
		DefaultBackendURL,
		DefaultTenantDomain,
		DefaultFrontendPort,
	)
}
