package analytics

import (
	"maps"
	"net/http"
)

// RouteKey is one route of the HTTP API as chi reports it: the method and
// the route pattern, never a concrete path.
type RouteKey struct {
	Method  string
	Pattern string
}

// CoreAction classifies one writing route for the usage analytics (spec
// #3598, "Kernaktionen per Middleware"). An empty Event means the route is
// deliberately not captured.
type CoreAction struct {
	Event string
	// Session: the response mints a session (login, demo entry); the actor
	// comes from its access token, and a 2xx without one sends nothing.
	Session bool
	// Surface names the portal of a route whose request carries no session
	// (a public form). It is the fallback when no session tells it.
	Surface string
	// ExportType is the only property a data export adds; it names the
	// export by its route, never by the request body.
	ExportType string
}

var notCaptured = CoreAction{}

func event(name string) CoreAction   { return CoreAction{Event: name} }
func session(name string) CoreAction { return CoreAction{Event: name, Session: true} }
func sessionOr(name, surface string) CoreAction {
	return CoreAction{Event: name, Session: true, Surface: surface}
}
func public(name string) CoreAction { return CoreAction{Event: name, Surface: SurfacePublic} }
func export(exportType string) CoreAction {
	return CoreAction{Event: "data_exported", ExportType: exportType}
}

// coreActions classifies every writing route (POST, PUT, PATCH, DELETE) of
// the portal routers: OGS portal (/api, /auth), parents portal (/parent),
// school portal (/school), and the public demo (/demo). A route either names
// its event or is notCaptured. TestFullProductionRouterGolden fails for a
// writing route of these routers that is missing here, and for an entry
// whose route no longer exists. Not portal routers, and so not listed: the
// operator dashboard (/operator), the kiosk (/api/iot, whose check-in events
// come from the attendance service), CalDAV clients (/api/caldav,
// /.well-known/caldav), and /internal.
//
// Adding a writing route: classify it here. New core action: name the event
// in snake_case after what succeeded (group_created, not create_group).
var coreActions = map[RouteKey]CoreAction{
	// OGS portal (tenant API).
	{http.MethodPost, "/api/absence-types/"}:                                                               notCaptured,
	{http.MethodPut, "/api/absence-types/{id}"}:                                                            notCaptured,
	{http.MethodPut, "/api/absence-types/{id}/allowances/{staffId}"}:                                       notCaptured,
	{http.MethodPost, "/api/active/combined/"}:                                                             notCaptured,
	{http.MethodDelete, "/api/active/combined/{id}"}:                                                       notCaptured,
	{http.MethodPut, "/api/active/combined/{id}"}:                                                          notCaptured,
	{http.MethodPost, "/api/active/combined/{id}/end"}:                                                     notCaptured,
	{http.MethodPost, "/api/active/groups/"}:                                                               notCaptured,
	{http.MethodDelete, "/api/active/groups/{id}"}:                                                         notCaptured,
	{http.MethodPut, "/api/active/groups/{id}"}:                                                            notCaptured,
	{http.MethodPost, "/api/active/groups/{id}/claim"}:                                                     notCaptured,
	{http.MethodPost, "/api/active/groups/{id}/end"}:                                                       notCaptured,
	{http.MethodPost, "/api/active/mappings/add"}:                                                          notCaptured,
	{http.MethodPost, "/api/active/mappings/remove"}:                                                       notCaptured,
	{http.MethodPost, "/api/active/supervisors/"}:                                                          notCaptured,
	{http.MethodDelete, "/api/active/supervisors/{id}"}:                                                    notCaptured,
	{http.MethodPut, "/api/active/supervisors/{id}"}:                                                       notCaptured,
	{http.MethodPost, "/api/active/supervisors/{id}/end"}:                                                  notCaptured,
	{http.MethodPost, "/api/active/tracking-indicators"}:                                                   notCaptured,
	{http.MethodPost, "/api/active/visits/"}:                                                               notCaptured,
	{http.MethodPost, "/api/active/visits/move-to-group"}:                                                  notCaptured,
	{http.MethodPost, "/api/active/visits/move-to-room"}:                                                   notCaptured,
	{http.MethodPost, "/api/active/visits/move-to-transit"}:                                                notCaptured,
	{http.MethodPost, "/api/active/visits/student/{studentId}/checkin"}:                                    notCaptured,
	{http.MethodPost, "/api/active/visits/student/{studentId}/checkout"}:                                   notCaptured,
	{http.MethodPost, "/api/active/visits/transit/assign"}:                                                 notCaptured,
	{http.MethodDelete, "/api/active/visits/{id}"}:                                                         notCaptured,
	{http.MethodPut, "/api/active/visits/{id}"}:                                                            notCaptured,
	{http.MethodPost, "/api/active/visits/{id}/end"}:                                                       notCaptured,
	{http.MethodPost, "/api/activities/"}:                                                                  notCaptured,
	{http.MethodPost, "/api/activities/categories"}:                                                        notCaptured,
	{http.MethodDelete, "/api/activities/categories/{categoryId}"}:                                         notCaptured,
	{http.MethodPut, "/api/activities/categories/{categoryId}"}:                                            notCaptured,
	{http.MethodPost, "/api/activities/categories/{categoryId}/restore"}:                                   notCaptured,
	{http.MethodPost, "/api/activities/quick-create"}:                                                      notCaptured,
	{http.MethodDelete, "/api/activities/{id}"}:                                                            notCaptured,
	{http.MethodPut, "/api/activities/{id}"}:                                                               notCaptured,
	{http.MethodPost, "/api/activities/{id}/schedules"}:                                                    notCaptured,
	{http.MethodDelete, "/api/activities/{id}/schedules/{scheduleId}"}:                                     notCaptured,
	{http.MethodPut, "/api/activities/{id}/schedules/{scheduleId}"}:                                        notCaptured,
	{http.MethodPut, "/api/activities/{id}/students"}:                                                      notCaptured,
	{http.MethodDelete, "/api/activities/{id}/students/{studentId}"}:                                       notCaptured,
	{http.MethodPost, "/api/activities/{id}/students/{studentId}"}:                                         notCaptured,
	{http.MethodPost, "/api/activities/{id}/supervisors"}:                                                  notCaptured,
	{http.MethodDelete, "/api/activities/{id}/supervisors/{supervisorId}"}:                                 notCaptured,
	{http.MethodPut, "/api/activities/{id}/supervisors/{supervisorId}"}:                                    notCaptured,
	{http.MethodPost, "/api/admin/grade-transitions/"}:                                                     notCaptured,
	{http.MethodDelete, "/api/admin/grade-transitions/{id}/"}:                                              notCaptured,
	{http.MethodPut, "/api/admin/grade-transitions/{id}/"}:                                                 notCaptured,
	{http.MethodPost, "/api/admin/grade-transitions/{id}/apply"}:                                           notCaptured,
	{http.MethodPost, "/api/admin/grade-transitions/{id}/revert"}:                                          notCaptured,
	{http.MethodPost, "/api/announcement-attachments/{announcementId}"}:                                    notCaptured,
	{http.MethodDelete, "/api/announcement-attachments/{announcementId}/{attachmentId}"}:                   notCaptured,
	{http.MethodPut, "/api/birthdays/opt-out"}:                                                             notCaptured,
	{http.MethodPost, "/api/birthdays/staff-export"}:                                                       export("staff_birthdays"),
	{http.MethodPost, "/api/calendar/appointments"}:                                                        notCaptured,
	{http.MethodDelete, "/api/calendar/appointments/{appointmentId}"}:                                      notCaptured,
	{http.MethodPut, "/api/calendar/appointments/{appointmentId}"}:                                         notCaptured,
	{http.MethodPost, "/api/calendar/appointments/{appointmentId}/cancel"}:                                 notCaptured,
	{http.MethodPost, "/api/calendar/appointments/{appointmentId}/occurrences/{occurrenceDate}/cancel"}:    notCaptured,
	{http.MethodPost, "/api/calendar/feed/rotate"}:                                                         notCaptured,
	{http.MethodPost, "/api/calendar/recipients/{recipientId}/response"}:                                   notCaptured,
	{http.MethodPost, "/api/class-list-entries/"}:                                                          notCaptured,
	{http.MethodDelete, "/api/class-list-entries/{id}"}:                                                    notCaptured,
	{http.MethodPut, "/api/class-list-entries/{id}"}:                                                       notCaptured,
	{http.MethodPost, "/api/class-list-entries/{id}/assign"}:                                               notCaptured,
	{http.MethodPost, "/api/display/"}:                                                                     notCaptured,
	{http.MethodDelete, "/api/display/{id}/"}:                                                              notCaptured,
	{http.MethodPatch, "/api/display/{id}/"}:                                                               notCaptured,
	{http.MethodPost, "/api/display/{id}/regenerate"}:                                                      notCaptured,
	{http.MethodPost, "/api/emergency/snapshot/export"}:                                                    export("emergency"),
	{http.MethodPost, "/api/enrollment/admin/change-requests/{id}/approve"}:                                notCaptured,
	{http.MethodPost, "/api/enrollment/admin/change-requests/{id}/question"}:                               notCaptured,
	{http.MethodPost, "/api/enrollment/admin/change-requests/{id}/reject"}:                                 notCaptured,
	{http.MethodPost, "/api/enrollment/admin/reports/care-usage/export"}:                                   export("care_usage"),
	{http.MethodPost, "/api/enrollment/admin/reports/class-roster/export"}:                                 export("class_roster"),
	{http.MethodPost, "/api/enrollment/admin/request-children/{id}/rollover-review"}:                       notCaptured,
	{http.MethodDelete, "/api/enrollment/admin/requests/{id}/"}:                                            notCaptured,
	{http.MethodDelete, "/api/enrollment/admin/requests/{id}/children/{childId}"}:                          notCaptured,
	{http.MethodPut, "/api/enrollment/admin/requests/{id}/children/{childId}/data-correction"}:             notCaptured,
	{http.MethodPost, "/api/enrollment/admin/requests/{id}/children/{childId}/decide"}:                     notCaptured,
	{http.MethodPut, "/api/enrollment/admin/requests/{id}/children/{childId}/offerings"}:                   notCaptured,
	{http.MethodPost, "/api/enrollment/admin/requests/{id}/restore"}:                                       notCaptured,
	{http.MethodPost, "/api/enrollment/admin/students/{studentId}/requests/export"}:                        export("student_enrollment_requests"),
	{http.MethodPost, "/api/enrollment/care-offerings/"}:                                                   notCaptured,
	{http.MethodDelete, "/api/enrollment/care-offerings/{id}/"}:                                            notCaptured,
	{http.MethodPut, "/api/enrollment/care-offerings/{id}/"}:                                               notCaptured,
	{http.MethodPost, "/api/enrollment/care-offerings/{id}/clone"}:                                         notCaptured,
	{http.MethodPost, "/api/enrollment/legal-documents"}:                                                   notCaptured,
	{http.MethodDelete, "/api/enrollment/legal-documents/{filename}"}:                                      notCaptured,
	{http.MethodPost, "/api/enrollment/phases/"}:                                                           notCaptured,
	{http.MethodDelete, "/api/enrollment/phases/{id}/"}:                                                    notCaptured,
	{http.MethodPut, "/api/enrollment/phases/{id}/"}:                                                       notCaptured,
	{http.MethodPost, "/api/enrollment/phases/{id}/export"}:                                                export("enrollment_phase"),
	{http.MethodPost, "/api/enrollment/phases/{id}/late-invites"}:                                          notCaptured,
	{http.MethodPost, "/api/enrollment/phases/{id}/manual-approved-enrollments"}:                           notCaptured,
	{http.MethodPost, "/api/enrollment/phases/{id}/rollover"}:                                              notCaptured,
	{http.MethodPatch, "/api/enrollment/requests/{statusToken}"}:                                           notCaptured,
	{http.MethodPut, "/api/enrollment/requests/{statusToken}"}:                                             notCaptured,
	{http.MethodPost, "/api/enrollment/requests/{statusToken}/change-requests"}:                            notCaptured,
	{http.MethodPost, "/api/enrollment/requests/{statusToken}/change-requests/{changeRequestId}/messages"}: notCaptured,
	{http.MethodPost, "/api/enrollment/requests/{statusToken}/confirm-renewal"}:                            notCaptured,
	{http.MethodPost, "/api/enrollment/requests/{statusToken}/withdraw"}:                                   notCaptured,
	{http.MethodPost, "/api/enrollment/schema/"}:                                                           notCaptured,
	{http.MethodDelete, "/api/enrollment/schema/{id}"}:                                                     notCaptured,
	{http.MethodPatch, "/api/enrollment/schema/{id}"}:                                                      notCaptured,
	{http.MethodPut, "/api/enrollment/schema/{id}"}:                                                        notCaptured,
	{http.MethodPost, "/api/enrollment/{tenantSlug}/submit"}:                                               public("enrollment_submitted"),
	{http.MethodPost, "/api/feedback/"}:                                                                    notCaptured,
	{http.MethodPost, "/api/feedback/batch"}:                                                               notCaptured,
	{http.MethodDelete, "/api/feedback/{id}"}:                                                              notCaptured,
	{http.MethodPost, "/api/files/folders"}:                                                                notCaptured,
	{http.MethodDelete, "/api/files/folders/{folderId}"}:                                                   notCaptured,
	{http.MethodPut, "/api/files/folders/{folderId}"}:                                                      notCaptured,
	{http.MethodPost, "/api/files/folders/{folderId}/files"}:                                               notCaptured,
	{http.MethodDelete, "/api/files/folders/{folderId}/files/{fileId}"}:                                    notCaptured,
	{http.MethodPost, "/api/groups/"}:                                                                      event("group_created"),
	{http.MethodDelete, "/api/groups/{id}"}:                                                                notCaptured,
	{http.MethodPut, "/api/groups/{id}"}:                                                                   event("group_updated"),
	{http.MethodPost, "/api/guardians/"}:                                                                   notCaptured,
	{http.MethodPost, "/api/guardians/bulk-invite"}:                                                        notCaptured,
	{http.MethodPost, "/api/guardians/invitations/{invitationId}/approve"}:                                 notCaptured,
	{http.MethodPost, "/api/guardians/invitations/{invitationId}/reject"}:                                  notCaptured,
	{http.MethodPost, "/api/guardians/payment-overview/export"}:                                            export("payment_overview"),
	{http.MethodPut, "/api/guardians/relationships/{relationshipId}"}:                                      notCaptured,
	{http.MethodPost, "/api/guardians/students/{studentId}/guardians"}:                                     notCaptured,
	{http.MethodPost, "/api/guardians/students/{studentId}/guardians/batch"}:                               notCaptured,
	{http.MethodDelete, "/api/guardians/students/{studentId}/guardians/{guardianId}"}:                      notCaptured,
	{http.MethodPost, "/api/guardians/students/{studentId}/invite"}:                                        notCaptured,
	{http.MethodPut, "/api/guardians/students/{studentId}/payer"}:                                          notCaptured,
	{http.MethodDelete, "/api/guardians/{id}"}:                                                             notCaptured,
	{http.MethodPut, "/api/guardians/{id}"}:                                                                notCaptured,
	{http.MethodPost, "/api/guardians/{id}/invite"}:                                                        notCaptured,
	{http.MethodPut, "/api/guardians/{id}/payment"}:                                                        notCaptured,
	{http.MethodPost, "/api/guardians/{id}/payment/reveal"}:                                                notCaptured,
	{http.MethodPost, "/api/guardians/{id}/phone-numbers/"}:                                                notCaptured,
	{http.MethodDelete, "/api/guardians/{id}/phone-numbers/{phoneId}"}:                                     notCaptured,
	{http.MethodPut, "/api/guardians/{id}/phone-numbers/{phoneId}"}:                                        notCaptured,
	{http.MethodPost, "/api/guardians/{id}/phone-numbers/{phoneId}/set-primary"}:                           notCaptured,
	{http.MethodPost, "/api/import/class-list-entries/import"}:                                             notCaptured,
	{http.MethodPost, "/api/import/class-list-entries/preview"}:                                            notCaptured,
	{http.MethodPost, "/api/import/opening-balances/import"}:                                               notCaptured,
	{http.MethodPost, "/api/import/opening-balances/preview"}:                                              notCaptured,
	{http.MethodPost, "/api/import/students/import"}:                                                       notCaptured,
	{http.MethodPost, "/api/import/students/preview"}:                                                      notCaptured,
	{http.MethodPost, "/api/import/teachers/import"}:                                                       notCaptured,
	{http.MethodPost, "/api/import/teachers/preview"}:                                                      notCaptured,
	{http.MethodPut, "/api/me/profile"}:                                                                    notCaptured,
	{http.MethodDelete, "/api/me/profile/avatar"}:                                                          notCaptured,
	{http.MethodPost, "/api/me/profile/avatar"}:                                                            notCaptured,
	{http.MethodDelete, "/api/meal-plan/{date}"}:                                                           notCaptured,
	{http.MethodPut, "/api/meal-plan/{date}"}:                                                              notCaptured,
	{http.MethodPost, "/api/messages/mark-all-read"}:                                                       event("parent_messages_marked_all_read"),
	{http.MethodPost, "/api/messages/threads"}:                                                             notCaptured,
	{http.MethodPost, "/api/messages/threads/open"}:                                                        notCaptured,
	{http.MethodPost, "/api/messages/threads/{threadId}"}:                                                  notCaptured,
	{http.MethodPost, "/api/messages/threads/{threadId}/unread"}:                                           event("parent_message_marked_unread"),
	{http.MethodDelete, "/api/notifications/preferences/"}:                                                 notCaptured,
	{http.MethodPut, "/api/notifications/preferences/{type}"}:                                              notCaptured,
	{http.MethodDelete, "/api/notifications/push/subscriptions"}:                                           notCaptured,
	{http.MethodPost, "/api/notifications/push/subscriptions"}:                                             notCaptured,
	{http.MethodPost, "/api/notifications/test"}:                                                           notCaptured,
	{http.MethodPost, "/api/parent-announcements/"}:                                                        notCaptured,
	{http.MethodDelete, "/api/parent-announcements/{announcementId}"}:                                      notCaptured,
	{http.MethodPut, "/api/parent-announcements/{announcementId}"}:                                         notCaptured,
	{http.MethodPost, "/api/parent-announcements/{announcementId}/publish"}:                                notCaptured,
	{http.MethodPost, "/api/parent-announcements/{announcementId}/remind"}:                                 notCaptured,
	{http.MethodPut, "/api/parent-announcements/{announcementId}/reminder"}:                                notCaptured,
	{http.MethodPost, "/api/parent-announcements/{announcementId}/resend-failed"}:                          notCaptured,
	{http.MethodPost, "/api/parent-announcements/{announcementId}/unpublish"}:                              notCaptured,
	{http.MethodPost, "/api/platform/announcements/{id}/dismiss"}:                                          notCaptured,
	{http.MethodPost, "/api/platform/announcements/{id}/seen"}:                                             notCaptured,
	{http.MethodPost, "/api/pwa/usage"}:                                                                    notCaptured,
	{http.MethodPost, "/api/rooms/"}:                                                                       notCaptured,
	{http.MethodPost, "/api/rooms/export"}:                                                                 export("rooms"),
	{http.MethodDelete, "/api/rooms/{id}"}:                                                                 notCaptured,
	{http.MethodPut, "/api/rooms/{id}"}:                                                                    notCaptured,
	{http.MethodPost, "/api/schedules/check-conflict"}:                                                     notCaptured,
	{http.MethodPost, "/api/schedules/dateframes/"}:                                                        notCaptured,
	{http.MethodDelete, "/api/schedules/dateframes/{id}"}:                                                  notCaptured,
	{http.MethodPut, "/api/schedules/dateframes/{id}"}:                                                     notCaptured,
	{http.MethodPost, "/api/schedules/find-available-slots"}:                                               notCaptured,
	{http.MethodPost, "/api/schedules/recurrence-rules/"}:                                                  notCaptured,
	{http.MethodDelete, "/api/schedules/recurrence-rules/{id}"}:                                            notCaptured,
	{http.MethodPut, "/api/schedules/recurrence-rules/{id}"}:                                               notCaptured,
	{http.MethodPost, "/api/schedules/recurrence-rules/{id}/generate-events"}:                              notCaptured,
	{http.MethodPost, "/api/schedules/timeframes/"}:                                                        notCaptured,
	{http.MethodDelete, "/api/schedules/timeframes/{id}"}:                                                  notCaptured,
	{http.MethodPut, "/api/schedules/timeframes/{id}"}:                                                     notCaptured,
	{http.MethodDelete, "/api/settings/enrollment/legal-agb-document"}:                                     event("settings_changed"),
	{http.MethodPost, "/api/settings/enrollment/legal-agb-document"}:                                       event("settings_changed"),
	{http.MethodDelete, "/api/settings/home-layout"}:                                                       event("settings_changed"),
	{http.MethodPut, "/api/settings/home-layout"}:                                                          event("settings_changed"),
	{http.MethodPut, "/api/settings/home-layout/policies"}:                                                 event("settings_changed"),
	{http.MethodDelete, "/api/settings/login-image"}:                                                       event("settings_changed"),
	{http.MethodPost, "/api/settings/login-image"}:                                                         event("settings_changed"),
	{http.MethodDelete, "/api/settings/values/{key}"}:                                                      event("settings_changed"),
	{http.MethodPut, "/api/settings/values/{key}"}:                                                         event("settings_changed"),
	{http.MethodPost, "/api/shift-types/"}:                                                                 notCaptured,
	{http.MethodPost, "/api/shift-types/defaults"}:                                                         notCaptured,
	{http.MethodDelete, "/api/shift-types/{id}"}:                                                           notCaptured,
	{http.MethodPut, "/api/shift-types/{id}"}:                                                              notCaptured,
	{http.MethodPost, "/api/staff-messages/threads/open"}:                                                  notCaptured,
	{http.MethodPost, "/api/staff-messages/threads/{threadID}"}:                                            notCaptured,
	{http.MethodPost, "/api/staff-notices/"}:                                                               notCaptured,
	{http.MethodDelete, "/api/staff-notices/{noticeId}"}:                                                   notCaptured,
	{http.MethodPut, "/api/staff-notices/{noticeId}"}:                                                      notCaptured,
	{http.MethodPost, "/api/staff-notices/{noticeId}/acknowledge"}:                                         notCaptured,
	{http.MethodPost, "/api/staff-shifts/"}:                                                                notCaptured,
	{http.MethodPost, "/api/staff-shifts/export"}:                                                          export("staff_shifts"),
	{http.MethodPost, "/api/staff-shifts/series"}:                                                          notCaptured,
	{http.MethodDelete, "/api/staff-shifts/series/{id}"}:                                                   notCaptured,
	{http.MethodPut, "/api/staff-shifts/series/{id}/split"}:                                                notCaptured,
	{http.MethodDelete, "/api/staff-shifts/{id}"}:                                                          notCaptured,
	{http.MethodPut, "/api/staff-shifts/{id}"}:                                                             notCaptured,
	{http.MethodPut, "/api/staff-shifts/{id}/cancellation"}:                                                notCaptured,
	{http.MethodPut, "/api/staff-shifts/{id}/move"}:                                                        notCaptured,
	{http.MethodPost, "/api/staff/"}:                                                                       notCaptured,
	{http.MethodPost, "/api/staff/absences/{absenceId}/approve"}:                                           notCaptured,
	{http.MethodPost, "/api/staff/absences/{absenceId}/deny"}:                                              notCaptured,
	{http.MethodPost, "/api/staff/absences/{absenceId}/question"}:                                          notCaptured,
	{http.MethodPost, "/api/staff/time-tracking/export/sftp"}:                                              export("time_tracking_sftp"),
	{http.MethodPost, "/api/staff/time-tracking/month-close"}:                                              notCaptured,
	{http.MethodDelete, "/api/staff/{id}"}:                                                                 notCaptured,
	{http.MethodPut, "/api/staff/{id}"}:                                                                    notCaptured,
	{http.MethodPost, "/api/staff/{id}/absences"}:                                                          notCaptured,
	{http.MethodPost, "/api/staff/{id}/absences/rebook"}:                                                   notCaptured,
	{http.MethodDelete, "/api/staff/{id}/absences/{absenceId}"}:                                            notCaptured,
	{http.MethodPost, "/api/staff/{id}/documents"}:                                                         notCaptured,
	{http.MethodDelete, "/api/staff/{id}/documents/{documentId}"}:                                          notCaptured,
	{http.MethodPut, "/api/staff/{id}/payroll-number"}:                                                     notCaptured,
	{http.MethodPut, "/api/staff/{id}/schedule"}:                                                           notCaptured,
	{http.MethodPut, "/api/staff/{id}/school-classes"}:                                                     notCaptured,
	{http.MethodPut, "/api/staff/{id}/stammdaten/arbeitsvertrag"}:                                          notCaptured,
	{http.MethodPut, "/api/staff/{id}/stammdaten/bank-steuer"}:                                             notCaptured,
	{http.MethodPost, "/api/staff/{id}/stammdaten/bank-steuer/reveal"}:                                     notCaptured,
	{http.MethodPut, "/api/staff/{id}/stammdaten/kontakt"}:                                                 notCaptured,
	{http.MethodPut, "/api/staff/{id}/stammdaten/person"}:                                                  notCaptured,
	{http.MethodPut, "/api/staff/{id}/stammdaten/qualifikationen"}:                                         notCaptured,
	{http.MethodPost, "/api/staff/{id}/target-overrides"}:                                                  notCaptured,
	{http.MethodDelete, "/api/staff/{id}/target-overrides/{overrideId}"}:                                   notCaptured,
	{http.MethodPost, "/api/staff/{id}/time-tracking/adjustments"}:                                         notCaptured,
	{http.MethodDelete, "/api/staff/{id}/time-tracking/adjustments/{adjustmentId}"}:                        notCaptured,
	{http.MethodPost, "/api/staff/{id}/time-tracking/month-close/reopen"}:                                  notCaptured,
	{http.MethodPost, "/api/staff/{id}/time-tracking/opening"}:                                             notCaptured,
	{http.MethodPost, "/api/staff/{id}/time-tracking/reset"}:                                               notCaptured,
	{http.MethodPost, "/api/staff/{id}/time-tracking/sessions"}:                                            notCaptured,
	{http.MethodPut, "/api/staff/{id}/time-tracking/sessions/{sessionId}"}:                                 notCaptured,
	{http.MethodDelete, "/api/staff/{id}/vacation/opening"}:                                                notCaptured,
	{http.MethodPost, "/api/staff/{id}/vacation/opening"}:                                                  notCaptured,
	{http.MethodPut, "/api/staff/{id}/vacation/quota"}:                                                     notCaptured,
	{http.MethodPost, "/api/students/"}:                                                                    notCaptured,
	{http.MethodPost, "/api/students/arrival-schedules/bulk"}:                                              notCaptured,
	{http.MethodPost, "/api/students/arrival-schedules/status"}:                                            notCaptured,
	{http.MethodPost, "/api/students/arrival-times/bulk"}:                                                  notCaptured,
	{http.MethodPost, "/api/students/care-end"}:                                                            notCaptured,
	{http.MethodPost, "/api/students/care-end/cancel"}:                                                     notCaptured,
	{http.MethodPost, "/api/students/care-end/preview"}:                                                    notCaptured,
	{http.MethodPost, "/api/students/care-schedule-change-requests/{requestId}/decide"}:                    event("pickup_change_decided"),
	{http.MethodDelete, "/api/students/care-withdrawals/{completionId}"}:                                   notCaptured,
	{http.MethodPost, "/api/students/care-withdrawals/{completionId}/care-end"}:                            notCaptured,
	{http.MethodPost, "/api/students/care-withdrawals/{completionId}/care-end/preview"}:                    notCaptured,
	{http.MethodPost, "/api/students/change-requests/bulk-approve"}:                                        notCaptured,
	{http.MethodPost, "/api/students/change-requests/conflicts/resolve"}:                                   notCaptured,
	{http.MethodPost, "/api/students/change-requests/rss-feed/"}:                                           notCaptured,
	{http.MethodPost, "/api/students/change-requests/rss-feed/rotate"}:                                     notCaptured,
	{http.MethodPost, "/api/students/change-requests/{kind}/{requestId}/correct"}:                          notCaptured,
	{http.MethodPost, "/api/students/change-requests/{kind}/{requestId}/mark-done"}:                        notCaptured,
	{http.MethodDelete, "/api/students/class-arrival-exceptions/{schoolClass}/{date}"}:                     notCaptured,
	{http.MethodPut, "/api/students/class-arrival-exceptions/{schoolClass}/{date}"}:                        notCaptured,
	{http.MethodPost, "/api/students/excused-absence-requests/{requestId}/decide"}:                         notCaptured,
	{http.MethodPost, "/api/students/export"}:                                                              export("students"),
	{http.MethodPost, "/api/students/master-data-change-requests/{requestId}/decide"}:                      notCaptured,
	{http.MethodPost, "/api/students/offering-change-requests/{requestId}/decide"}:                         event("offering_change_decided"),
	{http.MethodPost, "/api/students/offering-change-requests/{requestId}/preview"}:                        notCaptured,
	{http.MethodPost, "/api/students/pickup-schedules/bulk"}:                                               notCaptured,
	{http.MethodPost, "/api/students/pickup-times/bulk"}:                                                   notCaptured,
	{http.MethodPost, "/api/students/school-checkin/batch"}:                                                notCaptured,
	{http.MethodPost, "/api/students/status-days/bulk"}:                                                    event("absence_reported"),
	{http.MethodDelete, "/api/students/{id}"}:                                                              notCaptured,
	{http.MethodPut, "/api/students/{id}"}:                                                                 notCaptured,
	{http.MethodPost, "/api/students/{id}/arrival-exceptions"}:                                             notCaptured,
	{http.MethodDelete, "/api/students/{id}/arrival-exceptions/{exceptionId}"}:                             notCaptured,
	{http.MethodPut, "/api/students/{id}/arrival-exceptions/{exceptionId}"}:                                notCaptured,
	{http.MethodPost, "/api/students/{id}/arrival-notes"}:                                                  notCaptured,
	{http.MethodDelete, "/api/students/{id}/arrival-notes/{noteId}"}:                                       notCaptured,
	{http.MethodPut, "/api/students/{id}/arrival-notes/{noteId}"}:                                          notCaptured,
	{http.MethodPut, "/api/students/{id}/arrival-schedules"}:                                               notCaptured,
	{http.MethodPost, "/api/students/{id}/care-end/resume"}:                                                notCaptured,
	{http.MethodPost, "/api/students/{id}/documents"}:                                                      notCaptured,
	{http.MethodDelete, "/api/students/{id}/documents/{documentId}"}:                                       notCaptured,
	{http.MethodPut, "/api/students/{id}/family-protection"}:                                               notCaptured,
	{http.MethodPost, "/api/students/{id}/partial-absences"}:                                               event("absence_reported"),
	{http.MethodDelete, "/api/students/{id}/partial-absences/{partialAbsenceId}"}:                          notCaptured,
	{http.MethodPut, "/api/students/{id}/partial-absences/{partialAbsenceId}"}:                             notCaptured,
	{http.MethodDelete, "/api/students/{id}/photo"}:                                                        notCaptured,
	{http.MethodPost, "/api/students/{id}/photo"}:                                                          notCaptured,
	{http.MethodPost, "/api/students/{id}/pickup-exceptions"}:                                              notCaptured,
	{http.MethodDelete, "/api/students/{id}/pickup-exceptions/{exceptionId}"}:                              notCaptured,
	{http.MethodPut, "/api/students/{id}/pickup-exceptions/{exceptionId}"}:                                 notCaptured,
	{http.MethodPost, "/api/students/{id}/pickup-notes"}:                                                   notCaptured,
	{http.MethodPut, "/api/students/{id}/pickup-notes"}:                                                    notCaptured,
	{http.MethodDelete, "/api/students/{id}/pickup-notes/{noteId}"}:                                        notCaptured,
	{http.MethodPut, "/api/students/{id}/pickup-notes/{noteId}"}:                                           notCaptured,
	{http.MethodPut, "/api/students/{id}/pickup-schedules"}:                                                notCaptured,
	{http.MethodPost, "/api/students/{id}/pickup-schedules/apply"}:                                         notCaptured,
	{http.MethodPost, "/api/students/{id}/pickup-schedules/preview"}:                                       notCaptured,
	{http.MethodPost, "/api/students/{id}/pickup-schedules/reset-offering"}:                                notCaptured,
	{http.MethodPut, "/api/students/{id}/privacy-consent"}:                                                 notCaptured,
	{http.MethodDelete, "/api/students/{id}/purge"}:                                                        notCaptured,
	{http.MethodDelete, "/api/students/{id}/rfid"}:                                                         notCaptured,
	{http.MethodPost, "/api/students/{id}/rfid"}:                                                           notCaptured,
	{http.MethodPost, "/api/students/{id}/school-checkin"}:                                                 notCaptured,
	{http.MethodPost, "/api/students/{id}/status-days"}:                                                    event("absence_reported"),
	{http.MethodDelete, "/api/students/{id}/status-days/{statusDayId}"}:                                    notCaptured,
	{http.MethodPost, "/api/substitutions/"}:                                                               event("substitution_assigned"),
	{http.MethodPost, "/api/substitutions/end"}:                                                            event("substitution_ended"),
	{http.MethodPost, "/api/time-tracking/absences"}:                                                       notCaptured,
	{http.MethodDelete, "/api/time-tracking/absences/{id}"}:                                                notCaptured,
	{http.MethodPut, "/api/time-tracking/absences/{id}"}:                                                   notCaptured,
	{http.MethodPost, "/api/time-tracking/absences/{id}/cancel"}:                                           notCaptured,
	{http.MethodPost, "/api/time-tracking/absences/{id}/resubmit"}:                                         notCaptured,
	{http.MethodPost, "/api/time-tracking/break/end"}:                                                      notCaptured,
	{http.MethodPost, "/api/time-tracking/break/start"}:                                                    notCaptured,
	{http.MethodPost, "/api/time-tracking/check-in"}:                                                       notCaptured,
	{http.MethodPost, "/api/time-tracking/check-out"}:                                                      notCaptured,
	{http.MethodPost, "/api/time-tracking/vacation/request"}:                                               notCaptured,
	{http.MethodPut, "/api/time-tracking/{id}"}:                                                            notCaptured,
	{http.MethodPost, "/api/timetable/betreuungsplan/export"}:                                              export("betreuungsplan"),
	{http.MethodPost, "/api/timetable/closing-days/"}:                                                      notCaptured,
	{http.MethodDelete, "/api/timetable/closing-days/{id}"}:                                                notCaptured,
	{http.MethodPut, "/api/timetable/closing-days/{id}"}:                                                   notCaptured,
	{http.MethodDelete, "/api/timetable/conflict-acks/{fingerprint}"}:                                      notCaptured,
	{http.MethodPut, "/api/timetable/conflict-acks/{fingerprint}"}:                                         notCaptured,
	{http.MethodPost, "/api/timetable/instances/"}:                                                         notCaptured,
	{http.MethodPost, "/api/timetable/instances/bulk-cancel"}:                                              notCaptured,
	{http.MethodPost, "/api/timetable/instances/re-plan-week"}:                                             notCaptured,
	{http.MethodDelete, "/api/timetable/instances/{id}"}:                                                   notCaptured,
	{http.MethodPut, "/api/timetable/instances/{id}"}:                                                      notCaptured,
	{http.MethodPost, "/api/timetable/instances/{id}/acknowledge-understaffed"}:                            notCaptured,
	{http.MethodPost, "/api/timetable/instances/{id}/cancel"}:                                              notCaptured,
	{http.MethodPost, "/api/timetable/instances/{id}/complete"}:                                            notCaptured,
	{http.MethodPost, "/api/timetable/instances/{id}/convert-to-series"}:                                   notCaptured,
	{http.MethodPost, "/api/timetable/instances/{id}/deviations"}:                                          notCaptured,
	{http.MethodPost, "/api/timetable/instances/{id}/move-staff"}:                                          notCaptured,
	{http.MethodPost, "/api/timetable/instances/{id}/reopen"}:                                              notCaptured,
	{http.MethodPost, "/api/timetable/instances/{id}/start"}:                                               notCaptured,
	{http.MethodPatch, "/api/timetable/instances/{instance_id}/students/{student_id}"}:                     notCaptured,
	{http.MethodPost, "/api/timetable/instances/{instance_id}/students/{student_id}/correction"}:           notCaptured,
	{http.MethodPost, "/api/timetable/lists/export"}:                                                       export("timetable_lists"),
	{http.MethodPost, "/api/timetable/lists/options"}:                                                      notCaptured,
	{http.MethodPost, "/api/timetable/lists/preview"}:                                                      notCaptured,
	{http.MethodPost, "/api/timetable/materialize"}:                                                        notCaptured,
	{http.MethodPost, "/api/timetable/operations/instances/{id}/complete"}:                                 notCaptured,
	{http.MethodPost, "/api/timetable/operations/instances/{id}/reopen"}:                                   notCaptured,
	{http.MethodPost, "/api/timetable/operations/instances/{id}/start"}:                                    notCaptured,
	{http.MethodPatch, "/api/timetable/operations/instances/{id}/students/{student_id}/attendance"}:        notCaptured,
	{http.MethodPost, "/api/timetable/operations/instances/{id}/students/{student_id}/check-in"}:           notCaptured,
	{http.MethodPost, "/api/timetable/operations/instances/{id}/students/{student_id}/check-out"}:          notCaptured,
	{http.MethodPost, "/api/timetable/operations/spontaneous/start"}:                                       notCaptured,
	{http.MethodPost, "/api/timetable/periods/"}:                                                           notCaptured,
	{http.MethodPost, "/api/timetable/periods/bootstrap"}:                                                  notCaptured,
	{http.MethodDelete, "/api/timetable/periods/{id}"}:                                                     notCaptured,
	{http.MethodPut, "/api/timetable/periods/{id}"}:                                                        notCaptured,
	{http.MethodPost, "/api/timetable/pickup-extensions/{id}/resolve"}:                                     notCaptured,
	{http.MethodPost, "/api/timetable/planning-tracks/"}:                                                   notCaptured,
	{http.MethodPut, "/api/timetable/planning-tracks/order"}:                                               notCaptured,
	{http.MethodDelete, "/api/timetable/planning-tracks/{id}"}:                                             notCaptured,
	{http.MethodPut, "/api/timetable/planning-tracks/{id}"}:                                                notCaptured,
	{http.MethodPost, "/api/timetable/planning-tracks/{id}/restore"}:                                       notCaptured,
	{http.MethodPost, "/api/timetable/shift-coverage"}:                                                     notCaptured,
	{http.MethodPost, "/api/timetable/substitutions/bulk"}:                                                 event("substitution_assigned"),
	{http.MethodPost, "/api/timetable/templates"}:                                                          notCaptured,
	{http.MethodDelete, "/api/timetable/templates/{id}"}:                                                   notCaptured,
	{http.MethodPut, "/api/timetable/templates/{id}"}:                                                      notCaptured,
	{http.MethodPost, "/api/timetable/templates/{id}/end"}:                                                 notCaptured,
	{http.MethodPost, "/api/timetable/templates/{id}/split"}:                                               notCaptured,
	{http.MethodPost, "/api/users/"}:                                                                       notCaptured,
	{http.MethodDelete, "/api/users/{id}"}:                                                                 notCaptured,
	{http.MethodPut, "/api/users/{id}"}:                                                                    notCaptured,
	{http.MethodPost, "/api/work-time-models/"}:                                                            notCaptured,
	{http.MethodDelete, "/api/work-time-models/{id}"}:                                                      notCaptured,
	{http.MethodPut, "/api/work-time-models/{id}"}:                                                         notCaptured,

	// OGS portal: sign-in, accounts, invitations.
	{http.MethodPut, "/auth/accounts/{accountId}/"}:                                  notCaptured,
	{http.MethodPut, "/auth/accounts/{accountId}/activate"}:                          notCaptured,
	{http.MethodDelete, "/auth/accounts/{accountId}/caregiver-capability"}:           notCaptured,
	{http.MethodPost, "/auth/accounts/{accountId}/caregiver-capability"}:             notCaptured,
	{http.MethodPut, "/auth/accounts/{accountId}/deactivate"}:                        notCaptured,
	{http.MethodDelete, "/auth/accounts/{accountId}/mfa/"}:                           notCaptured,
	{http.MethodPut, "/auth/accounts/{accountId}/mfa/override"}:                      notCaptured,
	{http.MethodDelete, "/auth/accounts/{accountId}/permissions/{permissionId}"}:     notCaptured,
	{http.MethodPost, "/auth/accounts/{accountId}/permissions/{permissionId}/deny"}:  notCaptured,
	{http.MethodPost, "/auth/accounts/{accountId}/permissions/{permissionId}/grant"}: notCaptured,
	{http.MethodPut, "/auth/accounts/{accountId}/roles/"}:                            notCaptured,
	{http.MethodDelete, "/auth/accounts/{accountId}/roles/{roleId}"}:                 notCaptured,
	{http.MethodPost, "/auth/accounts/{accountId}/roles/{roleId}"}:                   notCaptured,
	{http.MethodDelete, "/auth/accounts/{accountId}/tokens/"}:                        notCaptured,
	{http.MethodPost, "/auth/guardian-invitations/{id}/resend"}:                      notCaptured,
	{http.MethodPost, "/auth/guardian-invitations/{token}/accept"}:                   sessionOr("guardian_invite_accepted", SurfaceParents),
	{http.MethodPost, "/auth/invitations/"}:                                          event("staff_invited"),
	{http.MethodDelete, "/auth/invitations/{id}/"}:                                   notCaptured,
	{http.MethodPost, "/auth/invitations/{id}/resend"}:                               notCaptured,
	{http.MethodPost, "/auth/invitations/{token}/accept"}:                            notCaptured,
	{http.MethodPost, "/auth/link-to-tenant"}:                                        notCaptured,
	{http.MethodPost, "/auth/login"}:                                                 session("login_success"),
	{http.MethodPost, "/auth/logout"}:                                                notCaptured,
	{http.MethodPost, "/auth/mfa/enroll/confirm"}:                                    session("login_success"),
	{http.MethodPost, "/auth/mfa/enroll/start"}:                                      notCaptured,
	{http.MethodPost, "/auth/mfa/resend"}:                                            notCaptured,
	{http.MethodDelete, "/auth/mfa/trusted-devices/{deviceId}"}:                      notCaptured,
	{http.MethodPost, "/auth/mfa/verify"}:                                            session("login_success"),
	{http.MethodPost, "/auth/parent-accounts/"}:                                      notCaptured,
	{http.MethodPut, "/auth/parent-accounts/{id}/"}:                                  notCaptured,
	{http.MethodPut, "/auth/parent-accounts/{id}/activate"}:                          notCaptured,
	{http.MethodPut, "/auth/parent-accounts/{id}/deactivate"}:                        notCaptured,
	{http.MethodPost, "/auth/passkeys/enrollment/challenge"}:                         notCaptured,
	{http.MethodPost, "/auth/passkeys/login/options"}:                                notCaptured,
	{http.MethodPost, "/auth/passkeys/login/verify"}:                                 session("login_success"),
	{http.MethodPost, "/auth/passkeys/register/options"}:                             notCaptured,
	{http.MethodPost, "/auth/passkeys/register/verify"}:                              notCaptured,
	{http.MethodDelete, "/auth/passkeys/{passkeyId}"}:                                notCaptured,
	{http.MethodPost, "/auth/password"}:                                              notCaptured,
	{http.MethodPost, "/auth/password-reset"}:                                        notCaptured,
	{http.MethodPost, "/auth/password-reset/confirm"}:                                notCaptured,
	{http.MethodPost, "/auth/permissions/"}:                                          notCaptured,
	{http.MethodDelete, "/auth/permissions/{id}/"}:                                   notCaptured,
	{http.MethodPut, "/auth/permissions/{id}/"}:                                      notCaptured,
	{http.MethodPost, "/auth/refresh"}:                                               notCaptured,
	{http.MethodPost, "/auth/register"}:                                              notCaptured,
	{http.MethodPost, "/auth/roles/"}:                                                notCaptured,
	{http.MethodDelete, "/auth/roles/{id}/"}:                                         notCaptured,
	{http.MethodPut, "/auth/roles/{id}/"}:                                            notCaptured,
	{http.MethodPut, "/auth/roles/{roleId}/permissions/"}:                            notCaptured,
	{http.MethodDelete, "/auth/roles/{roleId}/permissions/{permissionId}"}:           notCaptured,
	{http.MethodPost, "/auth/roles/{roleId}/permissions/{permissionId}"}:             notCaptured,
	{http.MethodPost, "/auth/session/validate"}:                                      notCaptured,
	{http.MethodPost, "/auth/staff-preview"}:                                         notCaptured,
	{http.MethodPost, "/auth/staff-preview/end"}:                                     notCaptured,
	{http.MethodPost, "/auth/switch-tenant"}:                                         notCaptured,
	{http.MethodDelete, "/auth/tokens/expired"}:                                      notCaptured,

	// Parents portal.
	{http.MethodPost, "/parent/auth/login"}:                                                       session("login_success"),
	{http.MethodPost, "/parent/auth/password-reset"}:                                              notCaptured,
	{http.MethodPost, "/parent/auth/password-reset/confirm"}:                                      notCaptured,
	{http.MethodPost, "/parent/enrollments/{tenantSlug}/submit"}:                                  event("enrollment_submitted"),
	{http.MethodPost, "/parent/me/calendar/feed/rotate"}:                                          notCaptured,
	{http.MethodPost, "/parent/me/calendar/recipients/{recipientId}/response"}:                    notCaptured,
	{http.MethodDelete, "/parent/me/children/{studentId}/care-exception"}:                         notCaptured,
	{http.MethodPost, "/parent/me/children/{studentId}/care-exception"}:                           event("pickup_change_requested"),
	{http.MethodPost, "/parent/me/children/{studentId}/care-offerings/requests"}:                  event("offering_change_requested"),
	{http.MethodPut, "/parent/me/children/{studentId}/care-offerings/requests/{requestId}"}:       notCaptured,
	{http.MethodPost, "/parent/me/children/{studentId}/care-schedule/requests"}:                   event("pickup_change_requested"),
	{http.MethodPut, "/parent/me/children/{studentId}/care-schedule/requests/{requestId}"}:        notCaptured,
	{http.MethodDelete, "/parent/me/children/{studentId}/consents/photo"}:                         event("photo_consent_changed"),
	{http.MethodPut, "/parent/me/children/{studentId}/consents/photo"}:                            event("photo_consent_changed"),
	{http.MethodPost, "/parent/me/children/{studentId}/courses/requests"}:                         event("offering_change_requested"),
	{http.MethodPost, "/parent/me/children/{studentId}/courses/requests/{requestId}/withdraw"}:    notCaptured,
	{http.MethodPut, "/parent/me/children/{studentId}/excused-requests/{requestId}"}:              notCaptured,
	{http.MethodPost, "/parent/me/children/{studentId}/guardians"}:                                notCaptured,
	{http.MethodPut, "/parent/me/children/{studentId}/guardians/{guardianProfileId}/contact"}:     notCaptured,
	{http.MethodPut, "/parent/me/children/{studentId}/guardians/{guardianProfileId}/pickup"}:      notCaptured,
	{http.MethodPost, "/parent/me/children/{studentId}/master-data/requests"}:                     event("master_data_change_submitted"),
	{http.MethodPut, "/parent/me/children/{studentId}/master-data/requests/{requestId}"}:          notCaptured,
	{http.MethodPatch, "/parent/me/children/{studentId}/master-data/{target}/{field}"}:            event("master_data_change_submitted"),
	{http.MethodPut, "/parent/me/children/{studentId}/meal-participation"}:                        notCaptured,
	{http.MethodDelete, "/parent/me/children/{studentId}/meal-participation/{date}"}:              notCaptured,
	{http.MethodPut, "/parent/me/children/{studentId}/meal-participation/{date}"}:                 notCaptured,
	{http.MethodPut, "/parent/me/children/{studentId}/pickup-change-requests/{requestId}"}:        notCaptured,
	{http.MethodPost, "/parent/me/children/{studentId}/related-accounts"}:                         notCaptured,
	{http.MethodDelete, "/parent/me/children/{studentId}/related-accounts/{guardianProfileId}"}:   notCaptured,
	{http.MethodPut, "/parent/me/children/{studentId}/request-sharing/{requestType}/{requestId}"}: notCaptured,
	{http.MethodPost, "/parent/me/children/{studentId}/sick-note"}:                                event("absence_request_submitted"),
	{http.MethodPost, "/parent/me/messages/children/{studentId}"}:                                 event("parent_message_sent"),
	{http.MethodPost, "/parent/me/news/{announcementId}/acknowledge"}:                             notCaptured,
	{http.MethodPost, "/parent/me/news/{announcementId}/read"}:                                    notCaptured,
	{http.MethodPost, "/parent/me/news/{announcementId}/respond"}:                                 notCaptured,
	{http.MethodDelete, "/parent/me/notification-preferences/"}:                                   notCaptured,
	{http.MethodPut, "/parent/me/notification-preferences/{type}"}:                                notCaptured,
	{http.MethodPut, "/parent/me/profile"}:                                                        notCaptured,
	{http.MethodDelete, "/parent/me/push/subscriptions"}:                                          notCaptured,
	{http.MethodPost, "/parent/me/push/subscriptions"}:                                            notCaptured,
	{http.MethodPost, "/parent/me/pwa-usage"}:                                                     notCaptured,

	// School portal (Lehrkräfte).
	{http.MethodPost, "/school/auth/login"}:                                          session("login_success"),
	{http.MethodPost, "/school/auth/mfa/enroll/confirm"}:                             session("login_success"),
	{http.MethodPost, "/school/auth/mfa/enroll/start"}:                               notCaptured,
	{http.MethodPost, "/school/auth/mfa/resend"}:                                     notCaptured,
	{http.MethodPost, "/school/auth/mfa/verify"}:                                     session("login_success"),
	{http.MethodPost, "/school/auth/password-reset"}:                                 notCaptured,
	{http.MethodPost, "/school/auth/password-reset/confirm"}:                         notCaptured,
	{http.MethodPost, "/school/auth/switch-school"}:                                  notCaptured,
	{http.MethodDelete, "/school/class-day/arrival-exceptions/{schoolClass}/{date}"}: event("arrival_exception_changed"),
	{http.MethodPut, "/school/class-day/arrival-exceptions/{schoolClass}/{date}"}:    event("arrival_exception_changed"),
	{http.MethodDelete, "/school/notifications/preferences/"}:                        notCaptured,
	{http.MethodPut, "/school/notifications/preferences/{type}"}:                     notCaptured,
	{http.MethodDelete, "/school/notifications/push/subscriptions"}:                  notCaptured,
	{http.MethodPost, "/school/notifications/push/subscriptions"}:                    notCaptured,
	{http.MethodPost, "/school/notifications/test"}:                                  notCaptured,
	{http.MethodPost, "/school/staff-messages/threads/open"}:                         notCaptured,
	{http.MethodPost, "/school/staff-messages/threads/{threadID}"}:                   event("staff_message_sent"),
	{http.MethodPost, "/school/staff-notices/{noticeId}/acknowledge"}:                event("staff_notice_acknowledged"),
	{http.MethodPost, "/school/supervisions/{id}/complete"}:                          event("supervision_completed"),
	{http.MethodPost, "/school/supervisions/{id}/start"}:                             event("supervision_started"),
	{http.MethodPatch, "/school/supervisions/{id}/students/{student_id}/attendance"}: event("supervision_attendance_recorded"),
	{http.MethodPost, "/school/supervisions/{id}/students/{student_id}/check-in"}:    event("supervision_attendance_recorded"),
	{http.MethodPost, "/school/supervisions/{id}/students/{student_id}/check-out"}:   event("supervision_attendance_recorded"),

	// Public demo (#3462), mounted under APP_ENV=demo only. A redeemed
	// access enters a demo school that is ready, so the entry is the proof
	// that the school was provided. The website's form requests the link
	// without a session, so that step counts on the public surface; it is
	// the demo funnel's first step in PostHog (#3604). A restart is counted
	// by the entry page (demo_restarted).
	{http.MethodPost, "/demo/access-requests"}: public("demo_link_requested"),
	{http.MethodPost, "/demo/access/sessions"}: session("demo_started"),
	{http.MethodPost, "/demo/access/reset"}:    notCaptured,
}

// CoreActions returns a copy of the route table for the guard tests.
func CoreActions() map[RouteKey]CoreAction {
	return maps.Clone(coreActions)
}

// CoreActionPrefixes are the path prefixes of the portal routers whose
// writing routes the table must classify.
func CoreActionPrefixes() []string {
	return []string{"/api/", "/auth/", "/parent/", "/school/", "/demo/"}
}

// CoreActionExcludedPrefixes are routes under those prefixes that do not
// belong to a portal: the kiosk and CalDAV clients.
func CoreActionExcludedPrefixes() []string {
	return []string{"/api/iot/", "/api/caldav"}
}

func coreActionFor(method, pattern string) (CoreAction, bool) {
	for _, candidate := range normalizePattern(pattern) {
		if action, ok := coreActions[RouteKey{Method: method, Pattern: candidate}]; ok {
			return action, true
		}
	}
	return CoreAction{}, false
}

// coreActionMethods are the methods with at least one captured route; the
// middleware leaves every other request alone.
func coreActionMethods() map[string]bool {
	methods := map[string]bool{}
	for key, action := range coreActions {
		if action.Event != "" {
			methods[key.Method] = true
		}
	}
	return methods
}
