package ports

import (
	"context"
	"time"

	"github.com/moto-nrw/project-phoenix/modules/timetable/internal/domain"
)

type Store interface {
	CountPlannedSupervisorsByCalendarPeriod(context.Context) (map[int64]int, domain.OperationStats, error)
	LockInstanceStudentAssignments(context.Context, int64) (domain.OperationStats, error)
	RestoreInstanceStudentAttendanceRow(context.Context, int64, domain.CompletionAttendance) (domain.OperationStats, error)
	CourseInstances(context.Context, string, string, string) ([]domain.CourseInstanceRow, domain.OperationStats, error)
	CourseParticipation(context.Context, string, string, string) ([]domain.CourseParticipationRow, domain.OperationStats, error)
	LockOpenStudentAssignments(ctx context.Context, studentIDs []int64) (domain.OperationStats, error)
	LockPlannedStudentAssignmentsAfter(ctx context.Context, studentIDs []int64, after string) (domain.OperationStats, error)
	ReconnectCareExitAssignmentPickupExceptions(ctx context.Context, studentIDs, pickupExceptionIDs []int64, removals []domain.InstanceStudent) (domain.OperationStats, error)
	ListOpenStudentAssignments(ctx context.Context, studentIDs []int64) ([]int64, domain.OperationStats, error)
	LatestStudentAssignmentAttendanceDate(ctx context.Context, studentID int64) (*string, domain.OperationStats, error)
	CloseOpenStudentAssignments(ctx context.Context, studentIDs []int64, at time.Time) (int64, domain.OperationStats, error)
	CountPlannedStudentAssignmentsAfter(ctx context.Context, studentIDs []int64, after string, removals []domain.InstanceStudent) (map[int64]int, domain.OperationStats, error)
	RemovePlannedStudentAssignmentsAfter(ctx context.Context, studentIDs []int64, after string) ([]domain.InstanceStudent, domain.OperationStats, error)
	RestoreCareExitStudentAssignments(ctx context.Context, studentIDs, roomIDs, statusDayIDs, pickupExceptionIDs []int64, removals []domain.InstanceStudent) (int64, domain.OperationStats, error)
	CountStudentAssignments(context.Context, int64) (int, domain.OperationStats, error)
	DeleteStudentAssignments(context.Context, int64) (domain.OperationStats, error)
	LockPlannedRosterForCareExit(context.Context, []int64, string) (domain.OperationStats, error)
	RemovePlannedRosterForCareExit(context.Context, []int64, string) ([]domain.CareExitRosterRow, domain.OperationStats, error)
	RestoreRosterForCareExit(context.Context, []int64, []domain.CareExitRosterRow) (int64, domain.OperationStats, error)
	FindCategory(context.Context, int64, string) (domain.Category, bool, domain.OperationStats, error)
	FindCategoryByName(context.Context, string, bool, string) (domain.Category, bool, domain.OperationStats, error)
	ListCategories(context.Context) ([]domain.Category, domain.OperationStats, error)
	CountCategoryUsage(context.Context) (map[int64]int, domain.OperationStats, error)
	CreateCategory(context.Context, domain.CategoryFields) (domain.Category, domain.OperationStats, error)
	UpdateCategoryIfActive(context.Context, int64, domain.CategoryFields) (domain.Category, bool, domain.OperationStats, error)
	SetCategoryArchivedAt(context.Context, int64, *time.Time) (domain.Category, bool, domain.OperationStats, error)
	SetCategoryShiftTypeLinks(context.Context, int64, []int64) (domain.OperationStats, error)
	SetCategoryShiftTypeID(context.Context, int64, *int64) (domain.OperationStats, error)
	DeleteCategory(context.Context, int64) (domain.OperationStats, error)
	LockStudentEnrollmentsForCareExit(context.Context, []int64, string) (domain.OperationStats, error)
	EndStudentEnrollmentsForCareExit(context.Context, []int64, string) (domain.CareExitEnrollmentChanges, domain.OperationStats, error)
	RestoreStudentEnrollmentsForCareExit(context.Context, []int64, []int64, []domain.CareExitEnrollmentRemoval) (int64, domain.OperationStats, error)
	FindGroup(context.Context, int64, string) (domain.Group, bool, domain.OperationStats, error)
	FindGroupByName(context.Context, string) (domain.Group, bool, domain.OperationStats, error)
	ListGroups(context.Context, domain.GroupFilter) ([]domain.Group, domain.OperationStats, error)
	ListTemplateRows(context.Context, *int64, string) ([]domain.TemplateListRow, domain.OperationStats, error)
	ListTemplateRowsForTemplatePeriod(context.Context, int64, int64, string) ([]domain.TemplateListRow, domain.OperationStats, error)
	ListTemplateRowsForPeriod(context.Context, *int64, string) ([]domain.TemplateListRow, domain.OperationStats, error)
	ListTemplateWeekdayRoster(context.Context, *int64, *int64, string) ([]domain.TemplateWeekdayRosterRow, domain.OperationStats, error)
	ListTemplateCapacityOccurrences(context.Context, *int64, []int64, []domain.TemplateCapacityPeriod, map[int64][]int64) ([]domain.TemplateCapacityOccurrence, domain.OperationStats, error)
	CreateGroup(context.Context, domain.GroupFields) (domain.Group, domain.OperationStats, error)
	UpdateGroup(context.Context, int64, domain.GroupFields) (domain.Group, bool, domain.OperationStats, error)
	DeleteGroup(context.Context, int64) (domain.OperationStats, error)
	UpdateTemplate(context.Context, int64, domain.TemplateFields) (int64, domain.OperationStats, error)
	ArchiveTemplate(context.Context, int64) (int64, domain.OperationStats, error)
	UpdateGroupOfferingSource(context.Context, int64, domain.OfferingSourceFields) (domain.OperationStats, error)
	ListGroupTargets(context.Context, []int64) (map[int64][]domain.GroupTarget, domain.OperationStats, error)
	ReplaceGroupTargets(context.Context, int64, []domain.GroupTargetFields) (domain.OperationStats, error)
	FindSchedule(context.Context, int64) (domain.Schedule, bool, domain.OperationStats, error)
	ListSchedules(context.Context, domain.ScheduleFilter) ([]domain.Schedule, domain.OperationStats, error)
	FindTemplateStartTimes(context.Context, []int64) ([]domain.TemplateStartTime, domain.OperationStats, error)
	CreateSchedule(context.Context, domain.ScheduleFields) (domain.Schedule, domain.OperationStats, error)
	UpdateSchedule(context.Context, int64, domain.ScheduleFields) (domain.Schedule, bool, domain.OperationStats, error)
	DeleteSchedule(context.Context, int64) (domain.OperationStats, error)
	DeleteSchedulesByGroup(context.Context, int64) (domain.OperationStats, error)
	CapScheduleValidUntil(context.Context, int64, string) (int64, domain.OperationStats, error)
	FindPlannedSupervisor(context.Context, int64) (domain.PlannedSupervisor, bool, domain.OperationStats, error)
	ListPlannedSupervisors(context.Context, domain.PlannedSupervisorFilter) ([]domain.PlannedSupervisor, domain.OperationStats, error)
	ListPlannedSupervisionBlockers(context.Context, int64) ([]domain.PlannedSupervisionBlocker, domain.OperationStats, error)
	CreatePlannedSupervisor(context.Context, domain.PlannedSupervisorFields) (domain.PlannedSupervisor, domain.OperationStats, error)
	UpdatePlannedSupervisor(context.Context, int64, domain.PlannedSupervisorFields) (domain.PlannedSupervisor, bool, domain.OperationStats, error)
	DeletePlannedSupervisor(context.Context, int64) (domain.OperationStats, error)
	SetPrimaryPlannedSupervisor(context.Context, int64) (bool, domain.OperationStats, error)
	DeletePlannedSupervisorsByStaff(context.Context, int64) (int64, domain.OperationStats, error)
	CapActivePlannedSupervisors(context.Context, int64, string) (int64, domain.OperationStats, error)
	SetPlannedSupervisorValidUntil(context.Context, int64, string) (bool, domain.OperationStats, error)
	CloseOpenPlannedSupervisors(context.Context, int64, *int64, string) (domain.OperationStats, error)
	FindStudentEnrollment(context.Context, int64) (domain.StudentEnrollment, bool, domain.OperationStats, error)
	ListStudentEnrollments(context.Context, domain.StudentEnrollmentFilter) ([]domain.StudentEnrollment, domain.OperationStats, error)
	CreateStudentEnrollment(context.Context, domain.StudentEnrollmentFields) (domain.StudentEnrollment, domain.OperationStats, error)
	UpdateStudentEnrollment(context.Context, int64, domain.StudentEnrollmentFields) (domain.StudentEnrollment, bool, domain.OperationStats, error)
	DeleteStudentEnrollment(context.Context, int64) (domain.OperationStats, error)
	BackfillStudentEnrollmentSource(context.Context, int64, int64, []int64) (int64, domain.OperationStats, error)
	DeleteStudentEnrollmentsBySource(context.Context, int64, int64) (int64, domain.OperationStats, error)
	CapActiveStudentEnrollments(context.Context, int64, string) (int64, domain.OperationStats, error)
	SetStudentEnrollmentValidUntil(context.Context, int64, string) (bool, domain.OperationStats, error)
	CloseOpenStudentEnrollments(context.Context, int64, *int64, string) (domain.OperationStats, error)
	FindTimeframe(context.Context, int64) (domain.Timeframe, bool, domain.OperationStats, error)
	ListTimeframes(context.Context, domain.TimeframeFilter) ([]domain.Timeframe, domain.OperationStats, error)
	CreateTimeframe(context.Context, domain.TimeframeFields) (domain.Timeframe, domain.OperationStats, error)
	UpdateTimeframe(context.Context, int64, domain.TimeframeFields) (domain.Timeframe, bool, domain.OperationStats, error)
	DeleteTimeframe(context.Context, int64) (domain.OperationStats, error)
	FindPlanningTrack(context.Context, int64, string) (domain.PlanningTrack, bool, domain.OperationStats, error)
	ListPlanningTracks(context.Context, domain.PlanningTrackFilter) ([]domain.PlanningTrack, domain.OperationStats, error)
	CreatePlanningTrack(context.Context, domain.PlanningTrackFields) (domain.PlanningTrack, domain.OperationStats, error)
	UpdatePlanningTrack(context.Context, int64, domain.PlanningTrackFields, bool) (domain.PlanningTrack, bool, domain.OperationStats, error)
	DeletePlanningTrack(context.Context, int64) (domain.OperationStats, error)
	SetPlanningTrackArchivedAt(context.Context, int64, *time.Time) (domain.PlanningTrack, bool, domain.OperationStats, error)
	ReorderPlanningTracks(context.Context, []int64) (domain.OperationStats, error)
	RestorePlanningTrackAtEnd(context.Context, int64) (domain.PlanningTrack, bool, domain.OperationStats, error)
	FindRecurrenceRule(context.Context, int64) (domain.RecurrenceRule, bool, domain.OperationStats, error)
	ListRecurrenceRules(context.Context, domain.RecurrenceRuleFilter) ([]domain.RecurrenceRule, domain.OperationStats, error)
	CreateRecurrenceRule(context.Context, domain.RecurrenceRuleFields) (domain.RecurrenceRule, domain.OperationStats, error)
	UpdateRecurrenceRule(context.Context, int64, domain.RecurrenceRuleFields) (domain.RecurrenceRule, bool, domain.OperationStats, error)
	DeleteRecurrenceRule(context.Context, int64) (domain.OperationStats, error)
	FindActivityException(context.Context, int64) (domain.ActivityException, bool, domain.OperationStats, error)
	ListActivityExceptions(context.Context, domain.ActivityExceptionFilter) ([]domain.ActivityException, domain.OperationStats, error)
	CountActivityExceptions(context.Context, *string) (int, domain.OperationStats, error)
	OldestActivityExceptionBefore(context.Context, *string) (*string, domain.OperationStats, error)
	CreateActivityException(context.Context, domain.ActivityExceptionFields) (domain.ActivityException, domain.OperationStats, error)
	UpdateActivityException(context.Context, int64, domain.ActivityExceptionFields) (domain.ActivityException, bool, domain.OperationStats, error)
	DeleteActivityException(context.Context, int64) (domain.OperationStats, error)
	DeleteActivityExceptionsBefore(context.Context, string) (int64, domain.OperationStats, error)
	FindActivityInstance(context.Context, int64) (domain.ActivityInstance, bool, domain.OperationStats, error)
	ListActivityInstances(context.Context, domain.ActivityInstanceFilter) ([]domain.ActivityInstance, domain.OperationStats, error)
	MaxActivityInstanceID(context.Context) (int64, domain.OperationStats, error)
	CountActivityInstances(context.Context, *string) (int, domain.OperationStats, error)
	OldestActivityInstanceBefore(context.Context, *string) (*string, domain.OperationStats, error)
	CreateActivityInstance(context.Context, domain.ActivityInstanceFields) (domain.ActivityInstance, domain.OperationStats, error)
	CreateTemplateBackedActivityInstanceIfAbsent(context.Context, domain.ActivityInstanceFields) (domain.ActivityInstance, bool, domain.OperationStats, error)
	CreateIdempotentActivityInstance(context.Context, domain.ActivityInstanceFields) (domain.ActivityInstance, bool, domain.OperationStats, error)
	UpdateActivityInstance(context.Context, int64, domain.ActivityInstanceFields) (domain.ActivityInstance, bool, domain.OperationStats, error)
	PatchActivityInstance(context.Context, int64, domain.ActivityInstanceFields, []string) (int64, domain.OperationStats, error)
	DeleteActivityInstance(context.Context, int64) (domain.OperationStats, error)
	MarkActivityInstanceCompleted(context.Context, int64, time.Time) (bool, domain.OperationStats, error)
	CompleteActiveActivityInstances(context.Context, []int64, time.Time) (int64, domain.OperationStats, error)
	DeletePlannedActivityInstances(context.Context, string, *string, *int64, bool) (int64, domain.OperationStats, error)
	DeleteRemovedWeekendActivityInstances(context.Context, int64, []int, string) (int64, domain.OperationStats, error)
	PropagateActivityInstanceListKind(context.Context, int64, *string, *string, string, time.Time) (int64, domain.OperationStats, error)
	DeleteActivityInstancesBefore(context.Context, string) (int64, domain.OperationStats, error)
	FindInstanceStaff(context.Context, int64) (domain.InstanceStaff, bool, domain.OperationStats, error)
	ListInstanceStaff(context.Context, domain.InstanceStaffFilter) ([]domain.InstanceStaff, domain.OperationStats, error)
	CountNonAbsentInstanceStaff(context.Context, []int64) (map[int64]int, domain.OperationStats, error)
	CreateInstanceStaff(context.Context, domain.InstanceStaffFields) (domain.InstanceStaff, domain.OperationStats, error)
	UpdateInstanceStaff(context.Context, int64, domain.InstanceStaffFields) (domain.InstanceStaff, bool, domain.OperationStats, error)
	PatchInstanceStaff(context.Context, int64, domain.InstanceStaffFields, []string) (int64, domain.OperationStats, error)
	DeleteInstanceStaff(context.Context, int64) (domain.OperationStats, error)
	DeleteInstanceStaffByInstance(context.Context, int64) (domain.OperationStats, error)
	DeleteUpcomingInstanceStaff(context.Context, int64, string) (int64, domain.OperationStats, error)
	FindInstanceStudent(context.Context, int64) (domain.InstanceStudent, bool, domain.OperationStats, error)
	ListInstanceStudents(context.Context, domain.InstanceStudentFilter) ([]domain.InstanceStudent, domain.OperationStats, error)
	CountNonAbsentInstanceStudents(context.Context, []int64) (map[int64]int, domain.OperationStats, error)
	ListParallelStudentPresence(context.Context, int64, string, []int64) ([]domain.ParallelPresence, domain.OperationStats, error)
	ListStudentInstanceRefsBefore(context.Context, string) ([]domain.StudentInstanceRef, domain.OperationStats, error)
	ListScheduledInstancesForStudent(context.Context, int64, string, string) ([]domain.ScheduledInstanceRow, domain.OperationStats, error)
	HasPlannedStudentSlots(context.Context, string, string) (bool, domain.OperationStats, error)
	ListPlannedStudentIDs(context.Context, []int64, string) ([]int64, domain.OperationStats, error)
	ListPartialAbsenceBlocks(context.Context, int64, string, time.Time, bool, []int64) ([]domain.PartialAbsenceBlock, domain.OperationStats, error)
	CreateInstanceStudent(context.Context, domain.InstanceStudentFields) (domain.InstanceStudent, domain.OperationStats, error)
	UpdateInstanceStudent(context.Context, int64, domain.InstanceStudentFields) (domain.InstanceStudent, bool, domain.OperationStats, error)
	DeleteInstanceStudent(context.Context, int64) (domain.OperationStats, error)
	DeleteInstanceStudentsByInstance(context.Context, int64) (domain.OperationStats, error)
	UpdateAttendanceFromCheckin(context.Context, int64, int64, time.Time) (bool, domain.OperationStats, error)
	UpdateAttendanceFromCheckinBatch(context.Context, []domain.InstanceStudentKey, time.Time) (domain.OperationStats, error)
	UpdateAttendanceCheckout(context.Context, int64, int64, time.Time) (domain.OperationStats, error)
	UpdateAttendanceCheckoutBatch(context.Context, []domain.InstanceStudentKey, time.Time) (domain.OperationStats, error)
	CreateUnplannedPresentIfAbsent(context.Context, int64, int64, time.Time) (domain.InstanceStudent, domain.OperationStats, error)
	ReconcileAttendanceInterval(context.Context, int64, int64, time.Time, *time.Time, time.Time, *time.Time) (bool, domain.OperationStats, error)
	UpdateAttendanceFields(context.Context, int64, domain.AttendanceFieldPatch) (domain.OperationStats, error)
	BulkUpdateStatus(context.Context, int64, string, string, []int64) (int64, domain.OperationStats, error)
	MarkNotScheduled(context.Context, []domain.StudentInstanceRef) (domain.OperationStats, error)
	MarkExpectedAbsentByActiveGroupIDs(context.Context, []int64, time.Time, []domain.StudentInstanceRef) (domain.OperationStats, error)
	CloseOpenCheckoutsByActiveGroupIDs(context.Context, []int64, time.Time) (int64, domain.OperationStats, error)
	ApplyStatusDay(context.Context, int64, string, int64, string, time.Time) (int64, domain.OperationStats, error)
	ReleaseStatusDay(context.Context, int64, int64, *domain.StudentStatusDay, time.Time) (int64, domain.OperationStats, error)
	ApplyActiveStatusDaysForInstance(context.Context, int64, []domain.StudentStatusDay, time.Time) (int64, domain.OperationStats, error)
	ApplyPartialAbsence(context.Context, domain.PickupException, bool, time.Time) (int64, domain.OperationStats, error)
	ReleasePartialAbsence(context.Context, int64, int64, *domain.StudentStatusDay, time.Time) (int64, domain.OperationStats, error)
	ApplyActivePartialAbsencesForInstance(context.Context, int64, string, []domain.PickupException, time.Time) (int64, domain.OperationStats, error)
	ArchivePlannedInstanceStudents(context.Context, int64, []int64, string, string, string) (int64, domain.OperationStats, error)
	ListRosterRemovalCareDays(context.Context, int64, []int64, string) ([]domain.CareDay, domain.OperationStats, error)
	ConsumeRosterRemovals(context.Context, int64, []int64) ([]domain.RosterRemoval, domain.OperationStats, error)
	InsertRestoredInstanceStudents(context.Context, []domain.InstanceStudentFields) (int64, domain.OperationStats, error)
}

type Transaction interface {
	RunWrite(context.Context, bool, func(context.Context) error) error
}

type StudentDirectory interface {
	ListEnrolledStudents(context.Context) ([]domain.TargetStudent, domain.OperationStats, error)
}

type CarePlanDirectory interface {
	FindPickupException(context.Context, int64) (*domain.PickupException, error)
	ListPickupExceptions(context.Context, domain.PickupExceptionFilter) ([]domain.PickupException, error)
	FindStudentStatusDay(context.Context, int64, bool) (*domain.StudentStatusDay, error)
	ListStudentStatusDays(context.Context, domain.StudentStatusDayFilter) ([]domain.StudentStatusDay, error)
}

type CareDayLocker interface {
	LockStudentAndExceptionDay(context.Context, int64, string) error
	LockExceptionDay(context.Context, int64, string) error
}

type RoomDirectory interface {
	LockRoomsByID(context.Context, []int64) ([]domain.RoomRef, domain.OperationStats, error)
}

type Observation struct {
	Operation string
	Duration  time.Duration
	Stats     domain.OperationStats
	Err       error
}

type Observer func(Observation)
