#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# Richtet den Drive-Upload der Produkt-Screenshots ein (#3759, #3763):
# OAuth-Client in Google Cloud, Refresh-Token, Zielordner in Drive und die
# Secrets der GitHub-Environment `product-screenshots`, die
# .github/workflows/product-screenshots.yml im Upload-Job liest.
#
#   scripts/product-screenshots-drive-wizard.sh
#
# Die Werte landen zusätzlich in ~/.config/moto/product-screenshots-drive.env
# (nur für dich lesbar), damit ein erneuter Lauf sie anbietet. Erneut ausführen,
# wenn der Upload mit invalid_grant abbricht (Token widerrufen oder abgelaufen).

TOTAL_STAGES=7

ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"
umask 077
ENV_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/moto/product-screenshots-drive.env"
mkdir -p "$(dirname "$ENV_FILE")"

GH_ENVIRONMENT=product-screenshots
FOLDER_NAME="moto Produkt-Screenshots"
SCOPE="https://www.googleapis.com/auth/drive.file"

# set_env_secret NAME VALUE setzt ein Secret der GitHub-Environment.
set_env_secret() {
  local name="$1" value="$2"
  if printf '%s' "$value" | gh secret set "$name" --env "$GH_ENVIRONMENT" --repo "$REPO" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$GH_ENVIRONMENT/$name")
    printf '  %s✓ set%s Secret %s in Environment %s\n' "$GREEN" "$RESET" "$name" "$GH_ENVIRONMENT"
  else
    SKIPPED+=("Secret $name: gh secret set $name --env $GH_ENVIRONMENT")
    warn "Secret $name konnte nicht gesetzt werden"
  fi
}

# drive_folder prüft DRIVE_FOLDER_ID oder legt den Zielordner an und gibt die
# ID aus. Mit dem Scope drive.file sieht die App nur Ordner, die sie selbst
# angelegt hat; deshalb entsteht der Ordner hier per API.
drive_folder() {
  DRIVE_CLIENT_ID="$DRIVE_CLIENT_ID" DRIVE_CLIENT_SECRET="$DRIVE_CLIENT_SECRET" \
    DRIVE_REFRESH_TOKEN="$DRIVE_REFRESH_TOKEN" FOLDER_ID="${1:-}" FOLDER_NAME="$FOLDER_NAME" \
    node --input-type=module - <<'JS'
const env = process.env;
const tokenResponse = await fetch("https://oauth2.googleapis.com/token", {
  method: "POST",
  body: new URLSearchParams({
    client_id: env.DRIVE_CLIENT_ID,
    client_secret: env.DRIVE_CLIENT_SECRET,
    refresh_token: env.DRIVE_REFRESH_TOKEN,
    grant_type: "refresh_token",
  }),
});
const token = await tokenResponse.json();
if (!token.access_token) {
  console.error(`Anmeldung fehlgeschlagen: ${token.error} ${token.error_description ?? ""}`);
  process.exit(1);
}
const headers = { Authorization: `Bearer ${token.access_token}` };
const api = "https://www.googleapis.com/drive/v3/files";
let response;
if (env.FOLDER_ID) {
  response = await fetch(
    `${api}/${encodeURIComponent(env.FOLDER_ID)}?fields=id,name,trashed&supportsAllDrives=true`,
    { headers },
  );
} else {
  response = await fetch(`${api}?fields=id,name&supportsAllDrives=true`, {
    method: "POST",
    headers: { ...headers, "Content-Type": "application/json" },
    body: JSON.stringify({
      name: env.FOLDER_NAME,
      mimeType: "application/vnd.google-apps.folder",
    }),
  });
}
const folder = await response.json();
if (!response.ok || folder.trashed) {
  console.error(`Ordner nicht erreichbar (${response.status}): ${JSON.stringify(folder.error ?? folder)}`);
  process.exit(1);
}
console.error(`Ordner „${folder.name}“`);
console.log(folder.id);
JS
}

banner "Drive-Upload der Produkt-Screenshots"

# ── 1 ──────────────────────────────────────────────────────────────────────
stage "Voraussetzungen"
say "Der Wizard braucht node und ein angemeldetes gh mit Admin-Rechten am Repo."
command -v node >/dev/null || { warn "node fehlt: devbox shell starten"; exit 1; }
command -v gh >/dev/null || { warn "gh fehlt: devbox shell starten"; exit 1; }
gh auth status >/dev/null 2>&1 || { warn "gh ist nicht angemeldet: gh auth login"; exit 1; }
REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
say "Repository: $REPO"
step "Melde dich im Browser mit dem Google-Konto an, dem der Drive-Ordner gehören soll"
step "(am besten ein Team-Konto, nicht ein persönliches)."
note "Werte merkt sich der Wizard in $ENV_FILE."
pause "Weiter mit Enter"

# ── 2 ──────────────────────────────────────────────────────────────────────
stage "Google Cloud: Projekt und Drive API"
say "Die App braucht ein Google-Cloud-Projekt mit eingeschalteter Drive API."
open_url "https://console.cloud.google.com/projectcreate"
step "Projekt anlegen, etwa „moto Produkt-Screenshots“, oder oben ein vorhandenes wählen."
open_url "https://console.cloud.google.com/apis/library/drive.googleapis.com"
step "Prüfen, dass oben das richtige Projekt gewählt ist, dann „Aktivieren“ klicken."
pause "Drive API aktiviert? Enter"

# ── 3 ──────────────────────────────────────────────────────────────────────
stage "Google Cloud: Zustimmungsbildschirm"
open_url "https://console.cloud.google.com/auth/overview"
step "„Get started“ bzw. „Jetzt starten“: App-Name „moto Produkt-Screenshots“, Support-E-Mail."
step "Zielgruppe: „Intern“, wenn das Konto zu Google Workspace gehört."
step "Sonst „Extern“ und danach unter „Zielgruppe“ auf „Veröffentlichen“ (In Produktion)."
warn "Im Status „Testing“ verfällt das Refresh-Token nach 7 Tagen, der Upload bricht dann ab."
step "Unter „Datenzugriff“ den Scope $SCOPE hinzufügen."
note "drive.file erlaubt nur Dateien, die diese App selbst anlegt; keine Prüfung durch Google nötig."
pause "Zustimmungsbildschirm eingerichtet? Enter"

# ── 4 ──────────────────────────────────────────────────────────────────────
stage "Google Cloud: OAuth-Client"
open_url "https://console.cloud.google.com/auth/clients"
step "„Client erstellen“, Anwendungstyp „Desktop-App“, Name „moto Produkt-Screenshots CI“."
step "Client-ID und Clientschlüssel aus dem Dialog kopieren."
ask DRIVE_CLIENT_ID "Client-ID:"
ask_secret DRIVE_CLIENT_SECRET "Clientschlüssel (Eingabe unsichtbar):"
[[ -n "$DRIVE_CLIENT_ID" && -n "$DRIVE_CLIENT_SECRET" ]] || { warn "Client-ID und Schlüssel sind Pflicht"; exit 1; }
write_env DRIVE_CLIENT_ID "$DRIVE_CLIENT_ID"
write_env DRIVE_CLIENT_SECRET "$DRIVE_CLIENT_SECRET"

# ── 5 ──────────────────────────────────────────────────────────────────────
stage "Refresh-Token"
DRIVE_REFRESH_TOKEN=$(_existing DRIVE_REFRESH_TOKEN || true)
if [[ -n "$DRIVE_REFRESH_TOKEN" ]] && ! confirm "Es gibt schon ein Token. Neu anmelden?"; then
  say "Behalte das vorhandene Token."
else
  say "Gleich öffnet sich die Google-Anmeldung. Mit dem Konto aus Stufe 1 anmelden und zustimmen."
  say "Der Wizard nimmt die Antwort auf 127.0.0.1 entgegen."
  oauth_dir=$(mktemp -d)
  DRIVE_CLIENT_ID="$DRIVE_CLIENT_ID" DRIVE_CLIENT_SECRET="$DRIVE_CLIENT_SECRET" SCOPE="$SCOPE" \
    URL_FILE="$oauth_dir/url" TOKEN_FILE="$oauth_dir/token" \
    node --input-type=module - <<'JS' &
import { createHash, randomBytes } from "node:crypto";
import { writeFileSync } from "node:fs";
import { createServer } from "node:http";

const env = process.env;
const verifier = randomBytes(32).toString("base64url");
const challenge = createHash("sha256").update(verifier).digest("base64url");
const state = randomBytes(16).toString("hex");
let redirectUri = "";
const timer = setTimeout(() => {
  console.error("Keine Anmeldung innerhalb von 10 Minuten.");
  process.exit(1);
}, 600_000);

const server = createServer(async (req, res) => {
  const url = new URL(req.url ?? "/", redirectUri);
  if (url.pathname !== "/" || url.searchParams.get("state") !== state) {
    res.writeHead(404).end();
    return;
  }
  const code = url.searchParams.get("code");
  if (!code) {
    res.end(`Abgebrochen: ${url.searchParams.get("error")}`);
    console.error(`Anmeldung abgebrochen: ${url.searchParams.get("error")}`);
    process.exit(1);
  }
  const response = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    body: new URLSearchParams({
      code,
      client_id: env.DRIVE_CLIENT_ID,
      client_secret: env.DRIVE_CLIENT_SECRET,
      redirect_uri: redirectUri,
      grant_type: "authorization_code",
      code_verifier: verifier,
    }),
  });
  const body = await response.json();
  if (!body.refresh_token) {
    res.end("Kein Refresh-Token erhalten. Siehe Terminal.");
    console.error(`Kein Refresh-Token: ${body.error ?? ""} ${body.error_description ?? ""}`);
    process.exit(1);
  }
  writeFileSync(env.TOKEN_FILE, body.refresh_token, { mode: 0o600 });
  res.end("Fertig. Zurück zum Terminal.");
  clearTimeout(timer);
  server.close();
});

server.listen(0, "127.0.0.1", () => {
  redirectUri = `http://127.0.0.1:${server.address().port}`;
  const auth = new URL("https://accounts.google.com/o/oauth2/v2/auth");
  auth.search = new URLSearchParams({
    client_id: env.DRIVE_CLIENT_ID,
    redirect_uri: redirectUri,
    response_type: "code",
    scope: env.SCOPE,
    access_type: "offline",
    prompt: "consent",
    state,
    code_challenge: challenge,
    code_challenge_method: "S256",
  }).toString();
  writeFileSync(env.URL_FILE, auth.toString());
});
JS
  oauth_pid=$!
  for _ in $(seq 1 50); do [[ -s "$oauth_dir/url" ]] && break; sleep 0.2; done
  [[ -s "$oauth_dir/url" ]] || { warn "Anmeldeserver startet nicht"; exit 1; }
  open_url "$(cat "$oauth_dir/url")"
  wait "$oauth_pid" || { rm -rf "$oauth_dir"; warn "Anmeldung fehlgeschlagen"; exit 1; }
  DRIVE_REFRESH_TOKEN=$(cat "$oauth_dir/token")
  rm -rf "$oauth_dir"
  write_env DRIVE_REFRESH_TOKEN "$DRIVE_REFRESH_TOKEN"
fi
pause "Weiter mit Enter"

# ── 6 ──────────────────────────────────────────────────────────────────────
stage "Drive: Zielordner"
DRIVE_FOLDER_ID=$(_existing DRIVE_FOLDER_ID || true)
if [[ -n "$DRIVE_FOLDER_ID" ]] && drive_folder "$DRIVE_FOLDER_ID" >/dev/null; then
  say "Vorhandener Zielordner $DRIVE_FOLDER_ID ist erreichbar."
else
  say "Der Wizard legt den Ordner „$FOLDER_NAME“ in „Meine Ablage“ an."
  note "Ein von Hand angelegter Ordner geht nicht: drive.file sieht nur Ordner dieser App."
  confirm "Ordner jetzt anlegen?" || { warn "Ohne Zielordner kein Upload"; exit 1; }
  DRIVE_FOLDER_ID=$(drive_folder) || { warn "Ordner konnte nicht angelegt werden"; exit 1; }
  write_env DRIVE_FOLDER_ID "$DRIVE_FOLDER_ID"
fi
open_url "https://drive.google.com/drive/folders/$DRIVE_FOLDER_ID"
step "Den Ordner bei Bedarf verschieben und für das Team freigeben; die ID bleibt gleich."
note "Darin entstehen „Aktuell“ und je Release „v<version> (<datum>)“."
pause "Weiter mit Enter"

# ── 7 ──────────────────────────────────────────────────────────────────────
stage "GitHub: Environment und Secrets"
say "Die Secrets liegen in der Environment „$GH_ENVIRONMENT“ von $REPO."
say "Sie gilt nur für den Branch main und Tags v*: ein Lauf von einem anderen Branch lädt nichts hoch."
if confirm "Environment und vier Secrets jetzt setzen?"; then
  gh api --method PUT "repos/$REPO/environments/$GH_ENVIRONMENT" --input - >/dev/null <<'JSON'
{"deployment_branch_policy": {"protected_branches": false, "custom_branch_policies": true}}
JSON
  existing=$(gh api "repos/$REPO/environments/$GH_ENVIRONMENT/deployment-branch-policies" \
    --jq '.branch_policies[] | .type + ":" + .name')
  for policy in branch:main tag:v*; do
    if ! grep -qxF "$policy" <<<"$existing"; then
      gh api --method POST "repos/$REPO/environments/$GH_ENVIRONMENT/deployment-branch-policies" \
        -f "type=${policy%%:*}" -f "name=${policy#*:}" >/dev/null
    fi
  done
  printf '  %s✓ set%s Environment %s (main, v*)\n' "$GREEN" "$RESET" "$GH_ENVIRONMENT"
  set_env_secret DRIVE_CLIENT_ID "$DRIVE_CLIENT_ID"
  set_env_secret DRIVE_CLIENT_SECRET "$DRIVE_CLIENT_SECRET"
  set_env_secret DRIVE_REFRESH_TOKEN "$DRIVE_REFRESH_TOKEN"
  set_env_secret DRIVE_FOLDER_ID "$DRIVE_FOLDER_ID"
else
  SKIPPED+=("Environment $GH_ENVIRONMENT mit den Secrets DRIVE_CLIENT_ID, DRIVE_CLIENT_SECRET, DRIVE_REFRESH_TOKEN, DRIVE_FOLDER_ID")
fi
say ""
say "Probelauf, sobald product-screenshots.yml auf main liegt:"
step "gh workflow run product-screenshots.yml --ref main -f version=<version>"
note "Ohne Version gilt das neueste Release. Ergebnis: Ordner „v<version> (<datum>)“ und „Aktuell“."
pause "Weiter mit Enter"

finish
