// Code generated by scripts/generate-error-codes.mjs; DO NOT EDIT.
package common

const (
	CodeAttendanceWebDisabled                            = "attendance.web_disabled"
	CodeCareAnnouncementAckNotRequired                   = "care.announcement_ack_not_required"
	CodeCareAnnouncementNotAPoll                         = "care.announcement_not_a_poll"
	CodeCareAnnouncementStale                            = "care.announcement_stale"
	CodeCareCannotRemoveOwnAccess                        = "care.cannot_remove_own_access"
	CodeCareCareExceptionAlreadyLeft                     = "care.care_exception_already_left"
	CodeCareCareExceptionConflict                        = "care.care_exception_conflict"
	CodeCareCareExceptionNoTime                          = "care.care_exception_no_time"
	CodeCareCareExceptionPastDate                        = "care.care_exception_past_date"
	CodeCareCareExceptionReasonRequired                  = "care.care_exception_reason_required"
	CodeCareCareExceptionReasonTooLong                   = "care.care_exception_reason_too_long"
	CodeCareCareExceptionTooFar                          = "care.care_exception_too_far"
	CodeCareCareRequestAlreadyPending                    = "care.care_request_already_pending"
	CodeCareCareRequestBookingsAuthoritative             = "care.care_request_bookings_authoritative"
	CodeCareCareRequestFieldDisabled                     = "care.care_request_field_disabled"
	CodeCareChildCareEnded                               = "care.child_care_ended"
	CodeCareChildNotLinked                               = "care.child_not_linked"
	CodeCareCourseAlreadyBooked                          = "care.course_already_booked"
	CodeCareCourseRequestInvalid                         = "care.course_request_invalid"
	CodeCareCourseRequestNotOwn                          = "care.course_request_not_own"
	CodeCareCourseRequestsDisabled                       = "care.course_requests_disabled"
	CodeCareDeclarationActionNotAllowed                  = "care.declaration_action_not_allowed"
	CodeCareDeclarationClosed                            = "care.declaration_closed"
	CodeCareDeclarationNotPermitted                      = "care.declaration_not_permitted"
	CodeCareDeclarationPasswordIncorrect                 = "care.declaration_password_incorrect"
	CodeCareDeclarationPasswordRequired                  = "care.declaration_password_required"
	CodeCareDeclarationVersionChanged                    = "care.declaration_version_changed"
	CodeCareExcusedRequestNotPending                     = "care.excused_request_not_pending"
	CodeCareExcusedRequestOverlap                        = "care.excused_request_overlap"
	CodeCareFamilyProtection                             = "care.family_protection"
	CodeCareGuardianContactInvalid                       = "care.guardian_contact_invalid"
	CodeCareGuardianEmailConflict                        = "care.guardian_email_conflict"
	CodeCareGuardianHasOwnAccount                        = "care.guardian_has_own_account"
	CodeCareGuardianManagementDisabled                   = "care.guardian_management_disabled"
	CodeCareGuardianNoChange                             = "care.guardian_no_change"
	CodeCareGuardianNotLinked                            = "care.guardian_not_linked"
	CodeCareGuardianPermissionDenied                     = "care.guardian_permission_denied"
	CodeCareGuardianRelationshipInvalid                  = "care.guardian_relationship_invalid"
	CodeCareGuardianRoleManaged                          = "care.guardian_role_managed"
	CodeCareGuardianSharedAcrossFamilies                 = "care.guardian_shared_across_families"
	CodeCareGuardianSocialWorkerManaged                  = "care.guardian_social_worker_managed"
	CodeCareInvalidCredentials                           = "care.invalid_credentials"
	CodeCareInvalidPollResponse                          = "care.invalid_poll_response"
	CodeCareInvalidRecipients                            = "care.invalid_recipients"
	CodeCareInvalidRequestPayload                        = "care.invalid_request_payload"
	CodeCareInviteDisabled                               = "care.invite_disabled"
	CodeCareMasterDataDuplicatePending                   = "care.master_data_duplicate_pending"
	CodeCareMasterDataEditDisabled                       = "care.master_data_edit_disabled"
	CodeCareMasterDataFieldNotEditable                   = "care.master_data_field_not_editable"
	CodeCareMasterDataInvalidValue                       = "care.master_data_invalid_value"
	CodeCareMasterDataNoChanges                          = "care.master_data_no_changes"
	CodeCareMasterDataRequestDisabled                    = "care.master_data_request_disabled"
	CodeCareNotAGuardian                                 = "care.not_a_guardian"
	CodeCareNotesDisabled                                = "care.notes_disabled"
	CodeCareOfferingChangeAlreadyPending                 = "care.offering_change_already_pending"
	CodeCareOfferingChangeForbidden                      = "care.offering_change_forbidden"
	CodeCareOfferingChangeInvalid                        = "care.offering_change_invalid"
	CodeCareOfferingChangesDisabled                      = "care.offering_changes_disabled"
	CodeCarePayerGuardianProtected                       = "care.payer_guardian_protected"
	CodeCarePhotoConsentNotWithdrawn                     = "care.photo_consent_not_withdrawn"
	CodeCarePickupChangeCutoffPassed                     = "care.pickup_change_cutoff_passed"
	CodeCarePickupChangeDisabled                         = "care.pickup_change_disabled"
	CodeCarePollClosed                                   = "care.poll_closed"
	CodeCarePrimaryGuardianProtected                     = "care.primary_guardian_protected"
	CodeCareRemoveDisabled                               = "care.remove_disabled"
	CodeCareRequestNotFound                              = "care.request_not_found"
	CodeCareRequestNotOpen                               = "care.request_not_open"
	CodeCareRequestSharingInvalid                        = "care.request_sharing_invalid"
	CodeCareSickNoteDisabled                             = "care.sick_note_disabled"
	CodeCareStaffManagedGuardianProtected                = "care.staff_managed_guardian_protected"
	CodeClassdayArrivalExceptionClassNotFound            = "classday.arrival_exception_class_not_found"
	CodeClassdayArrivalExceptionEditorRequired           = "classday.arrival_exception_editor_required"
	CodeClassdayArrivalExceptionPastDate                 = "classday.arrival_exception_past_date"
	CodeClassdayArrivalExceptionWeekend                  = "classday.arrival_exception_weekend"
	CodeClassdaySchoolWriteDisabled                      = "classday.school_write_disabled"
	CodeCommunicationAnnouncementNotPublished            = "communication.announcement_not_published"
	CodeCommunicationAnnouncementPublishedImmutable      = "communication.announcement_published_immutable"
	CodeCommunicationAnnouncementReminderSent            = "communication.announcement_reminder_sent"
	CodeCommunicationDeclarationHasSubmissions           = "communication.declaration_has_submissions"
	CodeCommunicationParentNewsDisabled                  = "communication.parent_news_disabled"
	CodeCommunicationPollNotOpen                         = "communication.poll_not_open"
	CodeCommunicationStaffCounterpartUnavailable         = "communication.staff_counterpart_unavailable"
	CodeCommunicationStaffMessagingDisabled              = "communication.staff_messaging_disabled"
	CodeCommunicationSystemAnnouncementImmutable         = "communication.system_announcement_immutable"
	CodeEnrollmentApprovalCareOfferingExactlyOne         = "enrollment.approval_care_offering_exactly_one"
	CodeEnrollmentApprovalCareOfferingMissing            = "enrollment.approval_care_offering_missing"
	CodeEnrollmentApprovalDataInvalid                    = "enrollment.approval_data_invalid"
	CodeEnrollmentCaptchaFailed                          = "enrollment.captcha_failed"
	CodeEnrollmentCaptchaRequired                        = "enrollment.captcha_required"
	CodeEnrollmentCareOfferingAutoAddInvalid             = "enrollment.care_offering_auto_add_invalid"
	CodeEnrollmentCareOfferingCapacityInvalid            = "enrollment.care_offering_capacity_invalid"
	CodeEnrollmentCareOfferingClosed                     = "enrollment.care_offering_closed"
	CodeEnrollmentCareOfferingDaysRequired               = "enrollment.care_offering_days_required"
	CodeEnrollmentCareOfferingExactlyOne                 = "enrollment.care_offering_exactly_one"
	CodeEnrollmentCareOfferingFull                       = "enrollment.care_offering_full"
	CodeEnrollmentCareOfferingInUse                      = "enrollment.care_offering_in_use"
	CodeEnrollmentCareOfferingMissing                    = "enrollment.care_offering_missing"
	CodeEnrollmentCareOfferingNameRequired               = "enrollment.care_offering_name_required"
	CodeEnrollmentCareOfferingNotFound                   = "enrollment.care_offering_not_found"
	CodeEnrollmentCareOfferingPickupTimeInvalid          = "enrollment.care_offering_pickup_time_invalid"
	CodeEnrollmentCareOfferingPickupTimesRequired        = "enrollment.care_offering_pickup_times_required"
	CodeEnrollmentCareOfferingPriceInvalid               = "enrollment.care_offering_price_invalid"
	CodeEnrollmentCareOfferingSelectionInvalid           = "enrollment.care_offering_selection_invalid"
	CodeEnrollmentCareOfferingTemplatePeriodMismatch     = "enrollment.care_offering_template_period_mismatch"
	CodeEnrollmentCareOfferingUnavailable                = "enrollment.care_offering_unavailable"
	CodeEnrollmentCareOfferingsDisabled                  = "enrollment.care_offerings_disabled"
	CodeEnrollmentChangeRequestChildLocked               = "enrollment.change_request_child_locked"
	CodeEnrollmentChangeRequestConflict                  = "enrollment.change_request_conflict"
	CodeEnrollmentChangeRequestGuardianLinked            = "enrollment.change_request_guardian_linked"
	CodeEnrollmentChangeRequestNotAllowed                = "enrollment.change_request_not_allowed"
	CodeEnrollmentChangeRequestNotFound                  = "enrollment.change_request_not_found"
	CodeEnrollmentChangeRequestNoteRequired              = "enrollment.change_request_note_required"
	CodeEnrollmentChangeRequestStatusChanged             = "enrollment.change_request_status_changed"
	CodeEnrollmentChildAlreadyEnrolled                   = "enrollment.child_already_enrolled"
	CodeEnrollmentChildAlreadyRequested                  = "enrollment.child_already_requested"
	CodeEnrollmentChildAmbiguous                         = "enrollment.child_ambiguous"
	CodeEnrollmentChildBirthDateInvalid                  = "enrollment.child_birth_date_invalid"
	CodeEnrollmentChildDeletionNotAllowed                = "enrollment.child_deletion_not_allowed"
	CodeEnrollmentChildGradeRequired                     = "enrollment.child_grade_required"
	CodeEnrollmentChildNameRequired                      = "enrollment.child_name_required"
	CodeEnrollmentChildNotEnrolled                       = "enrollment.child_not_enrolled"
	CodeEnrollmentChildNotPermitted                      = "enrollment.child_not_permitted"
	CodeEnrollmentChildRequired                          = "enrollment.child_required"
	CodeEnrollmentClassNotEligible                       = "enrollment.class_not_eligible"
	CodeEnrollmentCompanionNoteRequired                  = "enrollment.companion_note_required"
	CodeEnrollmentCompleteWithdrawalConfirmationRequired = "enrollment.complete_withdrawal_confirmation_required"
	CodeEnrollmentConsentRequired                        = "enrollment.consent_required"
	CodeEnrollmentCorrectionReasonRequired               = "enrollment.correction_reason_required"
	CodeEnrollmentCorrectionSchoolClassMismatch          = "enrollment.correction_school_class_mismatch"
	CodeEnrollmentDaySelectionNotAllowed                 = "enrollment.day_selection_not_allowed"
	CodeEnrollmentDaySelectionRequired                   = "enrollment.day_selection_required"
	CodeEnrollmentDecisionAlreadyFinal                   = "enrollment.decision_already_final"
	CodeEnrollmentDeletionReasonInvalid                  = "enrollment.deletion_reason_invalid"
	CodeEnrollmentDepartureModeLimit                     = "enrollment.departure_mode_limit"
	CodeEnrollmentDisabled                               = "enrollment.disabled"
	CodeEnrollmentDuplicateDetected                      = "enrollment.duplicate_detected"
	CodeEnrollmentEditNotAllowed                         = "enrollment.edit_not_allowed"
	CodeEnrollmentExportTooLarge                         = "enrollment.export_too_large"
	CodeEnrollmentFieldRequired                          = "enrollment.field_required"
	CodeEnrollmentFormFieldAllowedTimesInvalid           = "enrollment.form_field_allowed_times_invalid"
	CodeEnrollmentFormFieldContentRequired               = "enrollment.form_field_content_required"
	CodeEnrollmentFormFieldKeyDuplicate                  = "enrollment.form_field_key_duplicate"
	CodeEnrollmentFormFieldKeyInvalid                    = "enrollment.form_field_key_invalid"
	CodeEnrollmentFormFieldLabelRequired                 = "enrollment.form_field_label_required"
	CodeEnrollmentFormFieldOptionsInvalid                = "enrollment.form_field_options_invalid"
	CodeEnrollmentFormFieldTargetDuplicate               = "enrollment.form_field_target_duplicate"
	CodeEnrollmentFormFieldTargetInvalid                 = "enrollment.form_field_target_invalid"
	CodeEnrollmentFormFieldVisibilityInvalid             = "enrollment.form_field_visibility_invalid"
	CodeEnrollmentFormGradeCollectionRequired            = "enrollment.form_grade_collection_required"
	CodeEnrollmentFormNotFound                           = "enrollment.form_not_found"
	CodeEnrollmentGradeNotEligible                       = "enrollment.grade_not_eligible"
	CodeEnrollmentGuardianAccountMismatch                = "enrollment.guardian_account_mismatch"
	CodeEnrollmentGuardianEmailRequired                  = "enrollment.guardian_email_required"
	CodeEnrollmentGuardianNameRequired                   = "enrollment.guardian_name_required"
	CodeEnrollmentGuardianPhoneRequired                  = "enrollment.guardian_phone_required"
	CodeEnrollmentInvalidEmail                           = "enrollment.invalid_email"
	CodeEnrollmentInvalidPhone                           = "enrollment.invalid_phone"
	CodeEnrollmentLateInviteInvalid                      = "enrollment.late_invite_invalid"
	CodeEnrollmentLegalBlockIncomplete                   = "enrollment.legal_block_incomplete"
	CodeEnrollmentLegalBlockKeyDuplicate                 = "enrollment.legal_block_key_duplicate"
	CodeEnrollmentLegalBlockKeyInvalid                   = "enrollment.legal_block_key_invalid"
	CodeEnrollmentLegalBlockRequiredNotAllowed           = "enrollment.legal_block_required_not_allowed"
	CodeEnrollmentLegalDocumentInvalid                   = "enrollment.legal_document_invalid"
	CodeEnrollmentMessageRequired                        = "enrollment.message_required"
	CodeEnrollmentOfferingAdjustmentInvalid              = "enrollment.offering_adjustment_invalid"
	CodeEnrollmentPhaseCareOfferingConflict              = "enrollment.phase_care_offering_conflict"
	CodeEnrollmentPhaseEligibilitySettingRequired        = "enrollment.phase_eligibility_setting_required"
	CodeEnrollmentPhaseNameExists                        = "enrollment.phase_name_exists"
	CodeEnrollmentPhaseNameRequired                      = "enrollment.phase_name_required"
	CodeEnrollmentPhaseNotEligible                       = "enrollment.phase_not_eligible"
	CodeEnrollmentPhaseNotFound                          = "enrollment.phase_not_found"
	CodeEnrollmentPhaseSchoolClassesInvalid              = "enrollment.phase_school_classes_invalid"
	CodeEnrollmentPhaseServicePeriodInvalid              = "enrollment.phase_service_period_invalid"
	CodeEnrollmentPhaseWindowInvalid                     = "enrollment.phase_window_invalid"
	CodeEnrollmentPickupTimeNotAllowed                   = "enrollment.pickup_time_not_allowed"
	CodeEnrollmentRequestDuplicate                       = "enrollment.request_duplicate"
	CodeEnrollmentRequestNotFound                        = "enrollment.request_not_found"
	CodeEnrollmentRequiredCareOfferingMissing            = "enrollment.required_care_offering_missing"
	CodeEnrollmentRestoreDuplicate                       = "enrollment.restore_duplicate"
	CodeEnrollmentRestoreNothingWithdrawn                = "enrollment.restore_nothing_withdrawn"
	CodeEnrollmentRestoreOfferingClosed                  = "enrollment.restore_offering_closed"
	CodeEnrollmentRestorePhaseInactive                   = "enrollment.restore_phase_inactive"
	CodeEnrollmentSchemaHasPhases                        = "enrollment.schema_has_phases"
	CodeEnrollmentSchemaHasRequests                      = "enrollment.schema_has_requests"
	CodeEnrollmentSchemaNameExists                       = "enrollment.schema_name_exists"
	CodeEnrollmentSchemaNameRequired                     = "enrollment.schema_name_required"
	CodeEnrollmentSchemaNotFound                         = "enrollment.schema_not_found"
	CodeEnrollmentSelectedDayNotAvailable                = "enrollment.selected_day_not_available"
	CodeEnrollmentStatusLinkInvalid                      = "enrollment.status_link_invalid"
	CodeEnrollmentStudentExists                          = "enrollment.student_exists"
	CodeEnrollmentSubmissionRateLimited                  = "enrollment.submission_rate_limited"
	CodeEnrollmentWaitlistDisabled                       = "enrollment.waitlist_disabled"
	CodeEnrollmentWindowClosed                           = "enrollment.window_closed"
	CodeEnrollmentWithdrawNotAllowed                     = "enrollment.withdraw_not_allowed"
	CodeFilesAnnouncementPublished                       = "files.announcement_published"
	CodeFilesAttachmentLimitReached                      = "files.attachment_limit_reached"
	CodeFilesFolderNameTaken                             = "files.folder_name_taken"
	CodeFilesQuotaExceeded                               = "files.quota_exceeded"
	CodeGeneralBusinessRejection                         = "general.business_rejection"
	CodeGeneralInput                                     = "general.input"
	CodeGeneralPermission                                = "general.permission"
	CodeGeneralServer                                    = "general.server"
	CodeGeneralUnavailable                               = "general.unavailable"
	CodeGradeTransitionGraduatesCheckedIn                = "grade_transition.graduates_checked_in"
	CodeGradeTransitionNotApplied                        = "grade_transition.not_applied"
	CodeGradeTransitionNotDraft                          = "grade_transition.not_draft"
	CodeGradeTransitionNotLatestTransition               = "grade_transition.not_latest_transition"
	CodeGradeTransitionPreviewStale                      = "grade_transition.preview_stale"
	CodeIdentityAccountAlreadyHasTenantAccess            = "identity.account_already_has_tenant_access"
	CodeIdentityAccountInactive                          = "identity.account_inactive"
	CodeIdentityDemoAccessExpired                        = "identity.demo_access_expired"
	CodeIdentityDemoAccessInvalid                        = "identity.demo_access_invalid"
	CodeIdentityDemoAccessRateLimited                    = "identity.demo_access_rate_limited"
	CodeIdentityDemoAccessUnknown                        = "identity.demo_access_unknown"
	CodeIdentityDemoCapacityReached                      = "identity.demo_capacity_reached"
	CodeIdentityDemoSchoolPreparing                      = "identity.demo_school_preparing"
	CodeIdentityDemoSession                              = "identity.demo_session"
	CodeIdentityEmailAlreadyExists                       = "identity.email_already_exists"
	CodeIdentityInvitationAccountLoginRequired           = "identity.invitation_account_login_required"
	CodeIdentityInvitationAccountMismatch                = "identity.invitation_account_mismatch"
	CodeIdentityPreviewTargetNotPreviewable              = "identity.preview_target_not_previewable"
	CodeIdentityPreviewTargetSchoolPortal                = "identity.preview_target_school_portal"
	CodeIdentityPreviewTokenInvalid                      = "identity.preview_token_invalid"
	CodeIdentityReadOnlyPreview                          = "identity.read_only_preview"
	CodeIdentitySessionAccountInactive                   = "identity.session_account_inactive"
	CodeIdentityUseParentPortal                          = "identity.use_parent_portal"
	CodeIdentityUseSchoolPortal                          = "identity.use_school_portal"
	CodeImportImportBatchFailed                          = "import.import_batch_failed"
	CodeIotActivityCapacityExceeded                      = "iot.activity_capacity_exceeded"
	CodeIotDeviationReasonRequired                       = "iot.deviation_reason_required"
	CodeIotInvalidRfidTag                                = "iot.invalid_rfid_tag"
	CodeIotInvalidStaffClockRequest                      = "iot.invalid_staff_clock_request"
	CodeIotInvalidStaffClockState                        = "iot.invalid_staff_clock_state"
	CodeIotOpenRoomBinaryMode                            = "iot.open_room_binary_mode"
	CodeIotPlannedStartNotReached                        = "iot.planned_start_not_reached"
	CodeIotRfidTagInactive                               = "iot.rfid_tag_inactive"
	CodeIotRfidTagNotFound                               = "iot.rfid_tag_not_found"
	CodeIotRfidTagNotStaff                               = "iot.rfid_tag_not_staff"
	CodeIotRoomCapacityExceeded                          = "iot.room_capacity_exceeded"
	CodeIotRoomNotFound                                  = "iot.room_not_found"
	CodeIotStudentAlreadyActive                          = "iot.student_already_active"
	CodeIotStudentNotPresent                             = "iot.student_not_present"
	CodeMealsInvalidDishes                               = "meals.invalid_dishes"
	CodeMealsInvalidMealDate                             = "meals.invalid_meal_date"
	CodeMealsInvalidParticipation                        = "meals.invalid_participation"
	CodeMealsParticipationCutoffPassed                   = "meals.participation_cutoff_passed"
	CodeMealsParticipationOutOfRange                     = "meals.participation_out_of_range"
	CodeMealsPlanDisabled                                = "meals.plan_disabled"
	CodeMealsPlanWeekOutOfRange                          = "meals.plan_week_out_of_range"
	CodeMealsRegistrationDisabled                        = "meals.registration_disabled"
	CodePickupBulkExceptionConfirmationRequired          = "pickup.bulk_exception_confirmation_required"
	CodePickupFutureManualReset                          = "pickup.future_manual_reset"
	CodePickupInvalid                                    = "pickup.invalid"
	CodePickupOfferingCapacityFull                       = "pickup.offering_capacity_full"
	CodePickupOfferingsDisabled                          = "pickup.offerings_disabled"
	CodePickupPreviewStale                               = "pickup.preview_stale"
	CodePickupResolutionRequired                         = "pickup.resolution_required"
	CodePresenceActivityParticipantLimitReached          = "presence.activity_participant_limit_reached"
	CodePresenceRoomCapacityExceeded                     = "presence.room_capacity_exceeded"
	CodeRolloverDeadlineRequired                         = "rollover.deadline_required"
	CodeRolloverDuplicateName                            = "rollover.duplicate_name"
	CodeRolloverInvalidRequest                           = "rollover.invalid_request"
	CodeRolloverReviewInvalid                            = "rollover.review_invalid"
	CodeRolloverReviewNotFound                           = "rollover.review_not_found"
	CodeRolloverSourceAlreadyRolled                      = "rollover.source_already_rolled"
	CodeRolloverSourceNotFound                           = "rollover.source_not_found"
	CodeRoomsColorAlreadyInUse                           = "rooms.color_already_in_use"
	CodeRoomsNotReleased                                 = "rooms.not_released"
	CodeSchoolNoSchoolPortalRole                         = "school.no_school_portal_role"
	CodeSchoolSetupCompleted                             = "school.setup_completed"
	CodeSchoolSetupIncomplete                            = "school.setup_incomplete"
	CodeStudentsAbsenceReadRequired                      = "students.absence_read_required"
	CodeStudentsBulkApprovalIneligible                   = "students.bulk_approval_ineligible"
	CodeStudentsCareDayManagedByBooking                  = "students.care_day_managed_by_booking"
	CodeStudentsCareExceptionRaced                       = "students.care_exception_raced"
	CodeStudentsCareExitAlreadyEffective                 = "students.care_exit_already_effective"
	CodeStudentsCareExitBlocked                          = "students.care_exit_blocked"
	CodeStudentsCareExitDayInPast                        = "students.care_exit_day_in_past"
	CodeStudentsCareExitInvalidReason                    = "students.care_exit_invalid_reason"
	CodeStudentsCareExitNoStudents                       = "students.care_exit_no_students"
	CodeStudentsCareExitNotPlanned                       = "students.care_exit_not_planned"
	CodeStudentsCareExitNoteNotAllowed                   = "students.care_exit_note_not_allowed"
	CodeStudentsCareExitNoteRequired                     = "students.care_exit_note_required"
	CodeStudentsCareExitNoteTooLong                      = "students.care_exit_note_too_long"
	CodeStudentsCareExitPreviewChanged                   = "students.care_exit_preview_changed"
	CodeStudentsCareExitTooManyStudents                  = "students.care_exit_too_many_students"
	CodeStudentsCareOfferingsDisabled                    = "students.care_offerings_disabled"
	CodeStudentsCareResumeMissing                        = "students.care_resume_missing"
	CodeStudentsCareResumeNotChecked                     = "students.care_resume_not_checked"
	CodeStudentsCareResumeNotEnded                       = "students.care_resume_not_ended"
	CodeStudentsCareResumeStartInPast                    = "students.care_resume_start_in_past"
	CodeStudentsCareWithdrawalAfterGap                   = "students.care_withdrawal_after_gap"
	CodeStudentsCareWithdrawalAlreadyResolved            = "students.care_withdrawal_already_resolved"
	CodeStudentsCareWithdrawalDateInvalid                = "students.care_withdrawal_date_invalid"
	CodeStudentsCareWithdrawalNotFound                   = "students.care_withdrawal_not_found"
	CodeStudentsChangeRequestNotPending                  = "students.change_request_not_pending"
	CodeStudentsChangeRequestStale                       = "students.change_request_stale"
	CodeStudentsCheckinCareEnded                         = "students.checkin_care_ended"
	CodeStudentsCheckoutNoteTooLong                      = "students.checkout_note_too_long"
	CodeStudentsChildQuotaReached                        = "students.child_quota_reached"
	CodeStudentsCompanionLockBusy                        = "students.companion_lock_busy"
	CodeStudentsCompanionWouldLoseDeparture              = "students.companion_would_lose_departure"
	CodeStudentsCompanionsChanged                        = "students.companions_changed"
	CodeStudentsConflictKindUnsupported                  = "students.conflict_kind_unsupported"
	CodeStudentsCorrectionUnsupported                    = "students.correction_unsupported"
	CodeStudentsDeletionAcknowledgementRequired          = "students.deletion_acknowledgement_required"
	CodeStudentsDeletionAlumnus                          = "students.deletion_alumnus"
	CodeStudentsDeletionCompanionBlocked                 = "students.deletion_companion_blocked"
	CodeStudentsDeletionCompanionLockBusy                = "students.deletion_companion_lock_busy"
	CodeStudentsDeletionConfirmationMismatch             = "students.deletion_confirmation_mismatch"
	CodeStudentsDeletionConstraintsChanged               = "students.deletion_constraints_changed"
	CodeStudentsDeletionInvalidReason                    = "students.deletion_invalid_reason"
	CodeStudentsDeletionPreviewChanged                   = "students.deletion_preview_changed"
	CodeStudentsDeletionRetentionNotEnded                = "students.deletion_retention_not_ended"
	CodeStudentsExcusedRequestStatusConflict             = "students.excused_request_status_conflict"
	CodeStudentsExportSelectionTooLarge                  = "students.export_selection_too_large"
	CodeStudentsGuardianAccessRevoked                    = "students.guardian_access_revoked"
	CodeStudentsGuardianAccountHolderTooLong             = "students.guardian_account_holder_too_long"
	CodeStudentsGuardianEmailTaken                       = "students.guardian_email_taken"
	CodeStudentsGuardianIbanInvalid                      = "students.guardian_iban_invalid"
	CodeStudentsOfferingChangeCapacityFull               = "students.offering_change_capacity_full"
	CodeStudentsOfferingChangeDateOutOfRange             = "students.offering_change_date_out_of_range"
	CodeStudentsOfferingChangesNoEnrollment              = "students.offering_changes_no_enrollment"
	CodeStudentsPartialAbsenceConflict                   = "students.partial_absence_conflict"
	CodeStudentsPartialAbsenceRequiresDedicatedAction    = "students.partial_absence_requires_dedicated_action"
	CodeStudentsPhotoConsentRequired                     = "students.photo_consent_required"
	CodeStudentsPhotoConsentWithdrawn                    = "students.photo_consent_withdrawn"
	CodeStudentsPhotosDisabled                           = "students.photos_disabled"
	CodeStudentsPickupChangeCompleted                    = "students.pickup_change_completed"
	CodeStudentsPickupChangeConflict                     = "students.pickup_change_conflict"
	CodeStudentsPickupChangeExpired                      = "students.pickup_change_expired"
	CodeStudentsPickupChangeImpactChanged                = "students.pickup_change_impact_changed"
	CodeStudentsPickupResetRequiresOffering              = "students.pickup_reset_requires_offering"
	CodeStudentsReasonRequired                           = "students.reason_required"
	CodeStudentsRequestNotDecided                        = "students.request_not_decided"
	CodeStudentsRequestNotPast                           = "students.request_not_past"
	CodeStudentsRequestPast                              = "students.request_past"
	CodeStudentsSickExcusedConflict                      = "students.sick_excused_conflict"
	CodeStudentsStaffProfileRequired                     = "students.staff_profile_required"
	CodeStudentsStaffValueInvalid                        = "students.staff_value_invalid"
	CodeStudentsStaffValueUnsupported                    = "students.staff_value_unsupported"
	CodeStudentsStatusDayConflict                        = "students.status_day_conflict"
	CodeSubstitutionsAlreadyAssigned                     = "substitutions.already_assigned"
	CodeSubstitutionsConflict                            = "substitutions.conflict"
	CodeSubstitutionsForbidden                           = "substitutions.forbidden"
	CodeSubstitutionsInternal                            = "substitutions.internal"
	CodeSubstitutionsInvalidPeriod                       = "substitutions.invalid_period"
	CodeSubstitutionsInvalidTarget                       = "substitutions.invalid_target"
	CodeSubstitutionsNotFound                            = "substitutions.not_found"
	CodeSubstitutionsNotRunning                          = "substitutions.not_running"
	CodeSubstitutionsSelfAssignment                      = "substitutions.self_assignment"
	CodeTimetableAmbiguousTemplateInstanceDelete         = "timetable.ambiguous_template_instance_delete"
	CodeTimetableAttendanceEntryNotFound                 = "timetable.attendance_entry_not_found"
	CodeTimetableAttendanceFrozen                        = "timetable.attendance_frozen"
	CodeTimetableAttendanceInvalid                       = "timetable.attendance_invalid"
	CodeTimetableCalendarPeriodCareOfferingConflict      = "timetable.calendar_period_care_offering_conflict"
	CodeTimetableCalendarPeriodEndBeforeStart            = "timetable.calendar_period_end_before_start"
	CodeTimetableCalendarPeriodInvalid                   = "timetable.calendar_period_invalid"
	CodeTimetableCalendarPeriodNameTaken                 = "timetable.calendar_period_name_taken"
	CodeTimetableCalendarPeriodNotFound                  = "timetable.calendar_period_not_found"
	CodeTimetableCalendarPeriodOverlapConflict           = "timetable.calendar_period_overlap_conflict"
	CodeTimetableCalendarPeriodRosterConflict            = "timetable.calendar_period_roster_conflict"
	CodeTimetableCalendarPeriodWeekCycleAnchorMissing    = "timetable.calendar_period_week_cycle_anchor_missing"
	CodeTimetableClosingDayEndBeforeStart                = "timetable.closing_day_end_before_start"
	CodeTimetableClosingDayInvalid                       = "timetable.closing_day_invalid"
	CodeTimetableClosingDayNotFound                      = "timetable.closing_day_not_found"
	CodeTimetableCompleteTooEarly                        = "timetable.complete_too_early"
	CodeTimetableCompletionConfirmationStale             = "timetable.completion_confirmation_stale"
	CodeTimetableCorrectionCancelled                     = "timetable.correction_cancelled"
	CodeTimetableCorrectionNotCompleted                  = "timetable.correction_not_completed"
	CodeTimetableCorrectionReasonMissing                 = "timetable.correction_reason_missing"
	CodeTimetableCorrectionReasonTooLong                 = "timetable.correction_reason_too_long"
	CodeTimetableDateInPast                              = "timetable.date_in_past"
	CodeTimetableDatesInPast                             = "timetable.dates_in_past"
	CodeTimetableDatesRequired                           = "timetable.dates_required"
	CodeTimetableDeviationNoteTooLong                    = "timetable.deviation_note_too_long"
	CodeTimetableDeviationSelectionInvalid               = "timetable.deviation_selection_invalid"
	CodeTimetableDuplicateInstance                       = "timetable.duplicate_instance"
	CodeTimetableExportEndBeforeStart                    = "timetable.export_end_before_start"
	CodeTimetableExportInternalForbidden                 = "timetable.export_internal_forbidden"
	CodeTimetableExportRangeTooLarge                     = "timetable.export_range_too_large"
	CodeTimetableGroupAlreadyEnded                       = "timetable.group_already_ended"
	CodeTimetableGuardianNoticeDisabled                  = "timetable.guardian_notice_disabled"
	CodeTimetableGuardianNoticeInvalid                   = "timetable.guardian_notice_invalid"
	CodeTimetableGuardianNoticePast                      = "timetable.guardian_notice_past"
	CodeTimetableGuardianNoticeTextInvalid               = "timetable.guardian_notice_text_invalid"
	CodeTimetableIdempotencyKeyReused                    = "timetable.idempotency_key_reused"
	CodeTimetableInstanceEndBeforeStart                  = "timetable.instance_end_before_start"
	CodeTimetableInstanceInPast                          = "timetable.instance_in_past"
	CodeTimetableInstanceInvalid                         = "timetable.instance_invalid"
	CodeTimetableInstanceMoved                           = "timetable.instance_moved"
	CodeTimetableInstanceNotActive                       = "timetable.instance_not_active"
	CodeTimetableInstanceNotConvertible                  = "timetable.instance_not_convertible"
	CodeTimetableInstanceNotEditable                     = "timetable.instance_not_editable"
	CodeTimetableInstanceNotFound                        = "timetable.instance_not_found"
	CodeTimetableInstanceOutsidePeriod                   = "timetable.instance_outside_period"
	CodeTimetableInstanceSelectionInvalid                = "timetable.instance_selection_invalid"
	CodeTimetableInstanceWeekend                         = "timetable.instance_weekend"
	CodeTimetableInstancesNotAssigned                    = "timetable.instances_not_assigned"
	CodeTimetableInstancesOtherDay                       = "timetable.instances_other_day"
	CodeTimetableInstancesRequired                       = "timetable.instances_required"
	CodeTimetableInvalidTransition                       = "timetable.invalid_transition"
	CodeTimetableMoveOtherDay                            = "timetable.move_other_day"
	CodeTimetableMoveSameInstance                        = "timetable.move_same_instance"
	CodeTimetableNoStaffProfile                          = "timetable.no_staff_profile"
	CodeTimetableOfferingSourceInactive                  = "timetable.offering_source_inactive"
	CodeTimetableOfferingSourceInvalid                   = "timetable.offering_source_invalid"
	CodeTimetableOfferingSourceMixedPhases               = "timetable.offering_source_mixed_phases"
	CodeTimetableOfferingSourceNotFound                  = "timetable.offering_source_not_found"
	CodeTimetableOfferingSourceOutsidePeriod             = "timetable.offering_source_outside_period"
	CodeTimetableOfferingSourceTooMany                   = "timetable.offering_source_too_many"
	CodeTimetableOnlySupervisorReplacementRequired       = "timetable.only_supervisor_replacement_required"
	CodeTimetableOperationStale                          = "timetable.operation_stale"
	CodeTimetablePickupExtensionBlockGone                = "timetable.pickup_extension_block_gone"
	CodeTimetablePickupExtensionInvalid                  = "timetable.pickup_extension_invalid"
	CodeTimetablePickupExtensionNotFound                 = "timetable.pickup_extension_not_found"
	CodeTimetablePickupExtensionTooManyBlocks            = "timetable.pickup_extension_too_many_blocks"
	CodeTimetablePlanningTrackArchived                   = "timetable.planning_track_archived"
	CodeTimetablePlanningTrackInvalid                    = "timetable.planning_track_invalid"
	CodeTimetablePlanningTrackNameTaken                  = "timetable.planning_track_name_taken"
	CodeTimetablePlanningTrackNotFound                   = "timetable.planning_track_not_found"
	CodeTimetablePresenceWouldOverstaff                  = "timetable.presence_would_overstaff"
	CodeTimetableReopenAttendanceChanged                 = "timetable.reopen_attendance_changed"
	CodeTimetableReopenStaffBusy                         = "timetable.reopen_staff_busy"
	CodeTimetableReopenStudentActive                     = "timetable.reopen_student_active"
	CodeTimetableReopenSupervisionChanged                = "timetable.reopen_supervision_changed"
	CodeTimetableRoomOccupied                            = "timetable.room_occupied"
	CodeTimetableSeriesEndBeforeStart                    = "timetable.series_end_before_start"
	CodeTimetableSeriesEndOutsidePeriod                  = "timetable.series_end_outside_period"
	CodeTimetableSickAbsenceScopeLocked                  = "timetable.sick_absence_scope_locked"
	CodeTimetableSlotListDrifted                         = "timetable.slot_list_drifted"
	CodeTimetableSlotListGroupingInvalid                 = "timetable.slot_list_grouping_invalid"
	CodeTimetableSlotListPickupPastDate                  = "timetable.slot_list_pickup_past_date"
	CodeTimetableSlotListReconciliationFutureDate        = "timetable.slot_list_reconciliation_future_date"
	CodeTimetableSlotListsDisabled                       = "timetable.slot_lists_disabled"
	CodeTimetableSpontaneousActivitiesDisabled           = "timetable.spontaneous_activities_disabled"
	CodeTimetableSpontaneousCategoryArchived             = "timetable.spontaneous_category_archived"
	CodeTimetableStaffAbsentOnDate                       = "timetable.staff_absent_on_date"
	CodeTimetableStaffAbsentOnSource                     = "timetable.staff_absent_on_source"
	CodeTimetableStaffAbsentOnTarget                     = "timetable.staff_absent_on_target"
	CodeTimetableStaffAlreadyOnTarget                    = "timetable.staff_already_on_target"
	CodeTimetableStaffNotFound                           = "timetable.staff_not_found"
	CodeTimetableStaffNotOnSource                        = "timetable.staff_not_on_source"
	CodeTimetableStaffPresentAndAbsent                   = "timetable.staff_present_and_absent"
	CodeTimetableStartTooEarly                           = "timetable.start_too_early"
	CodeTimetableStartWindowExpired                      = "timetable.start_window_expired"
	CodeTimetableStudentAlreadyActive                    = "timetable.student_already_active"
	CodeTimetableStudentCareEnded                        = "timetable.student_care_ended"
	CodeTimetableStudentGraduated                        = "timetable.student_graduated"
	CodeTimetableStudentNotCheckedIn                     = "timetable.student_not_checked_in"
	CodeTimetableStudentNotFound                         = "timetable.student_not_found"
	CodeTimetableStudentsNotPresent                      = "timetable.students_not_present"
	CodeTimetableSubstituteAbsent                        = "timetable.substitute_absent"
	CodeTimetableSubstituteAbsentOnDate                  = "timetable.substitute_absent_on_date"
	CodeTimetableSubstituteConflict                      = "timetable.substitute_conflict"
	CodeTimetableSubstituteNotOnInstances                = "timetable.substitute_not_on_instances"
	CodeTimetableSubstituteSelf                          = "timetable.substitute_self"
	CodeTimetableSubstituteSingleOnly                    = "timetable.substitute_single_only"
	CodeTimetableTemplateCareOfferingConflict            = "timetable.template_care_offering_conflict"
	CodeTimetableTemplateCategoryUnavailable             = "timetable.template_category_unavailable"
	CodeTimetableTemplateEducationGroupInvalid           = "timetable.template_education_group_invalid"
	CodeTimetableTemplateEndBeforeStart                  = "timetable.template_end_before_start"
	CodeTimetableTemplateGradeAboveMax                   = "timetable.template_grade_above_max"
	CodeTimetableTemplateInvalid                         = "timetable.template_invalid"
	CodeTimetableTemplateMaxParticipantsInvalid          = "timetable.template_max_participants_invalid"
	CodeTimetableTemplateNotFound                        = "timetable.template_not_found"
	CodeTimetableTemplatePlanningTrackUnavailable        = "timetable.template_planning_track_unavailable"
	CodeTimetableTemplateRosterRebaseConflict            = "timetable.template_roster_rebase_conflict"
	CodeTimetableTemplateSplitInPast                     = "timetable.template_split_in_past"
	CodeTimetableTemplateSplitInvalid                    = "timetable.template_split_invalid"
	CodeTimetableTemplateStartInPast                     = "timetable.template_start_in_past"
	CodeTimetableTemplateStartNotEarlier                 = "timetable.template_start_not_earlier"
	CodeTimetableTemplateStartOutsidePeriod              = "timetable.template_start_outside_period"
	CodeTimetableTemplateStartPredecessorOverlap         = "timetable.template_start_predecessor_overlap"
	CodeTimetableTemplateWeekPatternInvalid              = "timetable.template_week_pattern_invalid"
	CodeTimetableTemplateWeekend                         = "timetable.template_weekend"
	CodeTimetableTooManyDates                            = "timetable.too_many_dates"
	CodeTimetableUnderstaffedStillStaffed                = "timetable.understaffed_still_staffed"
	CodeTimetableWindowEndBeforeStart                    = "timetable.window_end_before_start"
	CodeTimetableWindowTooLarge                          = "timetable.window_too_large"
	CodeWorkforceAbsenceAllowanceExceeded                = "workforce.absence_allowance_exceeded"
	CodeWorkforceAbsenceAlreadyDecided                   = "workforce.absence_already_decided"
	CodeWorkforceAbsenceNoWorkingDays                    = "workforce.absence_no_working_days"
	CodeWorkforceAbsenceNotCancelable                    = "workforce.absence_not_cancelable"
	CodeWorkforceAbsenceNotFound                         = "workforce.absence_not_found"
	CodeWorkforceAbsenceNotOwned                         = "workforce.absence_not_owned"
	CodeWorkforceAbsenceOverlap                          = "workforce.absence_overlap"
	CodeWorkforceAbsenceRebookingBlocked                 = "workforce.absence_rebooking_blocked"
	CodeWorkforceAbsenceTypeInactive                     = "workforce.absence_type_inactive"
	CodeWorkforceAdjustmentInClosedMonth                 = "workforce.adjustment_in_closed_month"
	CodeWorkforceAlreadyCheckedIn                        = "workforce.already_checked_in"
	CodeWorkforceAlreadyCheckedOut                       = "workforce.already_checked_out"
	CodeWorkforceBalanceAdjustmentExceedsBalance         = "workforce.balance_adjustment_exceeds_balance"
	CodeWorkforceBalanceAlreadyReset                     = "workforce.balance_already_reset"
	CodeWorkforceBreakAlreadyActive                      = "workforce.break_already_active"
	CodeWorkforceDecisionNoteRequired                    = "workforce.decision_note_required"
	CodeWorkforceDependentBalanceReset                   = "workforce.dependent_balance_reset"
	CodeWorkforceLaterMonthClosed                        = "workforce.later_month_closed"
	CodeWorkforceManagerControlledAbsence                = "workforce.manager_controlled_absence"
	CodeWorkforceMonthClosed                             = "workforce.month_closed"
	CodeWorkforceMonthNotClosable                        = "workforce.month_not_closable"
	CodeWorkforceMonthNotClosed                          = "workforce.month_not_closed"
	CodeWorkforceNoActiveBreak                           = "workforce.no_active_break"
	CodeWorkforceNoActiveSession                         = "workforce.no_active_session"
	CodeWorkforceNoSessionForToday                       = "workforce.no_session_for_today"
	CodeWorkforceOpeningBalanceAlreadyExists             = "workforce.opening_balance_already_exists"
	CodeWorkforcePayrollConfigIncomplete                 = "workforce.payroll_config_incomplete"
	CodeWorkforcePersonnelNumberInvalid                  = "workforce.personnel_number_invalid"
	CodeWorkforcePersonnelNumberTaken                    = "workforce.personnel_number_taken"
	CodeWorkforceRebookingBeforeVacationOpening          = "workforce.rebooking_before_vacation_opening"
	CodeWorkforceRebookingHalfDayEdge                    = "workforce.rebooking_half_day_edge"
	CodeWorkforceRebookingIntoSickReport                 = "workforce.rebooking_into_sick_report"
	CodeWorkforceRebookingNoWorkingDay                   = "workforce.rebooking_no_working_day"
	CodeWorkforceRebookingNotOver                        = "workforce.rebooking_not_over"
	CodeWorkforceRebookingNothingSelected                = "workforce.rebooking_nothing_selected"
	CodeWorkforceRebookingOutsideBalance                 = "workforce.rebooking_outside_balance"
	CodeWorkforceRebookingOverlap                        = "workforce.rebooking_overlap"
	CodeWorkforceRebookingReasonRequired                 = "workforce.rebooking_reason_required"
	CodeWorkforceRebookingRequest                        = "workforce.rebooking_request"
	CodeWorkforceRebookingSameType                       = "workforce.rebooking_same_type"
	CodeWorkforceRebookingSickReport                     = "workforce.rebooking_sick_report"
	CodeWorkforceRebookingTooMany                        = "workforce.rebooking_too_many"
	CodeWorkforceReplacementOutsideOrigin                = "workforce.replacement_outside_origin"
	CodeWorkforceSessionNotFound                         = "workforce.session_not_found"
	CodeWorkforceSessionNotOwned                         = "workforce.session_not_owned"
	CodeWorkforceSessionNoteRequired                     = "workforce.session_note_required"
	CodeWorkforceSessionTimesInvalid                     = "workforce.session_times_invalid"
	CodeWorkforceShiftChanged                            = "workforce.shift_changed"
	CodeWorkforceShiftDuplicate                          = "workforce.shift_duplicate"
	CodeWorkforceShiftHasReplacements                    = "workforce.shift_has_replacements"
	CodeWorkforceShiftOverlap                            = "workforce.shift_overlap"
	CodeWorkforceShiftSeriesNoOccurrences                = "workforce.shift_series_no_occurrences"
	CodeWorkforceShiftSeriesOutsidePeriod                = "workforce.shift_series_outside_period"
	CodeWorkforceShiftSeriesWeekCycleMissing             = "workforce.shift_series_week_cycle_missing"
	CodeWorkforceShiftTypeInactive                       = "workforce.shift_type_inactive"
	CodeWorkforceStammdatenInvalid                       = "workforce.stammdaten_invalid"
	CodeWorkforceTargetOverrideHoursInvalid              = "workforce.target_override_hours_invalid"
	CodeWorkforceTargetOverrideOverlap                   = "workforce.target_override_overlap"
	CodeWorkforceTargetOverrideRangeInvalid              = "workforce.target_override_range_invalid"
	CodeWorkforceTargetOverrideTooLong                   = "workforce.target_override_too_long"
	CodeWorkforceVacationOpeningAbsencesBeforeCutoff     = "workforce.vacation_opening_absences_before_cutoff"
	CodeWorkforceVacationOpeningAlreadyExists            = "workforce.vacation_opening_already_exists"
	CodeWorkforceVacationQuotaBelowUsed                  = "workforce.vacation_quota_below_used"
	CodeWorkforceVacationQuotaExceeded                   = "workforce.vacation_quota_exceeded"
	CodeWorkforceVacationQuotaReasonRequired             = "workforce.vacation_quota_reason_required"
	CodeWorkforceVacationRequestInPast                   = "workforce.vacation_request_in_past"
	CodeWorkforceWorkSessionOverlap                      = "workforce.work_session_overlap"
)

var errorClassByCode = map[string]string{
	"attendance.web_disabled":                              "permission",
	"care.announcement_ack_not_required":                   "input",
	"care.announcement_not_a_poll":                         "input",
	"care.announcement_stale":                              "business_rejection",
	"care.cannot_remove_own_access":                        "permission",
	"care.care_exception_already_left":                     "business_rejection",
	"care.care_exception_conflict":                         "business_rejection",
	"care.care_exception_no_time":                          "input",
	"care.care_exception_past_date":                        "input",
	"care.care_exception_reason_required":                  "input",
	"care.care_exception_reason_too_long":                  "input",
	"care.care_exception_too_far":                          "input",
	"care.care_request_already_pending":                    "business_rejection",
	"care.care_request_bookings_authoritative":             "permission",
	"care.care_request_field_disabled":                     "permission",
	"care.child_care_ended":                                "permission",
	"care.child_not_linked":                                "permission",
	"care.course_already_booked":                           "input",
	"care.course_request_invalid":                          "input",
	"care.course_request_not_own":                          "input",
	"care.course_requests_disabled":                        "permission",
	"care.declaration_action_not_allowed":                  "business_rejection",
	"care.declaration_closed":                              "business_rejection",
	"care.declaration_not_permitted":                       "permission",
	"care.declaration_password_incorrect":                  "input",
	"care.declaration_password_required":                   "input",
	"care.declaration_version_changed":                     "business_rejection",
	"care.excused_request_not_pending":                     "business_rejection",
	"care.excused_request_overlap":                         "business_rejection",
	"care.family_protection":                               "permission",
	"care.guardian_contact_invalid":                        "input",
	"care.guardian_email_conflict":                         "business_rejection",
	"care.guardian_has_own_account":                        "permission",
	"care.guardian_management_disabled":                    "permission",
	"care.guardian_no_change":                              "input",
	"care.guardian_not_linked":                             "permission",
	"care.guardian_permission_denied":                      "permission",
	"care.guardian_relationship_invalid":                   "input",
	"care.guardian_role_managed":                           "permission",
	"care.guardian_shared_across_families":                 "permission",
	"care.guardian_social_worker_managed":                  "permission",
	"care.invalid_credentials":                             "permission",
	"care.invalid_poll_response":                           "input",
	"care.invalid_recipients":                              "input",
	"care.invalid_request_payload":                         "input",
	"care.invite_disabled":                                 "permission",
	"care.master_data_duplicate_pending":                   "business_rejection",
	"care.master_data_edit_disabled":                       "permission",
	"care.master_data_field_not_editable":                  "permission",
	"care.master_data_invalid_value":                       "input",
	"care.master_data_no_changes":                          "input",
	"care.master_data_request_disabled":                    "permission",
	"care.not_a_guardian":                                  "permission",
	"care.notes_disabled":                                  "permission",
	"care.offering_change_already_pending":                 "business_rejection",
	"care.offering_change_forbidden":                       "permission",
	"care.offering_change_invalid":                         "input",
	"care.offering_changes_disabled":                       "permission",
	"care.payer_guardian_protected":                        "permission",
	"care.photo_consent_not_withdrawn":                     "business_rejection",
	"care.pickup_change_cutoff_passed":                     "business_rejection",
	"care.pickup_change_disabled":                          "permission",
	"care.poll_closed":                                     "business_rejection",
	"care.primary_guardian_protected":                      "permission",
	"care.remove_disabled":                                 "permission",
	"care.request_not_found":                               "business_rejection",
	"care.request_not_open":                                "business_rejection",
	"care.request_sharing_invalid":                         "input",
	"care.sick_note_disabled":                              "permission",
	"care.staff_managed_guardian_protected":                "permission",
	"classday.arrival_exception_class_not_found":           "business_rejection",
	"classday.arrival_exception_editor_required":           "permission",
	"classday.arrival_exception_past_date":                 "input",
	"classday.arrival_exception_weekend":                   "input",
	"classday.school_write_disabled":                       "permission",
	"communication.announcement_not_published":             "business_rejection",
	"communication.announcement_published_immutable":       "business_rejection",
	"communication.announcement_reminder_sent":             "business_rejection",
	"communication.declaration_has_submissions":            "business_rejection",
	"communication.parent_news_disabled":                   "permission",
	"communication.poll_not_open":                          "business_rejection",
	"communication.staff_counterpart_unavailable":          "unavailable",
	"communication.staff_messaging_disabled":               "permission",
	"communication.system_announcement_immutable":          "business_rejection",
	"enrollment.approval_care_offering_exactly_one":        "business_rejection",
	"enrollment.approval_care_offering_missing":            "business_rejection",
	"enrollment.approval_data_invalid":                     "input",
	"enrollment.captcha_failed":                            "input",
	"enrollment.captcha_required":                          "input",
	"enrollment.care_offering_auto_add_invalid":            "input",
	"enrollment.care_offering_capacity_invalid":            "input",
	"enrollment.care_offering_closed":                      "business_rejection",
	"enrollment.care_offering_days_required":               "input",
	"enrollment.care_offering_exactly_one":                 "input",
	"enrollment.care_offering_full":                        "business_rejection",
	"enrollment.care_offering_in_use":                      "business_rejection",
	"enrollment.care_offering_missing":                     "input",
	"enrollment.care_offering_name_required":               "input",
	"enrollment.care_offering_not_found":                   "business_rejection",
	"enrollment.care_offering_pickup_time_invalid":         "input",
	"enrollment.care_offering_pickup_times_required":       "input",
	"enrollment.care_offering_price_invalid":               "input",
	"enrollment.care_offering_selection_invalid":           "input",
	"enrollment.care_offering_template_period_mismatch":    "input",
	"enrollment.care_offering_unavailable":                 "business_rejection",
	"enrollment.care_offerings_disabled":                   "permission",
	"enrollment.change_request_child_locked":               "permission",
	"enrollment.change_request_conflict":                   "business_rejection",
	"enrollment.change_request_guardian_linked":            "input",
	"enrollment.change_request_not_allowed":                "permission",
	"enrollment.change_request_not_found":                  "business_rejection",
	"enrollment.change_request_note_required":              "input",
	"enrollment.change_request_status_changed":             "business_rejection",
	"enrollment.child_already_enrolled":                    "business_rejection",
	"enrollment.child_already_requested":                   "business_rejection",
	"enrollment.child_ambiguous":                           "input",
	"enrollment.child_birth_date_invalid":                  "input",
	"enrollment.child_deletion_not_allowed":                "business_rejection",
	"enrollment.child_grade_required":                      "input",
	"enrollment.child_name_required":                       "input",
	"enrollment.child_not_enrolled":                        "business_rejection",
	"enrollment.child_not_permitted":                       "permission",
	"enrollment.child_required":                            "input",
	"enrollment.class_not_eligible":                        "input",
	"enrollment.companion_note_required":                   "input",
	"enrollment.complete_withdrawal_confirmation_required": "input",
	"enrollment.consent_required":                          "input",
	"enrollment.correction_reason_required":                "input",
	"enrollment.correction_school_class_mismatch":          "input",
	"enrollment.day_selection_not_allowed":                 "input",
	"enrollment.day_selection_required":                    "input",
	"enrollment.decision_already_final":                    "business_rejection",
	"enrollment.deletion_reason_invalid":                   "input",
	"enrollment.departure_mode_limit":                      "input",
	"enrollment.disabled":                                  "business_rejection",
	"enrollment.duplicate_detected":                        "business_rejection",
	"enrollment.edit_not_allowed":                          "permission",
	"enrollment.export_too_large":                          "input",
	"enrollment.field_required":                            "input",
	"enrollment.form_field_allowed_times_invalid":          "input",
	"enrollment.form_field_content_required":               "input",
	"enrollment.form_field_key_duplicate":                  "input",
	"enrollment.form_field_key_invalid":                    "input",
	"enrollment.form_field_label_required":                 "input",
	"enrollment.form_field_options_invalid":                "input",
	"enrollment.form_field_target_duplicate":               "input",
	"enrollment.form_field_target_invalid":                 "input",
	"enrollment.form_field_visibility_invalid":             "input",
	"enrollment.form_grade_collection_required":            "input",
	"enrollment.form_not_found":                            "business_rejection",
	"enrollment.grade_not_eligible":                        "input",
	"enrollment.guardian_account_mismatch":                 "business_rejection",
	"enrollment.guardian_email_required":                   "input",
	"enrollment.guardian_name_required":                    "input",
	"enrollment.guardian_phone_required":                   "input",
	"enrollment.invalid_email":                             "input",
	"enrollment.invalid_phone":                             "input",
	"enrollment.late_invite_invalid":                       "input",
	"enrollment.legal_block_incomplete":                    "input",
	"enrollment.legal_block_key_duplicate":                 "input",
	"enrollment.legal_block_key_invalid":                   "input",
	"enrollment.legal_block_required_not_allowed":          "input",
	"enrollment.legal_document_invalid":                    "input",
	"enrollment.message_required":                          "input",
	"enrollment.offering_adjustment_invalid":               "input",
	"enrollment.phase_care_offering_conflict":              "business_rejection",
	"enrollment.phase_eligibility_setting_required":        "input",
	"enrollment.phase_name_exists":                         "business_rejection",
	"enrollment.phase_name_required":                       "input",
	"enrollment.phase_not_eligible":                        "permission",
	"enrollment.phase_not_found":                           "business_rejection",
	"enrollment.phase_school_classes_invalid":              "input",
	"enrollment.phase_service_period_invalid":              "input",
	"enrollment.phase_window_invalid":                      "input",
	"enrollment.pickup_time_not_allowed":                   "input",
	"enrollment.request_duplicate":                         "business_rejection",
	"enrollment.request_not_found":                         "business_rejection",
	"enrollment.required_care_offering_missing":            "input",
	"enrollment.restore_duplicate":                         "business_rejection",
	"enrollment.restore_nothing_withdrawn":                 "business_rejection",
	"enrollment.restore_offering_closed":                   "business_rejection",
	"enrollment.restore_phase_inactive":                    "business_rejection",
	"enrollment.schema_has_phases":                         "business_rejection",
	"enrollment.schema_has_requests":                       "business_rejection",
	"enrollment.schema_name_exists":                        "business_rejection",
	"enrollment.schema_name_required":                      "input",
	"enrollment.schema_not_found":                          "business_rejection",
	"enrollment.selected_day_not_available":                "input",
	"enrollment.status_link_invalid":                       "business_rejection",
	"enrollment.student_exists":                            "business_rejection",
	"enrollment.submission_rate_limited":                   "unavailable",
	"enrollment.waitlist_disabled":                         "business_rejection",
	"enrollment.window_closed":                             "business_rejection",
	"enrollment.withdraw_not_allowed":                      "permission",
	"files.announcement_published":                         "business_rejection",
	"files.attachment_limit_reached":                       "business_rejection",
	"files.folder_name_taken":                              "business_rejection",
	"files.quota_exceeded":                                 "business_rejection",
	"general.business_rejection":                           "business_rejection",
	"general.input":                                        "input",
	"general.permission":                                   "permission",
	"general.server":                                       "server",
	"general.unavailable":                                  "unavailable",
	"grade_transition.graduates_checked_in":                "business_rejection",
	"grade_transition.not_applied":                         "business_rejection",
	"grade_transition.not_draft":                           "business_rejection",
	"grade_transition.not_latest_transition":               "business_rejection",
	"grade_transition.preview_stale":                       "business_rejection",
	"identity.account_already_has_tenant_access":           "business_rejection",
	"identity.account_inactive":                            "permission",
	"identity.demo_access_expired":                         "business_rejection",
	"identity.demo_access_invalid":                         "input",
	"identity.demo_access_rate_limited":                    "unavailable",
	"identity.demo_access_unknown":                         "input",
	"identity.demo_capacity_reached":                       "unavailable",
	"identity.demo_school_preparing":                       "unavailable",
	"identity.demo_session":                                "permission",
	"identity.email_already_exists":                        "business_rejection",
	"identity.invitation_account_login_required":           "permission",
	"identity.invitation_account_mismatch":                 "permission",
	"identity.preview_target_not_previewable":              "permission",
	"identity.preview_target_school_portal":                "permission",
	"identity.preview_token_invalid":                       "permission",
	"identity.read_only_preview":                           "permission",
	"identity.session_account_inactive":                    "permission",
	"identity.use_parent_portal":                           "permission",
	"identity.use_school_portal":                           "permission",
	"import.import_batch_failed":                           "server",
	"iot.activity_capacity_exceeded":                       "business_rejection",
	"iot.deviation_reason_required":                        "input",
	"iot.invalid_rfid_tag":                                 "input",
	"iot.invalid_staff_clock_request":                      "input",
	"iot.invalid_staff_clock_state":                        "business_rejection",
	"iot.open_room_binary_mode":                            "business_rejection",
	"iot.planned_start_not_reached":                        "business_rejection",
	"iot.rfid_tag_inactive":                                "business_rejection",
	"iot.rfid_tag_not_found":                               "business_rejection",
	"iot.rfid_tag_not_staff":                               "business_rejection",
	"iot.room_capacity_exceeded":                           "business_rejection",
	"iot.room_not_found":                                   "business_rejection",
	"iot.student_already_active":                           "business_rejection",
	"iot.student_not_present":                              "business_rejection",
	"meals.invalid_dishes":                                 "input",
	"meals.invalid_meal_date":                              "input",
	"meals.invalid_participation":                          "input",
	"meals.participation_cutoff_passed":                    "business_rejection",
	"meals.participation_out_of_range":                     "input",
	"meals.plan_disabled":                                  "permission",
	"meals.plan_week_out_of_range":                         "input",
	"meals.registration_disabled":                          "permission",
	"pickup.bulk_exception_confirmation_required":          "input",
	"pickup.future_manual_reset":                           "business_rejection",
	"pickup.invalid":                                       "input",
	"pickup.offering_capacity_full":                        "business_rejection",
	"pickup.offerings_disabled":                            "business_rejection",
	"pickup.preview_stale":                                 "business_rejection",
	"pickup.resolution_required":                           "input",
	"presence.activity_participant_limit_reached":          "business_rejection",
	"presence.room_capacity_exceeded":                      "business_rejection",
	"rollover.deadline_required":                           "input",
	"rollover.duplicate_name":                              "business_rejection",
	"rollover.invalid_request":                             "input",
	"rollover.review_invalid":                              "input",
	"rollover.review_not_found":                            "business_rejection",
	"rollover.source_already_rolled":                       "business_rejection",
	"rollover.source_not_found":                            "business_rejection",
	"rooms.color_already_in_use":                           "business_rejection",
	"rooms.not_released":                                   "business_rejection",
	"school.no_school_portal_role":                         "permission",
	"school.setup_completed":                               "business_rejection",
	"school.setup_incomplete":                              "business_rejection",
	"students.absence_read_required":                       "permission",
	"students.bulk_approval_ineligible":                    "business_rejection",
	"students.care_day_managed_by_booking":                 "business_rejection",
	"students.care_exception_raced":                        "business_rejection",
	"students.care_exit_already_effective":                 "business_rejection",
	"students.care_exit_blocked":                           "business_rejection",
	"students.care_exit_day_in_past":                       "input",
	"students.care_exit_invalid_reason":                    "input",
	"students.care_exit_no_students":                       "input",
	"students.care_exit_not_planned":                       "business_rejection",
	"students.care_exit_note_not_allowed":                  "input",
	"students.care_exit_note_required":                     "input",
	"students.care_exit_note_too_long":                     "input",
	"students.care_exit_preview_changed":                   "business_rejection",
	"students.care_exit_too_many_students":                 "input",
	"students.care_offerings_disabled":                     "permission",
	"students.care_resume_missing":                         "business_rejection",
	"students.care_resume_not_checked":                     "input",
	"students.care_resume_not_ended":                       "business_rejection",
	"students.care_resume_start_in_past":                   "input",
	"students.care_withdrawal_after_gap":                   "input",
	"students.care_withdrawal_already_resolved":            "business_rejection",
	"students.care_withdrawal_date_invalid":                "input",
	"students.care_withdrawal_not_found":                   "business_rejection",
	"students.change_request_not_pending":                  "business_rejection",
	"students.change_request_stale":                        "business_rejection",
	"students.checkin_care_ended":                          "business_rejection",
	"students.checkout_note_too_long":                      "input",
	"students.child_quota_reached":                         "business_rejection",
	"students.companion_lock_busy":                         "business_rejection",
	"students.companion_would_lose_departure":              "input",
	"students.companions_changed":                          "business_rejection",
	"students.conflict_kind_unsupported":                   "input",
	"students.correction_unsupported":                      "business_rejection",
	"students.deletion_acknowledgement_required":           "input",
	"students.deletion_alumnus":                            "business_rejection",
	"students.deletion_companion_blocked":                  "business_rejection",
	"students.deletion_companion_lock_busy":                "business_rejection",
	"students.deletion_confirmation_mismatch":              "input",
	"students.deletion_constraints_changed":                "business_rejection",
	"students.deletion_invalid_reason":                     "input",
	"students.deletion_preview_changed":                    "business_rejection",
	"students.deletion_retention_not_ended":                "business_rejection",
	"students.excused_request_status_conflict":             "business_rejection",
	"students.export_selection_too_large":                  "input",
	"students.guardian_access_revoked":                     "business_rejection",
	"students.guardian_account_holder_too_long":            "input",
	"students.guardian_email_taken":                        "input",
	"students.guardian_iban_invalid":                       "input",
	"students.offering_change_capacity_full":               "business_rejection",
	"students.offering_change_date_out_of_range":           "input",
	"students.offering_changes_no_enrollment":              "permission",
	"students.partial_absence_conflict":                    "business_rejection",
	"students.partial_absence_requires_dedicated_action":   "business_rejection",
	"students.photo_consent_required":                      "input",
	"students.photo_consent_withdrawn":                     "business_rejection",
	"students.photos_disabled":                             "permission",
	"students.pickup_change_completed":                     "business_rejection",
	"students.pickup_change_conflict":                      "business_rejection",
	"students.pickup_change_expired":                       "business_rejection",
	"students.pickup_change_impact_changed":                "business_rejection",
	"students.pickup_reset_requires_offering":              "business_rejection",
	"students.reason_required":                             "input",
	"students.request_not_decided":                         "business_rejection",
	"students.request_not_past":                            "business_rejection",
	"students.request_past":                                "business_rejection",
	"students.sick_excused_conflict":                       "business_rejection",
	"students.staff_profile_required":                      "permission",
	"students.staff_value_invalid":                         "input",
	"students.staff_value_unsupported":                     "input",
	"students.status_day_conflict":                         "business_rejection",
	"substitutions.already_assigned":                       "business_rejection",
	"substitutions.conflict":                               "business_rejection",
	"substitutions.forbidden":                              "permission",
	"substitutions.internal":                               "server",
	"substitutions.invalid_period":                         "input",
	"substitutions.invalid_target":                         "input",
	"substitutions.not_found":                              "business_rejection",
	"substitutions.not_running":                            "business_rejection",
	"substitutions.self_assignment":                        "input",
	"timetable.ambiguous_template_instance_delete":         "business_rejection",
	"timetable.attendance_entry_not_found":                 "business_rejection",
	"timetable.attendance_frozen":                          "business_rejection",
	"timetable.attendance_invalid":                         "input",
	"timetable.calendar_period_care_offering_conflict":     "business_rejection",
	"timetable.calendar_period_end_before_start":           "input",
	"timetable.calendar_period_invalid":                    "input",
	"timetable.calendar_period_name_taken":                 "business_rejection",
	"timetable.calendar_period_not_found":                  "business_rejection",
	"timetable.calendar_period_overlap_conflict":           "business_rejection",
	"timetable.calendar_period_roster_conflict":            "business_rejection",
	"timetable.calendar_period_week_cycle_anchor_missing":  "input",
	"timetable.closing_day_end_before_start":               "input",
	"timetable.closing_day_invalid":                        "input",
	"timetable.closing_day_not_found":                      "business_rejection",
	"timetable.complete_too_early":                         "business_rejection",
	"timetable.completion_confirmation_stale":              "business_rejection",
	"timetable.correction_cancelled":                       "business_rejection",
	"timetable.correction_not_completed":                   "business_rejection",
	"timetable.correction_reason_missing":                  "input",
	"timetable.correction_reason_too_long":                 "input",
	"timetable.date_in_past":                               "input",
	"timetable.dates_in_past":                              "input",
	"timetable.dates_required":                             "input",
	"timetable.deviation_note_too_long":                    "input",
	"timetable.deviation_selection_invalid":                "input",
	"timetable.duplicate_instance":                         "business_rejection",
	"timetable.export_end_before_start":                    "input",
	"timetable.export_internal_forbidden":                  "permission",
	"timetable.export_range_too_large":                     "input",
	"timetable.group_already_ended":                        "business_rejection",
	"timetable.guardian_notice_disabled":                   "permission",
	"timetable.guardian_notice_invalid":                    "input",
	"timetable.guardian_notice_past":                       "input",
	"timetable.guardian_notice_text_invalid":               "input",
	"timetable.idempotency_key_reused":                     "business_rejection",
	"timetable.instance_end_before_start":                  "input",
	"timetable.instance_in_past":                           "input",
	"timetable.instance_invalid":                           "input",
	"timetable.instance_moved":                             "business_rejection",
	"timetable.instance_not_active":                        "business_rejection",
	"timetable.instance_not_convertible":                   "business_rejection",
	"timetable.instance_not_editable":                      "business_rejection",
	"timetable.instance_not_found":                         "business_rejection",
	"timetable.instance_outside_period":                    "input",
	"timetable.instance_selection_invalid":                 "input",
	"timetable.instance_weekend":                           "input",
	"timetable.instances_not_assigned":                     "input",
	"timetable.instances_other_day":                        "input",
	"timetable.instances_required":                         "input",
	"timetable.invalid_transition":                         "business_rejection",
	"timetable.move_other_day":                             "input",
	"timetable.move_same_instance":                         "input",
	"timetable.no_staff_profile":                           "permission",
	"timetable.offering_source_inactive":                   "business_rejection",
	"timetable.offering_source_invalid":                    "input",
	"timetable.offering_source_mixed_phases":               "input",
	"timetable.offering_source_not_found":                  "business_rejection",
	"timetable.offering_source_outside_period":             "business_rejection",
	"timetable.offering_source_too_many":                   "input",
	"timetable.only_supervisor_replacement_required":       "business_rejection",
	"timetable.operation_stale":                            "business_rejection",
	"timetable.pickup_extension_block_gone":                "business_rejection",
	"timetable.pickup_extension_invalid":                   "input",
	"timetable.pickup_extension_not_found":                 "business_rejection",
	"timetable.pickup_extension_too_many_blocks":           "input",
	"timetable.planning_track_archived":                    "business_rejection",
	"timetable.planning_track_invalid":                     "input",
	"timetable.planning_track_name_taken":                  "business_rejection",
	"timetable.planning_track_not_found":                   "business_rejection",
	"timetable.presence_would_overstaff":                   "business_rejection",
	"timetable.reopen_attendance_changed":                  "business_rejection",
	"timetable.reopen_staff_busy":                          "business_rejection",
	"timetable.reopen_student_active":                      "business_rejection",
	"timetable.reopen_supervision_changed":                 "business_rejection",
	"timetable.room_occupied":                              "business_rejection",
	"timetable.series_end_before_start":                    "input",
	"timetable.series_end_outside_period":                  "input",
	"timetable.sick_absence_scope_locked":                  "business_rejection",
	"timetable.slot_list_drifted":                          "business_rejection",
	"timetable.slot_list_grouping_invalid":                 "input",
	"timetable.slot_list_pickup_past_date":                 "input",
	"timetable.slot_list_reconciliation_future_date":       "input",
	"timetable.slot_lists_disabled":                        "permission",
	"timetable.spontaneous_activities_disabled":            "permission",
	"timetable.spontaneous_category_archived":              "business_rejection",
	"timetable.staff_absent_on_date":                       "business_rejection",
	"timetable.staff_absent_on_source":                     "input",
	"timetable.staff_absent_on_target":                     "business_rejection",
	"timetable.staff_already_on_target":                    "business_rejection",
	"timetable.staff_not_found":                            "business_rejection",
	"timetable.staff_not_on_source":                        "input",
	"timetable.staff_present_and_absent":                   "input",
	"timetable.start_too_early":                            "business_rejection",
	"timetable.start_window_expired":                       "business_rejection",
	"timetable.student_already_active":                     "business_rejection",
	"timetable.student_care_ended":                         "business_rejection",
	"timetable.student_graduated":                          "business_rejection",
	"timetable.student_not_checked_in":                     "business_rejection",
	"timetable.student_not_found":                          "business_rejection",
	"timetable.students_not_present":                       "business_rejection",
	"timetable.substitute_absent":                          "input",
	"timetable.substitute_absent_on_date":                  "input",
	"timetable.substitute_conflict":                        "business_rejection",
	"timetable.substitute_not_on_instances":                "input",
	"timetable.substitute_self":                            "input",
	"timetable.substitute_single_only":                     "input",
	"timetable.template_care_offering_conflict":            "input",
	"timetable.template_category_unavailable":              "business_rejection",
	"timetable.template_education_group_invalid":           "input",
	"timetable.template_end_before_start":                  "input",
	"timetable.template_grade_above_max":                   "input",
	"timetable.template_invalid":                           "input",
	"timetable.template_max_participants_invalid":          "input",
	"timetable.template_not_found":                         "business_rejection",
	"timetable.template_planning_track_unavailable":        "business_rejection",
	"timetable.template_roster_rebase_conflict":            "business_rejection",
	"timetable.template_split_in_past":                     "input",
	"timetable.template_split_invalid":                     "input",
	"timetable.template_start_in_past":                     "input",
	"timetable.template_start_not_earlier":                 "input",
	"timetable.template_start_outside_period":              "input",
	"timetable.template_start_predecessor_overlap":         "input",
	"timetable.template_week_pattern_invalid":              "input",
	"timetable.template_weekend":                           "input",
	"timetable.too_many_dates":                             "input",
	"timetable.understaffed_still_staffed":                 "business_rejection",
	"timetable.window_end_before_start":                    "input",
	"timetable.window_too_large":                           "input",
	"workforce.absence_allowance_exceeded":                 "business_rejection",
	"workforce.absence_already_decided":                    "business_rejection",
	"workforce.absence_no_working_days":                    "input",
	"workforce.absence_not_cancelable":                     "business_rejection",
	"workforce.absence_not_found":                          "business_rejection",
	"workforce.absence_not_owned":                          "permission",
	"workforce.absence_overlap":                            "business_rejection",
	"workforce.absence_rebooking_blocked":                  "business_rejection",
	"workforce.absence_type_inactive":                      "business_rejection",
	"workforce.adjustment_in_closed_month":                 "input",
	"workforce.already_checked_in":                         "business_rejection",
	"workforce.already_checked_out":                        "business_rejection",
	"workforce.balance_adjustment_exceeds_balance":         "business_rejection",
	"workforce.balance_already_reset":                      "business_rejection",
	"workforce.break_already_active":                       "business_rejection",
	"workforce.decision_note_required":                     "input",
	"workforce.dependent_balance_reset":                    "business_rejection",
	"workforce.later_month_closed":                         "business_rejection",
	"workforce.manager_controlled_absence":                 "permission",
	"workforce.month_closed":                               "business_rejection",
	"workforce.month_not_closable":                         "input",
	"workforce.month_not_closed":                           "business_rejection",
	"workforce.no_active_break":                            "business_rejection",
	"workforce.no_active_session":                          "business_rejection",
	"workforce.no_session_for_today":                       "business_rejection",
	"workforce.opening_balance_already_exists":             "business_rejection",
	"workforce.payroll_config_incomplete":                  "business_rejection",
	"workforce.personnel_number_invalid":                   "input",
	"workforce.personnel_number_taken":                     "business_rejection",
	"workforce.rebooking_before_vacation_opening":          "business_rejection",
	"workforce.rebooking_half_day_edge":                    "business_rejection",
	"workforce.rebooking_into_sick_report":                 "business_rejection",
	"workforce.rebooking_no_working_day":                   "business_rejection",
	"workforce.rebooking_not_over":                         "business_rejection",
	"workforce.rebooking_nothing_selected":                 "input",
	"workforce.rebooking_outside_balance":                  "business_rejection",
	"workforce.rebooking_overlap":                          "business_rejection",
	"workforce.rebooking_reason_required":                  "input",
	"workforce.rebooking_request":                          "business_rejection",
	"workforce.rebooking_same_type":                        "business_rejection",
	"workforce.rebooking_sick_report":                      "business_rejection",
	"workforce.rebooking_too_many":                         "input",
	"workforce.replacement_outside_origin":                 "input",
	"workforce.session_not_found":                          "business_rejection",
	"workforce.session_not_owned":                          "permission",
	"workforce.session_note_required":                      "input",
	"workforce.session_times_invalid":                      "input",
	"workforce.shift_changed":                              "business_rejection",
	"workforce.shift_duplicate":                            "business_rejection",
	"workforce.shift_has_replacements":                     "business_rejection",
	"workforce.shift_overlap":                              "business_rejection",
	"workforce.shift_series_no_occurrences":                "input",
	"workforce.shift_series_outside_period":                "input",
	"workforce.shift_series_week_cycle_missing":            "input",
	"workforce.shift_type_inactive":                        "business_rejection",
	"workforce.stammdaten_invalid":                         "input",
	"workforce.target_override_hours_invalid":              "input",
	"workforce.target_override_overlap":                    "business_rejection",
	"workforce.target_override_range_invalid":              "input",
	"workforce.target_override_too_long":                   "input",
	"workforce.vacation_opening_absences_before_cutoff":    "business_rejection",
	"workforce.vacation_opening_already_exists":            "business_rejection",
	"workforce.vacation_quota_below_used":                  "business_rejection",
	"workforce.vacation_quota_exceeded":                    "business_rejection",
	"workforce.vacation_quota_reason_required":             "input",
	"workforce.vacation_request_in_past":                   "input",
	"workforce.work_session_overlap":                       "business_rejection",
}
