// Code generated by scripts/generate-error-codes.mjs; DO NOT EDIT.
package common

const (
	CodeCareAnnouncementAckNotRequired                   = "care.announcement_ack_not_required"
	CodeCareAnnouncementNotAPoll                         = "care.announcement_not_a_poll"
	CodeCareAnnouncementStale                            = "care.announcement_stale"
	CodeCareCannotRemoveOwnAccess                        = "care.cannot_remove_own_access"
	CodeCareCareExceptionAlreadyLeft                     = "care.care_exception_already_left"
	CodeCareCareExceptionConflict                        = "care.care_exception_conflict"
	CodeCareCareExceptionNoTime                          = "care.care_exception_no_time"
	CodeCareCareExceptionPastDate                        = "care.care_exception_past_date"
	CodeCareCareExceptionReasonRequired                  = "care.care_exception_reason_required"
	CodeCareCareExceptionReasonTooLong                   = "care.care_exception_reason_too_long"
	CodeCareCareExceptionTooFar                          = "care.care_exception_too_far"
	CodeCareCareRequestAlreadyPending                    = "care.care_request_already_pending"
	CodeCareCareRequestBookingsAuthoritative             = "care.care_request_bookings_authoritative"
	CodeCareCareRequestFieldDisabled                     = "care.care_request_field_disabled"
	CodeCareChildCareEnded                               = "care.child_care_ended"
	CodeCareChildNotLinked                               = "care.child_not_linked"
	CodeCareCourseAlreadyBooked                          = "care.course_already_booked"
	CodeCareCourseRequestInvalid                         = "care.course_request_invalid"
	CodeCareCourseRequestNotOwn                          = "care.course_request_not_own"
	CodeCareCourseRequestsDisabled                       = "care.course_requests_disabled"
	CodeCareExcusedRequestNotPending                     = "care.excused_request_not_pending"
	CodeCareExcusedRequestOverlap                        = "care.excused_request_overlap"
	CodeCareFamilyProtection                             = "care.family_protection"
	CodeCareGuardianContactInvalid                       = "care.guardian_contact_invalid"
	CodeCareGuardianEmailConflict                        = "care.guardian_email_conflict"
	CodeCareGuardianHasOwnAccount                        = "care.guardian_has_own_account"
	CodeCareGuardianManagementDisabled                   = "care.guardian_management_disabled"
	CodeCareGuardianNoChange                             = "care.guardian_no_change"
	CodeCareGuardianNotLinked                            = "care.guardian_not_linked"
	CodeCareGuardianPermissionDenied                     = "care.guardian_permission_denied"
	CodeCareGuardianRelationshipInvalid                  = "care.guardian_relationship_invalid"
	CodeCareGuardianRoleManaged                          = "care.guardian_role_managed"
	CodeCareGuardianSharedAcrossFamilies                 = "care.guardian_shared_across_families"
	CodeCareGuardianSocialWorkerManaged                  = "care.guardian_social_worker_managed"
	CodeCareInvalidCredentials                           = "care.invalid_credentials"
	CodeCareInvalidPollResponse                          = "care.invalid_poll_response"
	CodeCareInvalidRecipients                            = "care.invalid_recipients"
	CodeCareInvalidRequestPayload                        = "care.invalid_request_payload"
	CodeCareInviteDisabled                               = "care.invite_disabled"
	CodeCareMasterDataDuplicatePending                   = "care.master_data_duplicate_pending"
	CodeCareMasterDataEditDisabled                       = "care.master_data_edit_disabled"
	CodeCareMasterDataFieldNotEditable                   = "care.master_data_field_not_editable"
	CodeCareMasterDataInvalidValue                       = "care.master_data_invalid_value"
	CodeCareMasterDataNoChanges                          = "care.master_data_no_changes"
	CodeCareMasterDataRequestDisabled                    = "care.master_data_request_disabled"
	CodeCareNotAGuardian                                 = "care.not_a_guardian"
	CodeCareNotesDisabled                                = "care.notes_disabled"
	CodeCareOfferingChangeAlreadyPending                 = "care.offering_change_already_pending"
	CodeCareOfferingChangeForbidden                      = "care.offering_change_forbidden"
	CodeCareOfferingChangeInvalid                        = "care.offering_change_invalid"
	CodeCareOfferingChangesDisabled                      = "care.offering_changes_disabled"
	CodeCarePayerGuardianProtected                       = "care.payer_guardian_protected"
	CodeCarePhotoConsentNotWithdrawn                     = "care.photo_consent_not_withdrawn"
	CodeCarePickupChangeCutoffPassed                     = "care.pickup_change_cutoff_passed"
	CodeCarePickupChangeDisabled                         = "care.pickup_change_disabled"
	CodeCarePollClosed                                   = "care.poll_closed"
	CodeCarePrimaryGuardianProtected                     = "care.primary_guardian_protected"
	CodeCareRemoveDisabled                               = "care.remove_disabled"
	CodeCareRequestNotFound                              = "care.request_not_found"
	CodeCareRequestNotOpen                               = "care.request_not_open"
	CodeCareRequestSharingInvalid                        = "care.request_sharing_invalid"
	CodeCareSickNoteDisabled                             = "care.sick_note_disabled"
	CodeCareStaffManagedGuardianProtected                = "care.staff_managed_guardian_protected"
	CodeClassdayArrivalExceptionClassNotFound            = "classday.arrival_exception_class_not_found"
	CodeClassdayArrivalExceptionEditorRequired           = "classday.arrival_exception_editor_required"
	CodeClassdayArrivalExceptionPastDate                 = "classday.arrival_exception_past_date"
	CodeClassdayArrivalExceptionWeekend                  = "classday.arrival_exception_weekend"
	CodeClassdaySchoolWriteDisabled                      = "classday.school_write_disabled"
	CodeCommunicationAnnouncementNotPublished            = "communication.announcement_not_published"
	CodeCommunicationAnnouncementPublishedImmutable      = "communication.announcement_published_immutable"
	CodeCommunicationAnnouncementReminderSent            = "communication.announcement_reminder_sent"
	CodeCommunicationParentNewsDisabled                  = "communication.parent_news_disabled"
	CodeCommunicationPollNotOpen                         = "communication.poll_not_open"
	CodeCommunicationStaffCounterpartUnavailable         = "communication.staff_counterpart_unavailable"
	CodeCommunicationStaffMessagingDisabled              = "communication.staff_messaging_disabled"
	CodeCommunicationSystemAnnouncementImmutable         = "communication.system_announcement_immutable"
	CodeEnrollmentApprovalCareOfferingExactlyOne         = "enrollment.approval_care_offering_exactly_one"
	CodeEnrollmentApprovalCareOfferingMissing            = "enrollment.approval_care_offering_missing"
	CodeEnrollmentCareOfferingDaysRequired               = "enrollment.care_offering_days_required"
	CodeEnrollmentCareOfferingExactlyOne                 = "enrollment.care_offering_exactly_one"
	CodeEnrollmentCareOfferingFull                       = "enrollment.care_offering_full"
	CodeEnrollmentCareOfferingInUse                      = "enrollment.care_offering_in_use"
	CodeEnrollmentCareOfferingMissing                    = "enrollment.care_offering_missing"
	CodeEnrollmentCareOfferingPickupTimesRequired        = "enrollment.care_offering_pickup_times_required"
	CodeEnrollmentCareOfferingTemplatePeriodMismatch     = "enrollment.care_offering_template_period_mismatch"
	CodeEnrollmentCareOfferingUnavailable                = "enrollment.care_offering_unavailable"
	CodeEnrollmentCareOfferingsDisabled                  = "enrollment.care_offerings_disabled"
	CodeEnrollmentChangeRequestChildLocked               = "enrollment.change_request_child_locked"
	CodeEnrollmentChangeRequestConflict                  = "enrollment.change_request_conflict"
	CodeEnrollmentChildAlreadyEnrolled                   = "enrollment.child_already_enrolled"
	CodeEnrollmentChildAmbiguous                         = "enrollment.child_ambiguous"
	CodeEnrollmentChildDeletionNotAllowed                = "enrollment.child_deletion_not_allowed"
	CodeEnrollmentChildNotEnrolled                       = "enrollment.child_not_enrolled"
	CodeEnrollmentChildNotPermitted                      = "enrollment.child_not_permitted"
	CodeEnrollmentClassNotEligible                       = "enrollment.class_not_eligible"
	CodeEnrollmentCompleteWithdrawalConfirmationRequired = "enrollment.complete_withdrawal_confirmation_required"
	CodeEnrollmentDaySelectionNotAllowed                 = "enrollment.day_selection_not_allowed"
	CodeEnrollmentDaySelectionRequired                   = "enrollment.day_selection_required"
	CodeEnrollmentDepartureModeLimit                     = "enrollment.departure_mode_limit"
	CodeEnrollmentDisabled                               = "enrollment.disabled"
	CodeEnrollmentDuplicateDetected                      = "enrollment.duplicate_detected"
	CodeEnrollmentGradeNotEligible                       = "enrollment.grade_not_eligible"
	CodeEnrollmentGuardianAccountMismatch                = "enrollment.guardian_account_mismatch"
	CodeEnrollmentInvalidEmail                           = "enrollment.invalid_email"
	CodeEnrollmentInvalidPhone                           = "enrollment.invalid_phone"
	CodeEnrollmentLateInviteInvalid                      = "enrollment.late_invite_invalid"
	CodeEnrollmentPhaseCareOfferingConflict              = "enrollment.phase_care_offering_conflict"
	CodeEnrollmentPhaseNameExists                        = "enrollment.phase_name_exists"
	CodeEnrollmentPhaseNotEligible                       = "enrollment.phase_not_eligible"
	CodeEnrollmentPickupTimeNotAllowed                   = "enrollment.pickup_time_not_allowed"
	CodeEnrollmentRequiredCareOfferingMissing            = "enrollment.required_care_offering_missing"
	CodeEnrollmentRestoreDuplicate                       = "enrollment.restore_duplicate"
	CodeEnrollmentRestoreOfferingClosed                  = "enrollment.restore_offering_closed"
	CodeEnrollmentRestorePhaseInactive                   = "enrollment.restore_phase_inactive"
	CodeEnrollmentSchemaHasPhases                        = "enrollment.schema_has_phases"
	CodeEnrollmentSchemaHasRequests                      = "enrollment.schema_has_requests"
	CodeEnrollmentSchemaNameExists                       = "enrollment.schema_name_exists"
	CodeEnrollmentSelectedDayNotAvailable                = "enrollment.selected_day_not_available"
	CodeEnrollmentStudentExists                          = "enrollment.student_exists"
	CodeEnrollmentWaitlistDisabled                       = "enrollment.waitlist_disabled"
	CodeEnrollmentWindowClosed                           = "enrollment.window_closed"
	CodeFilesAnnouncementPublished                       = "files.announcement_published"
	CodeFilesAttachmentLimitReached                      = "files.attachment_limit_reached"
	CodeFilesFolderNameTaken                             = "files.folder_name_taken"
	CodeFilesQuotaExceeded                               = "files.quota_exceeded"
	CodeGeneralBusinessRejection                         = "general.business_rejection"
	CodeGeneralInput                                     = "general.input"
	CodeGeneralPermission                                = "general.permission"
	CodeGeneralServer                                    = "general.server"
	CodeGeneralUnavailable                               = "general.unavailable"
	CodeGradeTransitionGraduatesCheckedIn                = "grade_transition.graduates_checked_in"
	CodeGradeTransitionNotApplied                        = "grade_transition.not_applied"
	CodeGradeTransitionNotDraft                          = "grade_transition.not_draft"
	CodeGradeTransitionNotLatestTransition               = "grade_transition.not_latest_transition"
	CodeGradeTransitionPreviewStale                      = "grade_transition.preview_stale"
	CodeIdentityAccountAlreadyHasTenantAccess            = "identity.account_already_has_tenant_access"
	CodeIdentityAccountInactive                          = "identity.account_inactive"
	CodeIdentityDemoSession                              = "identity.demo_session"
	CodeIdentityInvitationAccountLoginRequired           = "identity.invitation_account_login_required"
	CodeIdentityInvitationAccountMismatch                = "identity.invitation_account_mismatch"
	CodeIdentityPreviewTargetNotPreviewable              = "identity.preview_target_not_previewable"
	CodeIdentityPreviewTargetSchoolPortal                = "identity.preview_target_school_portal"
	CodeIdentityPreviewTokenInvalid                      = "identity.preview_token_invalid"
	CodeIdentityReadOnlyPreview                          = "identity.read_only_preview"
	CodeIdentitySessionAccountInactive                   = "identity.session_account_inactive"
	CodeIdentityUseParentPortal                          = "identity.use_parent_portal"
	CodeIdentityUseSchoolPortal                          = "identity.use_school_portal"
	CodeImportImportBatchFailed                          = "import.import_batch_failed"
	CodeIotActivityCapacityExceeded                      = "iot.activity_capacity_exceeded"
	CodeIotDeviationReasonRequired                       = "iot.deviation_reason_required"
	CodeIotInvalidRfidTag                                = "iot.invalid_rfid_tag"
	CodeIotInvalidStaffClockRequest                      = "iot.invalid_staff_clock_request"
	CodeIotInvalidStaffClockState                        = "iot.invalid_staff_clock_state"
	CodeIotOpenRoomBinaryMode                            = "iot.open_room_binary_mode"
	CodeIotPlannedStartNotReached                        = "iot.planned_start_not_reached"
	CodeIotRfidTagInactive                               = "iot.rfid_tag_inactive"
	CodeIotRfidTagNotFound                               = "iot.rfid_tag_not_found"
	CodeIotRfidTagNotStaff                               = "iot.rfid_tag_not_staff"
	CodeIotRoomCapacityExceeded                          = "iot.room_capacity_exceeded"
	CodeIotRoomNotFound                                  = "iot.room_not_found"
	CodeIotStudentAlreadyActive                          = "iot.student_already_active"
	CodeIotStudentNotPresent                             = "iot.student_not_present"
	CodeMealsInvalidDishes                               = "meals.invalid_dishes"
	CodeMealsInvalidMealDate                             = "meals.invalid_meal_date"
	CodeMealsInvalidParticipation                        = "meals.invalid_participation"
	CodeMealsParticipationCutoffPassed                   = "meals.participation_cutoff_passed"
	CodeMealsParticipationOutOfRange                     = "meals.participation_out_of_range"
	CodeMealsPlanDisabled                                = "meals.plan_disabled"
	CodeMealsPlanWeekOutOfRange                          = "meals.plan_week_out_of_range"
	CodeMealsRegistrationDisabled                        = "meals.registration_disabled"
	CodePickupBulkExceptionConfirmationRequired          = "pickup.bulk_exception_confirmation_required"
	CodePickupFutureManualReset                          = "pickup.future_manual_reset"
	CodePickupInvalid                                    = "pickup.invalid"
	CodePickupOfferingCapacityFull                       = "pickup.offering_capacity_full"
	CodePickupOfferingsDisabled                          = "pickup.offerings_disabled"
	CodePickupPreviewStale                               = "pickup.preview_stale"
	CodePickupResolutionRequired                         = "pickup.resolution_required"
	CodePresenceActivityParticipantLimitReached          = "presence.activity_participant_limit_reached"
	CodePresenceRoomCapacityExceeded                     = "presence.room_capacity_exceeded"
	CodeRolloverDuplicateName                            = "rollover.duplicate_name"
	CodeRolloverInvalidRequest                           = "rollover.invalid_request"
	CodeRolloverReviewInvalid                            = "rollover.review_invalid"
	CodeRolloverReviewNotFound                           = "rollover.review_not_found"
	CodeRolloverSourceAlreadyRolled                      = "rollover.source_already_rolled"
	CodeRolloverSourceNotFound                           = "rollover.source_not_found"
	CodeRoomsNotReleased                                 = "rooms.not_released"
	CodeSchoolNoSchoolPortalRole                         = "school.no_school_portal_role"
	CodeStudentsAbsenceReadRequired                      = "students.absence_read_required"
	CodeStudentsBulkApprovalIneligible                   = "students.bulk_approval_ineligible"
	CodeStudentsCareDayManagedByBooking                  = "students.care_day_managed_by_booking"
	CodeStudentsCareExceptionRaced                       = "students.care_exception_raced"
	CodeStudentsCareOfferingsDisabled                    = "students.care_offerings_disabled"
	CodeStudentsCareWithdrawalAlreadyResolved            = "students.care_withdrawal_already_resolved"
	CodeStudentsCareWithdrawalNotFound                   = "students.care_withdrawal_not_found"
	CodeStudentsChangeRequestNotPending                  = "students.change_request_not_pending"
	CodeStudentsChangeRequestStale                       = "students.change_request_stale"
	CodeStudentsCompanionLockBusy                        = "students.companion_lock_busy"
	CodeStudentsCompanionWouldLoseDeparture              = "students.companion_would_lose_departure"
	CodeStudentsCompanionsChanged                        = "students.companions_changed"
	CodeStudentsConflictKindUnsupported                  = "students.conflict_kind_unsupported"
	CodeStudentsCorrectionUnsupported                    = "students.correction_unsupported"
	CodeStudentsDeletionAcknowledgementRequired          = "students.deletion_acknowledgement_required"
	CodeStudentsDeletionAlumnus                          = "students.deletion_alumnus"
	CodeStudentsDeletionCompanionBlocked                 = "students.deletion_companion_blocked"
	CodeStudentsDeletionCompanionLockBusy                = "students.deletion_companion_lock_busy"
	CodeStudentsDeletionConfirmationMismatch             = "students.deletion_confirmation_mismatch"
	CodeStudentsDeletionConstraintsChanged               = "students.deletion_constraints_changed"
	CodeStudentsDeletionInvalidReason                    = "students.deletion_invalid_reason"
	CodeStudentsDeletionPreviewChanged                   = "students.deletion_preview_changed"
	CodeStudentsDeletionRetentionNotEnded                = "students.deletion_retention_not_ended"
	CodeStudentsExcusedRequestStatusConflict             = "students.excused_request_status_conflict"
	CodeStudentsGuardianAccessRevoked                    = "students.guardian_access_revoked"
	CodeStudentsOfferingChangeCapacityFull               = "students.offering_change_capacity_full"
	CodeStudentsOfferingChangeDateOutOfRange             = "students.offering_change_date_out_of_range"
	CodeStudentsOfferingChangesNoEnrollment              = "students.offering_changes_no_enrollment"
	CodeStudentsPartialAbsenceConflict                   = "students.partial_absence_conflict"
	CodeStudentsPartialAbsenceRequiresDedicatedAction    = "students.partial_absence_requires_dedicated_action"
	CodeStudentsPickupChangeCompleted                    = "students.pickup_change_completed"
	CodeStudentsPickupChangeConflict                     = "students.pickup_change_conflict"
	CodeStudentsPickupChangeExpired                      = "students.pickup_change_expired"
	CodeStudentsPickupChangeImpactChanged                = "students.pickup_change_impact_changed"
	CodeStudentsPickupResetRequiresOffering              = "students.pickup_reset_requires_offering"
	CodeStudentsReasonRequired                           = "students.reason_required"
	CodeStudentsRequestNotDecided                        = "students.request_not_decided"
	CodeStudentsRequestNotPast                           = "students.request_not_past"
	CodeStudentsRequestPast                              = "students.request_past"
	CodeStudentsSickExcusedConflict                      = "students.sick_excused_conflict"
	CodeStudentsStaffProfileRequired                     = "students.staff_profile_required"
	CodeStudentsStaffValueInvalid                        = "students.staff_value_invalid"
	CodeStudentsStaffValueUnsupported                    = "students.staff_value_unsupported"
	CodeSubstitutionsAlreadyAssigned                     = "substitutions.already_assigned"
	CodeSubstitutionsConflict                            = "substitutions.conflict"
	CodeSubstitutionsForbidden                           = "substitutions.forbidden"
	CodeSubstitutionsInternal                            = "substitutions.internal"
	CodeSubstitutionsInvalidPeriod                       = "substitutions.invalid_period"
	CodeSubstitutionsInvalidTarget                       = "substitutions.invalid_target"
	CodeSubstitutionsNotFound                            = "substitutions.not_found"
	CodeSubstitutionsNotRunning                          = "substitutions.not_running"
	CodeSubstitutionsSelfAssignment                      = "substitutions.self_assignment"
	CodeTimetableCalendarPeriodCareOfferingConflict      = "timetable.calendar_period_care_offering_conflict"
	CodeTimetableCalendarPeriodOverlapConflict           = "timetable.calendar_period_overlap_conflict"
	CodeTimetableCompletionConfirmationStale             = "timetable.completion_confirmation_stale"
	CodeTimetableInstanceNotConvertible                  = "timetable.instance_not_convertible"
	CodeTimetableOnlySupervisorReplacementRequired       = "timetable.only_supervisor_replacement_required"
	CodeTimetablePickupExtensionBlockGone                = "timetable.pickup_extension_block_gone"
	CodeTimetablePickupExtensionNotFound                 = "timetable.pickup_extension_not_found"
	CodeTimetableTemplateCareOfferingConflict            = "timetable.template_care_offering_conflict"
	CodeTimetableTemplateNotFound                        = "timetable.template_not_found"
	CodeTimetableTemplateRosterRebaseConflict            = "timetable.template_roster_rebase_conflict"
	CodeTimetableTemplateStartInPast                     = "timetable.template_start_in_past"
	CodeTimetableTemplateStartNotEarlier                 = "timetable.template_start_not_earlier"
	CodeTimetableTemplateStartPredecessorOverlap         = "timetable.template_start_predecessor_overlap"
	CodeWorkforceAbsenceAllowanceExceeded                = "workforce.absence_allowance_exceeded"
	CodeWorkforceAbsenceRebookingBlocked                 = "workforce.absence_rebooking_blocked"
	CodeWorkforceAbsenceTypeInactive                     = "workforce.absence_type_inactive"
	CodeWorkforceAdjustmentInClosedMonth                 = "workforce.adjustment_in_closed_month"
	CodeWorkforceBalanceAdjustmentExceedsBalance         = "workforce.balance_adjustment_exceeds_balance"
	CodeWorkforceBalanceAlreadyReset                     = "workforce.balance_already_reset"
	CodeWorkforceDependentBalanceReset                   = "workforce.dependent_balance_reset"
	CodeWorkforceLaterMonthClosed                        = "workforce.later_month_closed"
	CodeWorkforceManagerControlledAbsence                = "workforce.manager_controlled_absence"
	CodeWorkforceMonthNotClosable                        = "workforce.month_not_closable"
	CodeWorkforceMonthNotClosed                          = "workforce.month_not_closed"
	CodeWorkforceOpeningBalanceAlreadyExists             = "workforce.opening_balance_already_exists"
	CodeWorkforcePayrollConfigIncomplete                 = "workforce.payroll_config_incomplete"
	CodeWorkforcePersonnelNumberInvalid                  = "workforce.personnel_number_invalid"
	CodeWorkforcePersonnelNumberTaken                    = "workforce.personnel_number_taken"
	CodeWorkforceStammdatenInvalid                       = "workforce.stammdaten_invalid"
	CodeWorkforceVacationOpeningAbsencesBeforeCutoff     = "workforce.vacation_opening_absences_before_cutoff"
	CodeWorkforceVacationOpeningAlreadyExists            = "workforce.vacation_opening_already_exists"
	CodeWorkforceVacationQuotaBelowUsed                  = "workforce.vacation_quota_below_used"
	CodeWorkforceVacationQuotaExceeded                   = "workforce.vacation_quota_exceeded"
	CodeWorkforceVacationQuotaReasonRequired             = "workforce.vacation_quota_reason_required"
	CodeWorkforceWorkSessionOverlap                      = "workforce.work_session_overlap"
)

var errorClassByWireCode = map[string]string{
	"announcement_ack_not_required":                        "input",
	"announcement_not_a_poll":                              "input",
	"announcement_stale":                                   "business_rejection",
	"cannot_remove_own_access":                             "permission",
	"care_exception_already_left":                          "business_rejection",
	"care_exception_conflict":                              "business_rejection",
	"care_exception_no_time":                               "input",
	"care_exception_past_date":                             "input",
	"care_exception_reason_required":                       "input",
	"care_exception_reason_too_long":                       "input",
	"care_exception_too_far":                               "input",
	"care_request_already_pending":                         "business_rejection",
	"care_request_bookings_authoritative":                  "permission",
	"care_request_field_disabled":                          "permission",
	"child_care_ended":                                     "permission",
	"child_not_linked":                                     "permission",
	"course_already_booked":                                "input",
	"course_request_invalid":                               "input",
	"course_request_not_own":                               "input",
	"course_requests_disabled":                             "permission",
	"excused_request_not_pending":                          "business_rejection",
	"excused_request_overlap":                              "business_rejection",
	"family_protection":                                    "permission",
	"guardian_contact_invalid":                             "input",
	"guardian_email_conflict":                              "business_rejection",
	"guardian_has_own_account":                             "permission",
	"guardian_management_disabled":                         "permission",
	"guardian_no_change":                                   "input",
	"guardian_not_linked":                                  "permission",
	"guardian_permission_denied":                           "permission",
	"guardian_relationship_invalid":                        "input",
	"guardian_role_managed":                                "permission",
	"guardian_shared_across_families":                      "permission",
	"guardian_social_worker_managed":                       "permission",
	"invalid_credentials":                                  "permission",
	"invalid_poll_response":                                "input",
	"invalid_recipients":                                   "input",
	"invalid_request_payload":                              "input",
	"invite_disabled":                                      "permission",
	"master_data_duplicate_pending":                        "business_rejection",
	"master_data_edit_disabled":                            "permission",
	"master_data_field_not_editable":                       "permission",
	"master_data_invalid_value":                            "input",
	"master_data_no_changes":                               "input",
	"master_data_request_disabled":                         "permission",
	"not_a_guardian":                                       "permission",
	"notes_disabled":                                       "permission",
	"offering_change_already_pending":                      "business_rejection",
	"offering_change_forbidden":                            "permission",
	"offering_change_invalid":                              "input",
	"offering_changes_disabled":                            "permission",
	"payer_guardian_protected":                             "permission",
	"photo_consent_not_withdrawn":                          "business_rejection",
	"pickup_change_cutoff_passed":                          "business_rejection",
	"pickup_change_disabled":                               "permission",
	"poll_closed":                                          "business_rejection",
	"primary_guardian_protected":                           "permission",
	"remove_disabled":                                      "permission",
	"request_not_found":                                    "business_rejection",
	"request_not_open":                                     "business_rejection",
	"request_sharing_invalid":                              "input",
	"sick_note_disabled":                                   "permission",
	"staff_managed_guardian_protected":                     "permission",
	"class_arrival_exception_class_not_found":              "business_rejection",
	"class_arrival_exception_editor_required":              "permission",
	"class_arrival_exception_past_date":                    "input",
	"class_arrival_exception_weekend":                      "input",
	"school_write_disabled":                                "permission",
	"announcement_not_published":                           "business_rejection",
	"announcement_published_immutable":                     "business_rejection",
	"announcement_reminder_sent":                           "business_rejection",
	"parent_news_disabled":                                 "permission",
	"poll_not_open":                                        "business_rejection",
	"staff_counterpart_unavailable":                        "unavailable",
	"staff_messaging_disabled":                             "permission",
	"system_announcement_immutable":                        "business_rejection",
	"enrollment.approval_care_offering_exactly_one":        "business_rejection",
	"enrollment.approval_care_offering_missing":            "business_rejection",
	"enrollment.care_offering_days_required":               "input",
	"enrollment.care_offering_exactly_one":                 "input",
	"enrollment.care_offering_full":                        "business_rejection",
	"enrollment.care_offering_in_use":                      "business_rejection",
	"enrollment.care_offering_missing":                     "input",
	"enrollment.care_offering_pickup_times_required":       "input",
	"enrollment.care_offering_template_period_mismatch":    "input",
	"enrollment.care_offering_unavailable":                 "business_rejection",
	"enrollment.care_offerings_disabled":                   "permission",
	"enrollment.change_request_child_locked":               "permission",
	"enrollment.change_request_conflict":                   "business_rejection",
	"enrollment.child_already_enrolled":                    "business_rejection",
	"enrollment.child_ambiguous":                           "input",
	"enrollment.child_deletion_not_allowed":                "business_rejection",
	"enrollment.child_not_enrolled":                        "business_rejection",
	"enrollment.child_not_permitted":                       "permission",
	"enrollment.class_not_eligible":                        "input",
	"enrollment.complete_withdrawal_confirmation_required": "input",
	"enrollment.day_selection_not_allowed":                 "input",
	"enrollment.day_selection_required":                    "input",
	"enrollment.departure_mode_limit":                      "input",
	"enrollment.disabled":                                  "business_rejection",
	"enrollment.duplicate_detected":                        "business_rejection",
	"enrollment.grade_not_eligible":                        "input",
	"enrollment.guardian_account_mismatch":                 "business_rejection",
	"enrollment.invalid_email":                             "input",
	"enrollment.invalid_phone":                             "input",
	"enrollment.late_invite_invalid":                       "input",
	"enrollment.phase_care_offering_conflict":              "business_rejection",
	"enrollment.phase_name_exists":                         "business_rejection",
	"enrollment.phase_not_eligible":                        "permission",
	"enrollment.pickup_time_not_allowed":                   "input",
	"enrollment.required_care_offering_missing":            "input",
	"enrollment.restore_duplicate":                         "business_rejection",
	"enrollment.restore_offering_closed":                   "business_rejection",
	"enrollment.restore_phase_inactive":                    "business_rejection",
	"enrollment.schema_has_phases":                         "business_rejection",
	"enrollment.schema_has_requests":                       "business_rejection",
	"enrollment.schema_name_exists":                        "business_rejection",
	"enrollment.selected_day_not_available":                "input",
	"enrollment.student_exists":                            "business_rejection",
	"enrollment.waitlist_disabled":                         "business_rejection",
	"enrollment.window_closed":                             "business_rejection",
	"announcement_published":                               "business_rejection",
	"attachment_limit_reached":                             "business_rejection",
	"folder_name_taken":                                    "business_rejection",
	"quota_exceeded":                                       "business_rejection",
	"general.business_rejection":                           "business_rejection",
	"general.input":                                        "input",
	"general.permission":                                   "permission",
	"general.server":                                       "server",
	"general.unavailable":                                  "unavailable",
	"graduates_checked_in":                                 "business_rejection",
	"not_applied":                                          "business_rejection",
	"not_draft":                                            "business_rejection",
	"not_latest_transition":                                "business_rejection",
	"preview_stale":                                        "business_rejection",
	"ACCOUNT_ALREADY_HAS_TENANT_ACCESS":                    "business_rejection",
	"ACCOUNT_INACTIVE":                                     "permission",
	"demo_session":                                         "permission",
	"INVITATION_ACCOUNT_LOGIN_REQUIRED":                    "permission",
	"INVITATION_ACCOUNT_MISMATCH":                          "permission",
	"preview_target_not_previewable":                       "permission",
	"preview_target_school_portal":                         "permission",
	"preview_token_invalid":                                "permission",
	"read_only_preview":                                    "permission",
	"account_inactive":                                     "permission",
	"use_parent_portal":                                    "permission",
	"use_school_portal":                                    "permission",
	"import_batch_failed":                                  "server",
	"ACTIVITY_CAPACITY_EXCEEDED":                           "business_rejection",
	"deviation_reason_required":                            "input",
	"invalid_rfid_tag":                                     "input",
	"invalid_staff_clock_request":                          "input",
	"invalid_staff_clock_state":                            "business_rejection",
	"open_room_binary_mode":                                "business_rejection",
	"planned_start_not_reached":                            "business_rejection",
	"rfid_tag_inactive":                                    "business_rejection",
	"rfid_tag_not_found":                                   "business_rejection",
	"rfid_tag_not_staff":                                   "business_rejection",
	"ROOM_CAPACITY_EXCEEDED":                               "business_rejection",
	"room_not_found":                                       "business_rejection",
	"STUDENT_ALREADY_ACTIVE":                               "business_rejection",
	"student_not_present":                                  "business_rejection",
	"invalid_dishes":                                       "input",
	"invalid_meal_date":                                    "input",
	"invalid_meal_participation":                           "input",
	"meal_participation_cutoff_passed":                     "business_rejection",
	"meal_participation_out_of_range":                      "input",
	"meal_plan_disabled":                                   "permission",
	"meal_plan_week_out_of_range":                          "input",
	"meal_registration_disabled":                           "permission",
	"pickup.bulk_exception_confirmation_required":          "input",
	"pickup.future_manual_reset":                           "business_rejection",
	"pickup.invalid":                                       "input",
	"pickup.offering_capacity_full":                        "business_rejection",
	"pickup.offerings_disabled":                            "business_rejection",
	"pickup.preview_stale":                                 "business_rejection",
	"pickup.resolution_required":                           "input",
	"presence.activity_participant_limit_reached":          "business_rejection",
	"presence.room_capacity_exceeded":                      "business_rejection",
	"rollover.duplicate_name":                              "business_rejection",
	"rollover.invalid_request":                             "input",
	"rollover.review_invalid":                              "input",
	"rollover.review_not_found":                            "business_rejection",
	"rollover.source_already_rolled":                       "business_rejection",
	"rollover.source_not_found":                            "business_rejection",
	"room_not_released":                                    "business_rejection",
	"no_school_portal_role":                                "permission",
	"absence_read_required":                                "permission",
	"bulk_approval_ineligible":                             "business_rejection",
	"care_day_managed_by_booking":                          "business_rejection",
	"care_exception_raced":                                 "business_rejection",
	"care_offerings_disabled":                              "permission",
	"students.care_withdrawal_already_resolved":            "business_rejection",
	"students.care_withdrawal_not_found":                   "business_rejection",
	"change_request_not_pending":                           "business_rejection",
	"change_request_stale":                                 "business_rejection",
	"companion_lock_busy":                                  "business_rejection",
	"companion_would_lose_departure":                       "input",
	"companions_changed":                                   "business_rejection",
	"conflict_kind_unsupported":                            "input",
	"correction_unsupported":                               "business_rejection",
	"students.deletion_acknowledgement_required":           "input",
	"students.deletion_alumnus":                            "business_rejection",
	"students.deletion_companion_blocked":                  "business_rejection",
	"students.deletion_companion_lock_busy":                "business_rejection",
	"students.deletion_confirmation_mismatch":              "input",
	"students.deletion_constraints_changed":                "business_rejection",
	"students.deletion_invalid_reason":                     "input",
	"students.deletion_preview_changed":                    "business_rejection",
	"students.deletion_retention_not_ended":                "business_rejection",
	"excused_request_status_conflict":                      "business_rejection",
	"guardian_access_revoked":                              "business_rejection",
	"offering_change_capacity_full":                        "business_rejection",
	"offering_change_date_out_of_range":                    "input",
	"offering_changes_no_enrollment":                       "permission",
	"partial_absence_conflict":                             "business_rejection",
	"partial_absence_requires_dedicated_action":            "business_rejection",
	"pickup_change_completed":                              "business_rejection",
	"pickup_change_conflict":                               "business_rejection",
	"pickup_change_expired":                                "business_rejection",
	"pickup_change_impact_changed":                         "business_rejection",
	"pickup_reset_requires_offering":                       "business_rejection",
	"reason_required":                                      "input",
	"request_not_decided":                                  "business_rejection",
	"request_not_past":                                     "business_rejection",
	"request_past":                                         "business_rejection",
	"SICK_EXCUSED_CONFLICT":                                "business_rejection",
	"staff_profile_required":                               "permission",
	"staff_value_invalid":                                  "input",
	"staff_value_unsupported":                              "input",
	"already_assigned":                                     "business_rejection",
	"conflict":                                             "business_rejection",
	"forbidden":                                            "permission",
	"internal":                                             "server",
	"invalid_period":                                       "input",
	"invalid_target":                                       "input",
	"not_found":                                            "business_rejection",
	"not_running":                                          "business_rejection",
	"self_assignment":                                      "input",
	"calendar_period_care_offering_conflict":               "business_rejection",
	"calendar_period_overlap_conflict":                     "business_rejection",
	"completion_confirmation_stale":                        "business_rejection",
	"instance_not_convertible":                             "business_rejection",
	"ONLY_SUPERVISOR_REPLACEMENT_REQUIRED":                 "business_rejection",
	"pickup_extension_block_gone":                          "business_rejection",
	"pickup_extension_not_found":                           "business_rejection",
	"timetable.template_care_offering_conflict":            "input",
	"template_not_found":                                   "business_rejection",
	"timetable.template_roster_rebase_conflict":            "business_rejection",
	"timetable.template_start_in_past":                     "input",
	"timetable.template_start_not_earlier":                 "input",
	"timetable.template_start_predecessor_overlap":         "input",
	"absence_allowance_exceeded":                           "business_rejection",
	"absence_rebooking_blocked":                            "business_rejection",
	"absence_type_inactive":                                "business_rejection",
	"adjustment_in_closed_month":                           "input",
	"balance_adjustment_exceeds_balance":                   "business_rejection",
	"balance_already_reset":                                "business_rejection",
	"dependent_balance_reset":                              "business_rejection",
	"later_month_closed":                                   "business_rejection",
	"manager_controlled_absence":                           "permission",
	"month_not_closable":                                   "input",
	"month_not_closed":                                     "business_rejection",
	"opening_balance_already_exists":                       "business_rejection",
	"payroll_config_incomplete":                            "business_rejection",
	"personnel_number_invalid":                             "input",
	"personnel_number_taken":                               "business_rejection",
	"stammdaten_invalid":                                   "input",
	"vacation_opening_absences_before_cutoff":              "business_rejection",
	"vacation_opening_already_exists":                      "business_rejection",
	"vacation_quota_below_used":                            "business_rejection",
	"vacation_quota_exceeded":                              "business_rejection",
	"vacation_quota_reason_required":                       "input",
	"work_session_overlap":                                 "business_rejection",
}
