// Code generated by scripts/verify-error-catalog.mjs --write; DO NOT EDIT.
export const ERROR_CATALOG = {
  de: {
    classes: {
      input:
        "{object} konnte nicht übernommen werden. Bitte prüfen Sie Ihre Angaben.",
      permission:
        "Für {object} fehlt Ihnen die Berechtigung. Bitte fragen Sie die Schule.",
      business_rejection:
        "{object} konnte nicht geändert werden. Bitte prüfen Sie den aktuellen Stand.",
      unavailable:
        "{object} ist gerade nicht erreichbar. Bitte versuchen Sie es erneut.",
      server:
        "{object} konnte nicht bearbeitet werden. Bitte versuchen Sie es später erneut.",
    },
    actions: {
      retry: "Wiederholen",
      copyRequestId: "Vorgangskennung kopieren",
      requestId: "Vorgangskennung: {requestId}",
      crash:
        "{object} konnte nicht bearbeitet werden. Bitte versuchen Sie es später erneut.",
      fieldCheck: "Bitte prüfen Sie dieses Feld.",
    },
    codes: {
      "care.announcement_stale":
        "Der Stand von {object} hat sich geändert. Bitte laden Sie die Seite neu.",
      "care.care_exception_conflict":
        "Der Stand von {object} hat sich geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "care.care_exception_past_date":
        "Das Datum für {object} liegt in der Vergangenheit. Bitte wählen Sie ein anderes Datum.",
      "care.care_exception_reason_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "care.care_request_already_pending":
        "Für {object} gibt es bereits eine Anfrage. Bitte prüfen Sie den aktuellen Stand.",
      "care.care_request_field_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.course_request_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.course_requests_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.excused_request_not_pending":
        "{object} ist nicht mehr offen. Bitte laden Sie die Seite neu.",
      "care.excused_request_overlap":
        "Die Zeiten für {object} überschneiden sich. Bitte prüfen Sie die Angaben.",
      "care.guardian_contact_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.guardian_email_conflict":
        "Diese E-Mail-Adresse wird bereits verwendet. Bitte prüfen Sie die Adresse.",
      "care.guardian_management_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.guardian_relationship_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.invalid_poll_response":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.invalid_recipients":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.invalid_request_payload":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.invite_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.master_data_edit_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.master_data_invalid_value":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.master_data_no_changes":
        "Für {object} wurde nichts geändert. Bitte prüfen Sie Ihre Angaben.",
      "care.master_data_request_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.notes_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.offering_change_already_pending":
        "Für {object} gibt es bereits eine Anfrage. Bitte prüfen Sie den aktuellen Stand.",
      "care.offering_change_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.offering_changes_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.pickup_change_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.poll_closed":
        "{object} ist nicht mehr geöffnet. Bitte fragen Sie Ihre Ansprechperson.",
      "care.remove_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.request_not_found":
        "{object} wurde nicht gefunden. Bitte laden Sie die Seite neu.",
      "care.request_not_open":
        "{object} ist nicht mehr geöffnet. Bitte fragen Sie Ihre Ansprechperson.",
      "care.request_sharing_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.sick_note_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "classday.arrival_exception_class_not_found":
        "{object} wurde nicht gefunden. Bitte laden Sie die Seite neu.",
      "classday.arrival_exception_editor_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "classday.arrival_exception_past_date":
        "Das Datum für {object} liegt in der Vergangenheit. Bitte wählen Sie ein anderes Datum.",
      "classday.school_write_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "communication.parent_news_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "communication.poll_not_open":
        "{object} ist nicht mehr geöffnet. Bitte fragen Sie Ihre Ansprechperson.",
      "communication.staff_messaging_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "enrollment.approval_care_offering_missing":
        "Für {object} fehlt ein Betreuungsangebot. Bitte wählen Sie eines aus.",
      "enrollment.care_offering_days_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "enrollment.care_offering_in_use":
        "{object} wird bereits verwendet. Bitte prüfen Sie den aktuellen Stand.",
      "enrollment.care_offering_missing":
        "Für {object} fehlt ein Betreuungsangebot. Bitte wählen Sie eines aus.",
      "enrollment.care_offering_pickup_times_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "enrollment.care_offerings_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "enrollment.change_request_conflict":
        "Der Stand von {object} hat sich geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "enrollment.class_not_eligible":
        "{object} erfüllt die Voraussetzungen nicht. Bitte fragen Sie Ihre Ansprechperson.",
      "enrollment.complete_withdrawal_confirmation_required":
        "{object} kann noch nicht abgemeldet werden. Bitte bestätigen Sie mit {confirmation}.",
      "enrollment.day_selection_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "enrollment.grade_not_eligible":
        "{object} erfüllt die Voraussetzungen nicht. Bitte fragen Sie Ihre Ansprechperson.",
      "enrollment.invalid_email":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "enrollment.invalid_phone":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "enrollment.late_invite_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "enrollment.phase_care_offering_conflict":
        "Der Stand von {object} hat sich geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "enrollment.phase_name_exists":
        "{object} gibt es bereits. Bitte wählen Sie eine andere Angabe.",
      "enrollment.phase_not_eligible":
        "{object} erfüllt die Voraussetzungen nicht. Bitte fragen Sie Ihre Ansprechperson.",
      "enrollment.required_care_offering_missing":
        "Für {object} fehlt ein Betreuungsangebot. Bitte wählen Sie eines aus.",
      "enrollment.restore_duplicate":
        "{object} gibt es bereits. Bitte wählen Sie eine andere Angabe.",
      "enrollment.restore_offering_closed":
        "{object} ist nicht mehr geöffnet. Bitte fragen Sie Ihre Ansprechperson.",
      "enrollment.schema_name_exists":
        "{object} gibt es bereits. Bitte wählen Sie eine andere Angabe.",
      "enrollment.student_exists":
        "{object} gibt es bereits. Bitte wählen Sie eine andere Angabe.",
      "enrollment.waitlist_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "enrollment.window_closed":
        "{object} ist nicht mehr geöffnet. Bitte fragen Sie Ihre Ansprechperson.",
      "files.attachment_limit_reached":
        "Für {object} sind zu viele Dateien ausgewählt. Bitte entfernen Sie einen Anhang.",
      "files.folder_name_taken":
        "{object} gibt es bereits. Bitte wählen Sie eine andere Angabe.",
      "grade_transition.preview_stale":
        "Der Stand von {object} hat sich geändert. Bitte laden Sie die Seite neu.",
      "identity.invitation_account_login_required":
        "Für {object} müssen Sie angemeldet sein. Bitte melden Sie sich an.",
      "identity.preview_token_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "iot.activity_capacity_exceeded":
        "Im Angebot {activity_name} ist kein Platz mehr. Bitte wählen Sie ein anderes Angebot.",
      "iot.deviation_reason_required":
        "{object} weicht vom Plan ab. Bitte geben Sie einen Grund an.",
      "iot.invalid_staff_clock_request":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "iot.invalid_staff_clock_state":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "iot.planned_start_not_reached":
        "{object} kann noch nicht beginnen. Bitte warten Sie bis {planned_start_time} Uhr.",
      "iot.room_capacity_exceeded":
        "Im Raum {room_name} ist kein Platz mehr. Bitte wählen Sie einen anderen Raum.",
      "iot.student_already_active":
        "{object} ist bereits im Raum {room_name}. Bitte prüfen Sie den aktuellen Aufenthalt.",
      "meals.invalid_dishes":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "meals.invalid_meal_date":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "meals.invalid_participation":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "meals.plan_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "meals.registration_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "pickup.bulk_exception_confirmation_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "pickup.invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "pickup.offering_capacity_full":
        "Für {object} ist kein Platz mehr frei. Bitte wählen Sie etwas anderes.",
      "pickup.offerings_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "pickup.preview_stale":
        "Der Stand von {object} hat sich geändert. Bitte laden Sie die Seite neu.",
      "pickup.resolution_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "presence.activity_participant_limit_reached":
        "Im Angebot {activity_name} ist kein Platz mehr. Bitte wählen Sie ein anderes Angebot.",
      "presence.room_capacity_exceeded":
        "Der Raum {room_name} ist voll ({current_occupancy} von {max_capacity} Plätzen).",
      "rollover.invalid_request":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "rollover.review_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "students.absence_read_required":
        "Für {object} fehlt die Bestätigung. Bitte bestätigen Sie den Hinweis.",
      "students.care_exception_raced":
        "Der Stand von {object} hat sich geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "students.care_offerings_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "students.care_withdrawal_not_found":
        "{object} wurde nicht gefunden. Bitte laden Sie die Seite neu.",
      "students.change_request_not_pending":
        "{object} ist nicht mehr offen. Bitte laden Sie die Seite neu.",
      "students.change_request_stale":
        "Der Stand von {object} hat sich geändert. Bitte laden Sie die Seite neu.",
      "students.companions_changed":
        "Der Stand von {object} hat sich geändert. Bitte laden Sie die Seite neu.",
      "students.deletion_acknowledgement_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "students.deletion_constraints_changed":
        "Der Stand von {object} hat sich geändert. Bitte laden Sie die Seite neu.",
      "students.deletion_invalid_reason":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "students.deletion_preview_changed":
        "Der Stand von {object} hat sich geändert. Bitte laden Sie die Seite neu.",
      "students.excused_request_status_conflict":
        "Der Stand von {object} hat sich geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "students.offering_change_capacity_full":
        "Für {object} ist kein Platz mehr frei. Bitte wählen Sie etwas anderes.",
      "students.partial_absence_conflict":
        "Der Stand von {object} hat sich geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "students.pickup_change_conflict":
        "Der Stand von {object} hat sich geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "students.pickup_change_expired":
        "{object} ist abgelaufen. Bitte beginnen Sie erneut.",
      "students.pickup_change_impact_changed":
        "Der Stand von {object} hat sich geändert. Bitte laden Sie die Seite neu.",
      "students.reason_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "students.sick_excused_conflict":
        "Der Stand von {object} hat sich geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "students.staff_profile_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "students.staff_value_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "substitutions.invalid_period":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "substitutions.invalid_target":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "timetable.calendar_period_care_offering_conflict":
        "Der Stand von {object} hat sich geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "timetable.calendar_period_overlap_conflict":
        "{object} überschneidet sich mit anderen Zeiträumen. Bitte prüfen Sie die Termine.",
      "timetable.completion_confirmation_stale":
        "Der Stand von {object} hat sich geändert. Bitte laden Sie die Seite neu.",
      "timetable.only_supervisor_replacement_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "timetable.pickup_extension_not_found":
        "{object} wurde nicht gefunden. Bitte laden Sie die Seite neu.",
      "timetable.template_care_offering_conflict":
        "Der Stand von {object} hat sich geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "timetable.template_roster_rebase_conflict":
        "Der Stand von {object} hat sich geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "timetable.template_start_in_past":
        "Das Datum für {object} liegt in der Vergangenheit. Bitte wählen Sie ein anderes Datum.",
      "timetable.template_start_predecessor_overlap":
        "Die Zeiten für {object} überschneiden sich. Bitte prüfen Sie die Angaben.",
      "workforce.later_month_closed":
        "{object} ist nicht mehr geöffnet. Bitte fragen Sie Ihre Ansprechperson.",
      "workforce.month_not_closed":
        "Der Monat für {object} ist noch offen. Bitte schließen Sie ihn zuerst ab.",
      "workforce.opening_balance_already_exists":
        "{object} gibt es bereits. Bitte wählen Sie eine andere Angabe.",
      "workforce.personnel_number_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "workforce.personnel_number_taken":
        "{object} gibt es bereits. Bitte wählen Sie eine andere Angabe.",
      "workforce.stammdaten_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "workforce.vacation_opening_already_exists":
        "{object} gibt es bereits. Bitte wählen Sie eine andere Angabe.",
      "workforce.vacation_quota_reason_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "workforce.work_session_overlap":
        "Die Zeiten für {object} überschneiden sich. Bitte prüfen Sie die Angaben.",
    },
  },
  en: {
    classes: {
      input: "{object} could not be saved. Please check your entries.",
      permission: "You cannot access {object}. Please contact the school.",
      business_rejection:
        "{object} could not be changed. Please check its current status.",
      unavailable: "{object} is unavailable right now. Please try again.",
      server: "{object} could not be processed. Please try again later.",
    },
    actions: {
      retry: "Try again",
      copyRequestId: "Copy request ID",
      requestId: "Request ID: {requestId}",
      crash: "{object} could not be processed. Please try again later.",
      fieldCheck: "Please check this field.",
    },
    codes: {},
  },
  ru: {
    classes: {
      input: "Не удалось сохранить: {object}. Проверьте введённые данные.",
      permission: "У вас нет доступа к: {object}. Обратитесь в школу.",
      business_rejection:
        "Не удалось изменить: {object}. Проверьте текущее состояние.",
      unavailable: "{object} сейчас недоступен. Повторите попытку.",
      server: "Не удалось обработать: {object}. Повторите попытку позже.",
    },
    actions: {
      retry: "Повторить",
      copyRequestId: "Скопировать номер запроса",
      requestId: "Номер запроса: {requestId}",
      crash: "Не удалось обработать: {object}. Повторите попытку позже.",
      fieldCheck: "Проверьте это поле.",
    },
    codes: {},
  },
  sq: {
    classes: {
      input: "Nuk u ruajt: {object}. Kontrolloni të dhënat.",
      permission: "Nuk keni qasje te: {object}. Kontaktoni shkollën.",
      business_rejection:
        "Nuk u ndryshua: {object}. Kontrolloni gjendjen aktuale.",
      unavailable: "{object} nuk është i disponueshëm tani. Provoni përsëri.",
      server: "Nuk u përpunua: {object}. Provoni përsëri më vonë.",
    },
    actions: {
      retry: "Provo përsëri",
      copyRequestId: "Kopjo numrin e kërkesës",
      requestId: "Numri i kërkesës: {requestId}",
      crash: "Nuk u përpunua: {object}. Provoni përsëri më vonë.",
      fieldCheck: "Kontrolloni këtë fushë.",
    },
    codes: {},
  },
  pl: {
    classes: {
      input: "Nie udało się zapisać: {object}. Sprawdź wpisane dane.",
      permission: "Nie masz dostępu do: {object}. Skontaktuj się ze szkołą.",
      business_rejection:
        "Nie udało się zmienić: {object}. Sprawdź aktualny stan.",
      unavailable: "{object} jest teraz niedostępne. Spróbuj ponownie.",
      server: "Nie udało się przetworzyć: {object}. Spróbuj ponownie później.",
    },
    actions: {
      retry: "Spróbuj ponownie",
      copyRequestId: "Kopiuj numer zgłoszenia",
      requestId: "Numer zgłoszenia: {requestId}",
      crash: "Nie udało się przetworzyć: {object}. Spróbuj ponownie później.",
      fieldCheck: "Sprawdź to pole.",
    },
    codes: {},
  },
  tr: {
    classes: {
      input: "{object} kaydedilemedi. Girdiğiniz bilgileri kontrol edin.",
      permission: "{object} için erişim izniniz yok. Okulla iletişime geçin.",
      business_rejection:
        "{object} değiştirilemedi. Güncel durumu kontrol edin.",
      unavailable: "{object} şu anda kullanılamıyor. Yeniden deneyin.",
      server: "{object} işlenemedi. Daha sonra yeniden deneyin.",
    },
    actions: {
      retry: "Yeniden dene",
      copyRequestId: "İstek numarasını kopyala",
      requestId: "İstek numarası: {requestId}",
      crash: "{object} işlenemedi. Daha sonra yeniden deneyin.",
      fieldCheck: "Bu alanı kontrol edin.",
    },
    codes: {},
  },
  uk: {
    classes: {
      input: "Не вдалося зберегти: {object}. Перевірте введені дані.",
      permission: "У вас немає доступу до: {object}. Зверніться до школи.",
      business_rejection:
        "Не вдалося змінити: {object}. Перевірте поточний стан.",
      unavailable: "{object} зараз недоступний. Спробуйте ще раз.",
      server: "Не вдалося обробити: {object}. Спробуйте пізніше.",
    },
    actions: {
      retry: "Спробувати ще раз",
      copyRequestId: "Скопіювати номер запиту",
      requestId: "Номер запиту: {requestId}",
      crash: "Не вдалося обробити: {object}. Спробуйте пізніше.",
      fieldCheck: "Перевірте це поле.",
    },
    codes: {},
  },
} as const;
