// Code generated by scripts/verify-error-catalog.mjs --write; DO NOT EDIT.
export const ERROR_CATALOG = {
  de: {
    classes: {
      input:
        "{object} konnte nicht übernommen werden. Bitte prüfen Sie Ihre Angaben.",
      permission:
        "Für {object} fehlt Ihnen die Berechtigung. Bitte fragen Sie die Schule.",
      business_rejection:
        "{object} konnte nicht geändert werden. Bitte prüfen Sie den aktuellen Stand.",
      unavailable:
        "{object} ist gerade nicht erreichbar. Bitte versuchen Sie es erneut.",
      server:
        "{object} konnte nicht bearbeitet werden. Bitte versuchen Sie es später erneut.",
    },
    actions: {
      retry: "Wiederholen",
      copyRequestId: "Vorgangskennung kopieren",
      requestId: "Vorgangskennung: {requestId}",
      crash:
        "{object} konnte nicht bearbeitet werden. Bitte versuchen Sie es später erneut.",
      fieldCheck: "Bitte prüfen Sie dieses Feld.",
    },
    codes: {
      "attendance.web_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.announcement_stale":
        "{object} wurde inzwischen geändert. Bitte laden Sie die Seite neu.",
      "care.care_exception_conflict":
        "{object} wurde inzwischen geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "care.care_exception_past_date":
        "Das Datum für {object} liegt in der Vergangenheit. Bitte wählen Sie ein anderes Datum.",
      "care.care_exception_reason_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "care.care_request_already_pending":
        "Für {object} gibt es bereits eine Anfrage. Bitte prüfen Sie den aktuellen Stand.",
      "care.care_request_field_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.course_request_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.course_requests_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.declaration_closed":
        "{object} ist nicht mehr geöffnet. Bitte fragen Sie Ihre Ansprechperson.",
      "care.declaration_password_incorrect":
        "Das Passwort stimmt nicht. Bitte versuchen Sie es noch einmal.",
      "care.declaration_password_required": "Bitte geben Sie Ihr Passwort ein.",
      "care.declaration_version_changed":
        "{object} wurde inzwischen geändert. Bitte laden Sie die Seite neu.",
      "care.excused_request_not_pending":
        "{object} ist nicht mehr offen. Bitte laden Sie die Seite neu.",
      "care.excused_request_overlap":
        "Die Zeiten für {object} überschneiden sich. Bitte prüfen Sie die Angaben.",
      "care.guardian_contact_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.guardian_email_conflict":
        "Diese E-Mail-Adresse wird bereits verwendet. Bitte prüfen Sie die Adresse.",
      "care.guardian_management_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.guardian_relationship_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.invalid_poll_response":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.invalid_recipients":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.invalid_request_payload":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.invite_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.master_data_edit_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.master_data_invalid_value":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.master_data_no_changes":
        "Für {object} wurde nichts geändert. Bitte prüfen Sie Ihre Angaben.",
      "care.master_data_request_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.notes_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.offering_change_already_pending":
        "Für {object} gibt es bereits eine Anfrage. Bitte prüfen Sie den aktuellen Stand.",
      "care.offering_change_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.offering_changes_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.pickup_change_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.poll_closed":
        "{object} ist nicht mehr geöffnet. Bitte fragen Sie Ihre Ansprechperson.",
      "care.remove_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "care.request_not_found":
        "{object} wurde nicht gefunden. Bitte laden Sie die Seite neu.",
      "care.request_not_open":
        "{object} ist nicht mehr geöffnet. Bitte fragen Sie Ihre Ansprechperson.",
      "care.request_sharing_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "care.sick_note_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "classday.arrival_exception_class_not_found":
        "{object} wurde nicht gefunden. Bitte laden Sie die Seite neu.",
      "classday.arrival_exception_editor_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "classday.arrival_exception_past_date":
        "Das Datum für {object} liegt in der Vergangenheit. Bitte wählen Sie ein anderes Datum.",
      "classday.school_write_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "communication.parent_news_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "communication.poll_not_open":
        "{object} ist nicht mehr geöffnet. Bitte fragen Sie Ihre Ansprechperson.",
      "communication.staff_messaging_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "enrollment.approval_care_offering_missing":
        "Für {object} fehlt ein Betreuungsangebot. Bitte wählen Sie eines aus.",
      "enrollment.care_offering_days_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "enrollment.care_offering_in_use":
        "{object} wird bereits verwendet. Bitte prüfen Sie den aktuellen Stand.",
      "enrollment.care_offering_missing":
        "Für {object} fehlt ein Betreuungsangebot. Bitte wählen Sie eines aus.",
      "enrollment.care_offering_pickup_times_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "enrollment.care_offerings_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "enrollment.change_request_conflict":
        "{object} wurde inzwischen geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "enrollment.class_not_eligible":
        "{object} erfüllt die Voraussetzungen nicht. Bitte fragen Sie Ihre Ansprechperson.",
      "enrollment.complete_withdrawal_confirmation_required":
        "{object} kann noch nicht abgemeldet werden. Bitte bestätigen Sie mit {confirmation}.",
      "enrollment.day_selection_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "enrollment.grade_not_eligible":
        "{object} erfüllt die Voraussetzungen nicht. Bitte fragen Sie Ihre Ansprechperson.",
      "enrollment.invalid_email":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "enrollment.invalid_phone":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "enrollment.late_invite_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "enrollment.phase_care_offering_conflict":
        "{object} wurde inzwischen geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "enrollment.phase_name_exists":
        "{object} gibt es bereits. Bitte wählen Sie eine andere Angabe.",
      "enrollment.phase_not_eligible":
        "{object} erfüllt die Voraussetzungen nicht. Bitte fragen Sie Ihre Ansprechperson.",
      "enrollment.required_care_offering_missing":
        "Für {object} fehlt ein Betreuungsangebot. Bitte wählen Sie eines aus.",
      "enrollment.restore_duplicate":
        "{object} gibt es bereits. Bitte wählen Sie eine andere Angabe.",
      "enrollment.restore_offering_closed":
        "{object} ist nicht mehr geöffnet. Bitte fragen Sie Ihre Ansprechperson.",
      "enrollment.schema_name_exists":
        "{object} gibt es bereits. Bitte wählen Sie eine andere Angabe.",
      "enrollment.student_exists":
        "{object} gibt es bereits. Bitte wählen Sie eine andere Angabe.",
      "enrollment.waitlist_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "enrollment.window_closed":
        "{object} ist nicht mehr geöffnet. Bitte fragen Sie Ihre Ansprechperson.",
      "files.attachment_limit_reached":
        "Für {object} sind zu viele Dateien ausgewählt. Bitte entfernen Sie einen Anhang.",
      "files.folder_name_taken":
        "{object} gibt es bereits. Bitte wählen Sie eine andere Angabe.",
      "grade_transition.preview_stale":
        "{object} wurde inzwischen geändert. Bitte laden Sie die Seite neu.",
      "identity.account_already_has_tenant_access":
        "Diese Person hat schon Zugang zu dieser Schule. Sie finden sie in der Personalliste.",
      "identity.demo_access_expired":
        "Der Demo-Zugang ist abgelaufen. Bitte fordern Sie einen neuen Zugang an.",
      "identity.demo_access_invalid":
        "Der Demo-Link ist ungültig. Bitte fordern Sie einen neuen Link an.",
      "identity.demo_access_rate_limited":
        "Das waren zu viele Versuche. Bitte warten Sie kurz und versuchen Sie es dann erneut.",
      "identity.demo_access_unknown":
        "Diesen Demo-Link gibt es nicht. Bitte fordern Sie einen neuen Link an.",
      "identity.demo_capacity_reached":
        "Gerade sind alle Demo-Plätze belegt. Bitte versuchen Sie es später erneut.",
      "identity.demo_school_preparing":
        "Die Demo-Schule wird gerade vorbereitet. Bitte versuchen Sie es gleich noch einmal.",
      "identity.email_already_exists":
        "Für diese E-Mail-Adresse gibt es schon ein Konto. Bitte verwenden Sie eine andere Adresse.",
      "identity.invitation_account_login_required":
        "Für {object} müssen Sie angemeldet sein. Bitte melden Sie sich an.",
      "identity.preview_token_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "iot.activity_capacity_exceeded":
        "Im Angebot {activity_name} ist kein Platz mehr. Bitte wählen Sie ein anderes Angebot.",
      "iot.deviation_reason_required":
        "{object} weicht vom Plan ab. Bitte geben Sie einen Grund an.",
      "iot.invalid_staff_clock_request":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "iot.invalid_staff_clock_state":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "iot.planned_start_not_reached":
        "{object} kann noch nicht beginnen. Bitte warten Sie bis {planned_start_time} Uhr.",
      "iot.room_capacity_exceeded":
        "Im Raum {room_name} ist kein Platz mehr. Bitte wählen Sie einen anderen Raum.",
      "iot.student_already_active":
        "{object} ist bereits im Raum {room_name}. Bitte prüfen Sie den aktuellen Aufenthalt.",
      "meals.invalid_dishes":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "meals.invalid_meal_date":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "meals.invalid_participation":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "meals.plan_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "meals.registration_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "pickup.bulk_exception_confirmation_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "pickup.invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "pickup.offering_capacity_full":
        "Für {object} ist kein Platz mehr frei. Bitte wählen Sie etwas anderes.",
      "pickup.offerings_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "pickup.preview_stale":
        "{object} wurde inzwischen geändert. Bitte laden Sie die Seite neu.",
      "pickup.resolution_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "presence.activity_participant_limit_reached":
        "Im Angebot {activity_name} ist kein Platz mehr. Bitte wählen Sie ein anderes Angebot.",
      "presence.room_capacity_exceeded":
        "Der Raum {room_name} ist voll ({current_occupancy} von {max_capacity} Plätzen).",
      "rollover.invalid_request":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "rollover.review_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "rooms.color_already_in_use":
        "Diese Farbe hat schon ein anderer Raum. Bitte wählen Sie eine andere Farbe.",
      "school.setup_completed":
        "Die Einrichtung der Schule ist schon abgeschlossen. Bitte laden Sie die Seite neu.",
      "school.setup_incomplete":
        "Die Einrichtung ist noch nicht fertig. Bitte schließen Sie zuerst die offenen Schritte ab.",
      "students.absence_read_required":
        "Für {object} brauchen Sie zusätzlich das Recht „Kinder sehen“. Bitte fragen Sie die Schulleitung.",
      "students.bulk_approval_ineligible":
        "Mindestens eine Anfrage muss einzeln geprüft werden. Es wurde nichts freigegeben.",
      "students.care_day_managed_by_booking":
        "Dieser Tag gehört zu einem gebuchten Angebot. Bitte ändern Sie zuerst die Buchung.",
      "students.care_exception_raced":
        "{object} wurde inzwischen geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "students.care_exit_already_effective":
        "Die Betreuung ist schon beendet. Bitte nutzen Sie „Betreuung wieder aufnehmen“.",
      "students.care_exit_blocked":
        "Die Betreuung wurde nicht beendet. Bitte prüfen Sie die Hinweise bei den Kindern.",
      "students.care_exit_day_in_past":
        "Der letzte Betreuungstag darf nicht in der Vergangenheit liegen.",
      "students.care_exit_invalid_reason": "Bitte wählen Sie einen Grund aus.",
      "students.care_exit_no_students":
        "Bitte wählen Sie mindestens ein Kind aus.",
      "students.care_exit_not_planned":
        "Für dieses Kind ist kein Ende der Betreuung geplant.",
      "students.care_exit_note_not_allowed":
        "Eine eigene Begründung ist nur bei „Anderer Grund“ möglich.",
      "students.care_exit_note_required": "Bitte geben Sie den Grund ein.",
      "students.care_exit_note_too_long":
        "Die Begründung ist zu lang. Bitte kürzen Sie sie.",
      "students.care_exit_preview_changed":
        "Seit der Vorschau hat sich etwas geändert. Bitte prüfen Sie die Vorschau erneut.",
      "students.care_exit_too_many_students":
        "Bitte wählen Sie höchstens 500 Kinder auf einmal aus.",
      "students.care_offerings_disabled":
        "{object} ist hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "students.care_resume_missing":
        "Für dieses Kind ist keine beendete Betreuung hinterlegt.",
      "students.care_resume_not_checked":
        "Bitte bestätigen Sie zuerst die Prüfung. Sonst bleiben Gruppe, Angebote, Wochenplan und Zeiten ungeprüft.",
      "students.care_resume_not_ended":
        "Die Betreuung dieses Kindes läuft noch.",
      "students.care_resume_start_in_past":
        "Der neue Beginn darf nicht in der Vergangenheit liegen.",
      "students.care_withdrawal_after_gap":
        "Der letzte Betreuungstag muss vor dem ersten Tag ohne Buchung liegen.",
      "students.care_withdrawal_date_invalid":
        "Dieser letzte Betreuungstag ist für das Kind nicht möglich. Bitte wählen Sie ein späteres Datum.",
      "students.care_withdrawal_not_found":
        "{object} wurde nicht gefunden. Bitte laden Sie die Seite neu.",
      "students.change_request_not_pending":
        "{object} ist nicht mehr offen. Bitte laden Sie die Seite neu.",
      "students.change_request_stale":
        "{object} wurde inzwischen geändert. Bitte laden Sie die Seite neu.",
      "students.child_quota_reached":
        "Das Kinderkontingent Ihrer Schule ist voll ({occupied_places} von {booked_places} Kindern). Bitte melden Sie sich beim moto-Team.",
      "students.companion_lock_busy":
        "Gerade ändert jemand anderes die Laufgemeinschaft. Bitte versuchen Sie es gleich noch einmal.",
      "students.companion_would_lose_departure":
        "Ein verknüpftes Kind hätte dann keinen Heimweg mehr. Bitte passen Sie zuerst dessen Heimweg an.",
      "students.companions_changed":
        "Die Laufgemeinschaft wurde inzwischen geändert. Bitte laden Sie die Seite neu.",
      "students.conflict_kind_unsupported":
        "Diese Anfragen lassen sich nicht gemeinsam entscheiden. Bitte entscheiden Sie sie einzeln.",
      "students.correction_unsupported":
        "Diese Entscheidung lässt sich nicht zurücknehmen. Bitte ändern Sie den Eintrag direkt beim Kind.",
      "students.deletion_acknowledgement_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "students.deletion_companion_lock_busy":
        "Gerade ändert jemand anderes die Laufgemeinschaft. Bitte versuchen Sie es gleich noch einmal.",
      "students.deletion_constraints_changed":
        "{object} wurde inzwischen geändert. Bitte laden Sie die Seite neu.",
      "students.deletion_invalid_reason":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "students.deletion_preview_changed":
        "{object} wurde inzwischen geändert. Bitte laden Sie die Seite neu.",
      "students.excused_request_status_conflict":
        "Für einen der Tage gibt es schon einen neueren Eintrag. Bitte prüfen Sie die Tage.",
      "students.export_selection_too_large":
        "Die Auswahl umfasst {total} Kinder. Eine Liste darf höchstens {limit} Kinder haben. Bitte grenzen Sie die Auswahl ein, zum Beispiel nach Gruppe oder Klasse.",
      "students.guardian_access_revoked":
        "Die anfragende Person hat keinen Zugriff mehr auf das Kind. Bitte lehnen Sie {object} ab.",
      "students.offering_change_capacity_full":
        "In einem der Angebote ist kein Platz mehr frei. Bitte prüfen Sie die Belegung.",
      "students.offering_change_date_out_of_range":
        "Zu diesem Datum kann die Änderung nicht gelten. Bitte wählen Sie ein anderes Datum.",
      "students.offering_changes_no_enrollment":
        "Für das Kind gibt es keine gültige Anmeldung mehr. Bitte lehnen Sie {object} ab.",
      "students.partial_absence_conflict":
        "{object} wurde inzwischen geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "students.pickup_change_completed":
        "Das Kind ist schon abgemeldet. Die Abholzeit lässt sich nicht mehr ändern.",
      "students.pickup_change_conflict":
        "Für diesen Tag hat die OGS schon etwas eingetragen. Bitte prüfen Sie den Tag.",
      "students.pickup_change_expired":
        "Der Tag liegt in der Vergangenheit. Bitte lehnen Sie {object} ab.",
      "students.pickup_change_impact_changed":
        "Der Betreuungsplan hat sich geändert. Bitte laden Sie die Seite neu.",
      "students.reason_required":
        "Für {object} fehlt eine Begründung. Bitte tragen Sie eine ein.",
      "students.request_not_decided":
        "{object} ist noch nicht entschieden. Bitte entscheiden Sie zuerst.",
      "students.request_not_past":
        "Die Anfrage betrifft noch kommende Tage. Bitte entscheiden Sie sie.",
      "students.request_past":
        "Die Anfrage betrifft nur vergangene Tage. Sie können sie nur ablehnen oder als erledigt markieren.",
      "students.sick_excused_conflict":
        "{object} wurde inzwischen geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "students.staff_profile_required":
        "Diese Zeit haben die Eltern gesetzt. Ändern kann sie nur jemand mit Personalprofil.",
      "students.staff_value_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "students.staff_value_unsupported":
        "Ein eigener Wert ist hier nicht möglich. Bitte wählen Sie einen Wunsch oder „Keine Änderung“.",
      "students.status_day_conflict":
        "An einigen Tagen gibt es schon einen Eintrag. Diese Tage wurden nicht geändert.",
      "substitutions.invalid_period":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "substitutions.invalid_target":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "timetable.calendar_period_care_offering_conflict":
        "{object} wurde inzwischen geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "timetable.calendar_period_overlap_conflict":
        "{object} überschneidet sich mit anderen Zeiträumen. Bitte prüfen Sie die Termine.",
      "timetable.complete_too_early":
        "Der Termin kann erst nach seinem Ende abgeschlossen werden.",
      "timetable.completion_confirmation_stale":
        "{object} wurde inzwischen geändert. Bitte laden Sie die Seite neu.",
      "timetable.duplicate_instance":
        "Diesen Termin gibt es schon. Bitte laden Sie die Seite neu.",
      "timetable.guardian_notice_disabled":
        "Hinweise an Eltern sind hier zurzeit nicht verfügbar. Bitte fragen Sie Ihre Ansprechperson.",
      "timetable.instance_moved":
        "Der Termin wurde inzwischen geändert. Bitte laden Sie die Seite neu.",
      "timetable.only_supervisor_replacement_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "timetable.pickup_extension_not_found":
        "{object} wurde nicht gefunden. Bitte laden Sie die Seite neu.",
      "timetable.staff_absent_on_date":
        "Die Person ist an diesem Tag abwesend. Bitte wählen Sie eine andere Person.",
      "timetable.staff_absent_on_target":
        "Die Person ist an diesem Tag abwesend. Bitte wählen Sie eine andere Person.",
      "timetable.staff_already_on_target":
        "Die Person ist für diesen Termin schon eingeteilt.",
      "timetable.start_too_early":
        "Der Termin kann noch nicht gestartet werden. Bitte versuchen Sie es kurz vor Beginn erneut.",
      "timetable.start_window_expired":
        "Der Termin kann nicht mehr gestartet werden. Die Startzeit ist vorbei.",
      "timetable.template_care_offering_conflict":
        "{object} wurde inzwischen geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "timetable.template_roster_rebase_conflict":
        "{object} wurde inzwischen geändert. Bitte prüfen Sie Ihre Angaben erneut.",
      "timetable.template_start_in_past":
        "Das Datum für {object} liegt in der Vergangenheit. Bitte wählen Sie ein anderes Datum.",
      "timetable.template_start_predecessor_overlap":
        "Die Zeiten für {object} überschneiden sich. Bitte prüfen Sie die Angaben.",
      "timetable.understaffed_still_staffed":
        "Für den Termin ist noch Personal eingeteilt. Bitte nehmen Sie das Personal zuerst heraus.",
      "workforce.later_month_closed":
        "{object} ist nicht mehr geöffnet. Bitte fragen Sie Ihre Ansprechperson.",
      "workforce.month_not_closed":
        "Der Monat für {object} ist noch offen. Bitte schließen Sie ihn zuerst ab.",
      "workforce.opening_balance_already_exists":
        "{object} gibt es bereits. Bitte wählen Sie eine andere Angabe.",
      "workforce.personnel_number_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "workforce.personnel_number_taken":
        "{object} gibt es bereits. Bitte wählen Sie eine andere Angabe.",
      "workforce.stammdaten_invalid":
        "{object} enthält ungültige Angaben. Bitte prüfen Sie Ihre Eingaben.",
      "workforce.vacation_opening_already_exists":
        "{object} gibt es bereits. Bitte wählen Sie eine andere Angabe.",
      "workforce.vacation_quota_reason_required":
        "Für {object} fehlt eine Angabe. Bitte ergänzen Sie das markierte Feld.",
      "workforce.work_session_overlap":
        "Die Zeiten für {object} überschneiden sich. Bitte prüfen Sie die Angaben.",
    },
  },
  en: {
    classes: {
      input: "{object} could not be saved. Please check your entries.",
      permission: "You cannot access {object}. Please contact the school.",
      business_rejection:
        "{object} could not be changed. Please check its current status.",
      unavailable: "{object} is unavailable right now. Please try again.",
      server: "{object} could not be processed. Please try again later.",
    },
    actions: {
      retry: "Try again",
      copyRequestId: "Copy request ID",
      requestId: "Request ID: {requestId}",
      crash: "{object} could not be processed. Please try again later.",
      fieldCheck: "Please check this field.",
    },
    codes: {
      "care.declaration_password_incorrect":
        "The password is not correct. Please try again.",
      "care.declaration_password_required": "Please enter your password.",
      "identity.account_already_has_tenant_access":
        "This person already has access to this school. You can find them in the staff list.",
      "identity.email_already_exists":
        "There is already an account for this email address. Please use a different address.",
      "students.export_selection_too_large":
        "The selection has {total} children. A list can have at most {limit} children. Please narrow the selection, for example by group or class.",
      "students.staff_profile_required":
        "The parents set this time. Only someone with a staff profile can change it.",
      "students.status_day_conflict":
        "Some days already have an entry. These days were not changed.",
    },
  },
  ru: {
    classes: {
      input: "Не удалось сохранить: {object}. Проверьте введённые данные.",
      permission: "У вас нет доступа к: {object}. Обратитесь в школу.",
      business_rejection:
        "Не удалось изменить: {object}. Проверьте текущее состояние.",
      unavailable: "{object} сейчас недоступен. Повторите попытку.",
      server: "Не удалось обработать: {object}. Повторите попытку позже.",
    },
    actions: {
      retry: "Повторить",
      copyRequestId: "Скопировать номер запроса",
      requestId: "Номер запроса: {requestId}",
      crash: "Не удалось обработать: {object}. Повторите попытку позже.",
      fieldCheck: "Проверьте это поле.",
    },
    codes: {
      "care.declaration_password_incorrect":
        "Пароль неверный. Пожалуйста, попробуйте ещё раз.",
      "care.declaration_password_required": "Пожалуйста, введите пароль.",
      "identity.account_already_has_tenant_access":
        "У этого человека уже есть доступ к этой школе. Он есть в списке сотрудников.",
      "identity.email_already_exists":
        "Для этого адреса электронной почты уже есть учётная запись. Укажите другой адрес.",
      "students.export_selection_too_large":
        "Выбрано детей: {total}. В списке может быть не больше {limit} детей. Сузьте выбор, например по группе или классу.",
      "students.staff_profile_required":
        "Это время установили родители. Изменить его может только сотрудник с профилем персонала.",
      "students.status_day_conflict":
        "На некоторые дни уже есть запись. Эти дни не изменены.",
    },
  },
  sq: {
    classes: {
      input: "Nuk u ruajt: {object}. Kontrolloni të dhënat.",
      permission: "Nuk keni qasje te: {object}. Kontaktoni shkollën.",
      business_rejection:
        "Nuk u ndryshua: {object}. Kontrolloni gjendjen aktuale.",
      unavailable: "{object} nuk është i disponueshëm tani. Provoni përsëri.",
      server: "Nuk u përpunua: {object}. Provoni përsëri më vonë.",
    },
    actions: {
      retry: "Provo përsëri",
      copyRequestId: "Kopjo numrin e kërkesës",
      requestId: "Numri i kërkesës: {requestId}",
      crash: "Nuk u përpunua: {object}. Provoni përsëri më vonë.",
      fieldCheck: "Kontrolloni këtë fushë.",
    },
    codes: {
      "care.declaration_password_incorrect":
        "Fjalëkalimi nuk është i saktë. Ju lutemi provoni përsëri.",
      "care.declaration_password_required": "Ju lutemi shkruani fjalëkalimin.",
      "identity.account_already_has_tenant_access":
        "Ky person ka tashmë qasje në këtë shkollë. E gjeni në listën e personelit.",
      "identity.email_already_exists":
        "Për këtë adresë email ka tashmë një llogari. Ju lutemi përdorni një adresë tjetër.",
      "students.export_selection_too_large":
        "Përzgjedhja ka {total} fëmijë. Një listë mund të ketë më së shumti {limit} fëmijë. Ju lutemi ngushtoni përzgjedhjen, p.sh. sipas grupit ose klasës.",
      "students.staff_profile_required":
        "Këtë orë e kanë vendosur prindërit. Vetëm dikush me profil stafi mund ta ndryshojë.",
      "students.status_day_conflict":
        "Disa ditë kanë tashmë një regjistrim. Këto ditë nuk u ndryshuan.",
    },
  },
  pl: {
    classes: {
      input: "Nie udało się zapisać: {object}. Sprawdź wpisane dane.",
      permission: "Nie masz dostępu do: {object}. Skontaktuj się ze szkołą.",
      business_rejection:
        "Nie udało się zmienić: {object}. Sprawdź aktualny stan.",
      unavailable: "{object} jest teraz niedostępne. Spróbuj ponownie.",
      server: "Nie udało się przetworzyć: {object}. Spróbuj ponownie później.",
    },
    actions: {
      retry: "Spróbuj ponownie",
      copyRequestId: "Kopiuj numer zgłoszenia",
      requestId: "Numer zgłoszenia: {requestId}",
      crash: "Nie udało się przetworzyć: {object}. Spróbuj ponownie później.",
      fieldCheck: "Sprawdź to pole.",
    },
    codes: {
      "care.declaration_password_incorrect":
        "Hasło jest nieprawidłowe. Spróbuj ponownie.",
      "care.declaration_password_required": "Wpisz swoje hasło.",
      "identity.account_already_has_tenant_access":
        "Ta osoba ma już dostęp do tej szkoły. Znajdziesz ją na liście personelu.",
      "identity.email_already_exists":
        "Dla tego adresu e-mail istnieje już konto. Użyj innego adresu.",
      "students.export_selection_too_large":
        "Wybrano {total} dzieci. Lista może mieć najwyżej {limit} dzieci. Zawęź wybór, na przykład według grupy lub klasy.",
      "students.staff_profile_required":
        "Ten czas ustawili rodzice. Zmienić go może tylko osoba z profilem pracownika.",
      "students.status_day_conflict":
        "Niektóre dni mają już wpis. Tych dni nie zmieniono.",
    },
  },
  tr: {
    classes: {
      input: "{object} kaydedilemedi. Girdiğiniz bilgileri kontrol edin.",
      permission: "{object} için erişim izniniz yok. Okulla iletişime geçin.",
      business_rejection:
        "{object} değiştirilemedi. Güncel durumu kontrol edin.",
      unavailable: "{object} şu anda kullanılamıyor. Yeniden deneyin.",
      server: "{object} işlenemedi. Daha sonra yeniden deneyin.",
    },
    actions: {
      retry: "Yeniden dene",
      copyRequestId: "İstek numarasını kopyala",
      requestId: "İstek numarası: {requestId}",
      crash: "{object} işlenemedi. Daha sonra yeniden deneyin.",
      fieldCheck: "Bu alanı kontrol edin.",
    },
    codes: {
      "care.declaration_password_incorrect":
        "Şifre doğru değil. Lütfen tekrar deneyin.",
      "care.declaration_password_required": "Lütfen şifrenizi girin.",
      "identity.account_already_has_tenant_access":
        "Bu kişinin bu okula zaten erişimi var. Kişiyi personel listesinde bulabilirsiniz.",
      "identity.email_already_exists":
        "Bu e-posta adresi için zaten bir hesap var. Lütfen başka bir adres kullanın.",
      "students.export_selection_too_large":
        "Seçimde {total} çocuk var. Bir liste en fazla {limit} çocuk içerebilir. Lütfen seçimi daraltın, örneğin gruba veya sınıfa göre.",
      "students.staff_profile_required":
        "Bu saati veliler belirledi. Yalnızca personel profili olan biri değiştirebilir.",
      "students.status_day_conflict":
        "Bazı günlerde zaten bir kayıt var. Bu günler değiştirilmedi.",
    },
  },
  uk: {
    classes: {
      input: "Не вдалося зберегти: {object}. Перевірте введені дані.",
      permission: "У вас немає доступу до: {object}. Зверніться до школи.",
      business_rejection:
        "Не вдалося змінити: {object}. Перевірте поточний стан.",
      unavailable: "{object} зараз недоступний. Спробуйте ще раз.",
      server: "Не вдалося обробити: {object}. Спробуйте пізніше.",
    },
    actions: {
      retry: "Спробувати ще раз",
      copyRequestId: "Скопіювати номер запиту",
      requestId: "Номер запиту: {requestId}",
      crash: "Не вдалося обробити: {object}. Спробуйте пізніше.",
      fieldCheck: "Перевірте це поле.",
    },
    codes: {
      "care.declaration_password_incorrect":
        "Пароль неправильний. Будь ласка, спробуйте ще раз.",
      "care.declaration_password_required": "Будь ласка, введіть пароль.",
      "identity.account_already_has_tenant_access":
        "Ця особа вже має доступ до цієї школи. Її можна знайти в списку персоналу.",
      "identity.email_already_exists":
        "Для цієї адреси електронної пошти вже є обліковий запис. Укажіть іншу адресу.",
      "students.export_selection_too_large":
        "Вибрано дітей: {total}. У списку може бути не більше {limit} дітей. Звузьте вибір, наприклад за групою або класом.",
      "students.staff_profile_required":
        "Цей час встановили батьки. Змінити його може лише працівник із профілем персоналу.",
      "students.status_day_conflict":
        "На деякі дні вже є запис. Ці дні не змінено.",
    },
  },
} as const;
